
/*
Auto-generated by CVXPYgen on May 05, 2025 at 01:36:10.
Content: Function declarations.
*/

#include "cpg_workspace.h"

// Update user-defined parameter values
extern void cpg_update_param7(cpg_int idx, cpg_float val);
extern void cpg_update_param15(cpg_float val);
extern void cpg_update_param17(cpg_float val);
extern void cpg_update_param8(cpg_int idx, cpg_float val);
extern void cpg_update_param16(cpg_float val);
extern void cpg_update_param18(cpg_float val);
extern void cpg_update_param9(cpg_float val);
extern void cpg_update_param10(cpg_int idx, cpg_float val);
extern void cpg_update_param11(cpg_int idx, cpg_float val);
extern void cpg_update_param12(cpg_int idx, cpg_float val);
extern void cpg_update_param13(cpg_int idx, cpg_float val);
extern void cpg_update_param14(cpg_int idx, cpg_float val);

// Map user-defined to canonical parameters
extern void cpg_canonicalize_A();
extern void cpg_canonicalize_b();
extern void cpg_canonicalize_G();
extern void cpg_canonicalize_h();

// Retrieve primal solution in terms of user-defined variables
extern void cpg_retrieve_prim();

// Retrieve dual solution in terms of user-defined constraints
extern void cpg_retrieve_dual();

// Retrieve solver information
extern void cpg_retrieve_info();

// Copy canonical parameters for preconditioning
extern void cpg_copy_c();
extern void cpg_copy_A();
extern void cpg_copy_b();
extern void cpg_copy_G();
extern void cpg_copy_h();
extern void cpg_copy_all();

// Solve via canonicalization, canonical solve, retrieval
extern void cpg_solve();

// Update solver settings
extern void cpg_set_solver_default_settings();
extern void cpg_set_solver_max_iters(cpg_int max_iters_new);
extern void cpg_set_solver_bisect_iters(cpg_int bisect_iters_new);
extern void cpg_set_solver_ruiz_iters(cpg_int ruiz_iters_new);
extern void cpg_set_solver_iter_ref_iters(cpg_int iter_ref_iters_new);
extern void cpg_set_solver_kkt_static_reg(cpg_float kkt_static_reg_new);
extern void cpg_set_solver_kkt_dynamic_reg(cpg_float kkt_dynamic_reg_new);
extern void cpg_set_solver_abstol(cpg_float abstol_new);
extern void cpg_set_solver_reltol(cpg_float reltol_new);
extern void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new);
extern void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new);
extern void cpg_set_solver_verbose(cpg_int verbose_new);
