
/*
Auto-generated by CVXPYgen on June 03, 2025 at 04:47:27.
Content: Function declarations.
*/

#include "cpg_workspace.h"

// Update user-defined parameter values
extern void mpc_socp__cpg_update_param3412(cpg_int idx, cpg_float val);
extern void mpc_socp__cpg_update_param3405(cpg_int idx, cpg_float val);
extern void mpc_socp__cpg_update_param3406(cpg_int idx, cpg_float val);
extern void mpc_socp__cpg_update_param3409(cpg_int idx, cpg_float val);
extern void mpc_socp__cpg_update_param3410(cpg_int idx, cpg_float val);
extern void mpc_socp__cpg_update_param3407(cpg_int idx, cpg_float val);
extern void mpc_socp__cpg_update_param3408(cpg_int idx, cpg_float val);

// Map user-defined to canonical parameters
extern void mpc_socp__cpg_canonicalize_A();
extern void mpc_socp__cpg_canonicalize_b();
extern void mpc_socp__cpg_canonicalize_G();
extern void mpc_socp__cpg_canonicalize_h();

// Retrieve primal solution in terms of user-defined variables
extern void mpc_socp__cpg_retrieve_prim();

// Retrieve dual solution in terms of user-defined constraints
extern void mpc_socp__cpg_retrieve_dual();

// Retrieve solver information
extern void mpc_socp__cpg_retrieve_info();

// Copy canonical parameters for preconditioning
extern void mpc_socp__cpg_copy_P();
extern void mpc_socp__cpg_copy_c();
extern void mpc_socp__cpg_copy_A();
extern void mpc_socp__cpg_copy_b();
extern void mpc_socp__cpg_copy_G();
extern void mpc_socp__cpg_copy_h();
extern void mpc_socp__cpg_copy_all();

// Solve via canonicalization, canonical solve, retrieval
extern void mpc_socp__cpg_solve();

// Update solver settings
extern void mpc_socp__cpg_set_solver_default_settings();
extern void mpc_socp__cpg_set_solver_max_iters(cpg_int max_iters_new);
extern void mpc_socp__cpg_set_solver_bisect_iters(cpg_int bisect_iters_new);
extern void mpc_socp__cpg_set_solver_ruiz_iters(cpg_int ruiz_iters_new);
extern void mpc_socp__cpg_set_solver_iter_ref_iters(cpg_int iter_ref_iters_new);
extern void mpc_socp__cpg_set_solver_kkt_static_reg(cpg_float kkt_static_reg_new);
extern void mpc_socp__cpg_set_solver_kkt_dynamic_reg(cpg_float kkt_dynamic_reg_new);
extern void mpc_socp__cpg_set_solver_abstol(cpg_float abstol_new);
extern void mpc_socp__cpg_set_solver_reltol(cpg_float reltol_new);
extern void mpc_socp__cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new);
extern void mpc_socp__cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new);
extern void mpc_socp__cpg_set_solver_verbose(cpg_int verbose_new);
