
/*
Auto-generated by CVXPYgen on May 26, 2025 at 22:53:23.
Content: Python binding with pybind11.
*/

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <ctime>
#include "cpg_module.hpp"

extern "C" {
    #include "include/cpg_workspace.h"
    #include "include/cpg_solve.h"
}

namespace py = pybind11;

static int i;

mpc_socp__CPG_Result_cpp_t mpc_socp__solve_cpp(struct mpc_socp__CPG_Updated_cpp_t& CPG_Updated_cpp, struct mpc_socp__CPG_Params_cpp_t& CPG_Params_cpp){

    // Pass changed user-defined parameter values to the solver
    if (CPG_Updated_cpp.param3972) {
        for(i=0; i<476; i++) {
            mpc_socp__cpg_update_param3972(i, CPG_Params_cpp.param3972[i]);
        }
    }
    if (CPG_Updated_cpp.param3965) {
        for(i=0; i<14; i++) {
            mpc_socp__cpg_update_param3965(i, CPG_Params_cpp.param3965[i]);
        }
    }
    if (CPG_Updated_cpp.param3966) {
        for(i=0; i<490; i++) {
            mpc_socp__cpg_update_param3966(i, CPG_Params_cpp.param3966[i]);
        }
    }
    if (CPG_Updated_cpp.param3969) {
        for(i=0; i<6664; i++) {
            mpc_socp__cpg_update_param3969(i, CPG_Params_cpp.param3969[i]);
        }
    }
    if (CPG_Updated_cpp.param3970) {
        for(i=0; i<1428; i++) {
            mpc_socp__cpg_update_param3970(i, CPG_Params_cpp.param3970[i]);
        }
    }
    if (CPG_Updated_cpp.param3967) {
        for(i=0; i<102; i++) {
            mpc_socp__cpg_update_param3967(i, CPG_Params_cpp.param3967[i]);
        }
    }
    if (CPG_Updated_cpp.param3968) {
        for(i=0; i<34; i++) {
            mpc_socp__cpg_update_param3968(i, CPG_Params_cpp.param3968[i]);
        }
    }

    // Solve
    std::clock_t ASA_start = std::clock();
    mpc_socp__cpg_solve();
    std::clock_t ASA_end = std::clock();

    // Arrange and return results
    mpc_socp__CPG_Prim_cpp_t CPG_Prim_cpp {};
    for(i=0; i<490; i++) {
        CPG_Prim_cpp.var3963[i] = mpc_socp__CPG_Prim.var3963[i];
    }
    for(i=0; i<102; i++) {
        CPG_Prim_cpp.var3964[i] = mpc_socp__CPG_Prim.var3964[i];
    }
    mpc_socp__CPG_Dual_cpp_t CPG_Dual_cpp {};
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d0[i] = mpc_socp__CPG_Dual.d0[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d1[i] = mpc_socp__CPG_Dual.d1[i];
    }
    CPG_Dual_cpp.d2 = mpc_socp__CPG_Dual.d2;
    CPG_Dual_cpp.d3 = mpc_socp__CPG_Dual.d3;
    CPG_Dual_cpp.d4 = mpc_socp__CPG_Dual.d4;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d5[i] = mpc_socp__CPG_Dual.d5[i];
    }
    CPG_Dual_cpp.d6 = mpc_socp__CPG_Dual.d6;
    CPG_Dual_cpp.d7 = mpc_socp__CPG_Dual.d7;
    CPG_Dual_cpp.d8 = mpc_socp__CPG_Dual.d8;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d9[i] = mpc_socp__CPG_Dual.d9[i];
    }
    CPG_Dual_cpp.d10 = mpc_socp__CPG_Dual.d10;
    CPG_Dual_cpp.d11 = mpc_socp__CPG_Dual.d11;
    CPG_Dual_cpp.d12 = mpc_socp__CPG_Dual.d12;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d13[i] = mpc_socp__CPG_Dual.d13[i];
    }
    CPG_Dual_cpp.d14 = mpc_socp__CPG_Dual.d14;
    CPG_Dual_cpp.d15 = mpc_socp__CPG_Dual.d15;
    CPG_Dual_cpp.d16 = mpc_socp__CPG_Dual.d16;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d17[i] = mpc_socp__CPG_Dual.d17[i];
    }
    CPG_Dual_cpp.d18 = mpc_socp__CPG_Dual.d18;
    CPG_Dual_cpp.d19 = mpc_socp__CPG_Dual.d19;
    CPG_Dual_cpp.d20 = mpc_socp__CPG_Dual.d20;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d21[i] = mpc_socp__CPG_Dual.d21[i];
    }
    CPG_Dual_cpp.d22 = mpc_socp__CPG_Dual.d22;
    CPG_Dual_cpp.d23 = mpc_socp__CPG_Dual.d23;
    CPG_Dual_cpp.d24 = mpc_socp__CPG_Dual.d24;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d25[i] = mpc_socp__CPG_Dual.d25[i];
    }
    CPG_Dual_cpp.d26 = mpc_socp__CPG_Dual.d26;
    CPG_Dual_cpp.d27 = mpc_socp__CPG_Dual.d27;
    CPG_Dual_cpp.d28 = mpc_socp__CPG_Dual.d28;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d29[i] = mpc_socp__CPG_Dual.d29[i];
    }
    CPG_Dual_cpp.d30 = mpc_socp__CPG_Dual.d30;
    CPG_Dual_cpp.d31 = mpc_socp__CPG_Dual.d31;
    CPG_Dual_cpp.d32 = mpc_socp__CPG_Dual.d32;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d33[i] = mpc_socp__CPG_Dual.d33[i];
    }
    CPG_Dual_cpp.d34 = mpc_socp__CPG_Dual.d34;
    CPG_Dual_cpp.d35 = mpc_socp__CPG_Dual.d35;
    CPG_Dual_cpp.d36 = mpc_socp__CPG_Dual.d36;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d37[i] = mpc_socp__CPG_Dual.d37[i];
    }
    CPG_Dual_cpp.d38 = mpc_socp__CPG_Dual.d38;
    CPG_Dual_cpp.d39 = mpc_socp__CPG_Dual.d39;
    CPG_Dual_cpp.d40 = mpc_socp__CPG_Dual.d40;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d41[i] = mpc_socp__CPG_Dual.d41[i];
    }
    CPG_Dual_cpp.d42 = mpc_socp__CPG_Dual.d42;
    CPG_Dual_cpp.d43 = mpc_socp__CPG_Dual.d43;
    CPG_Dual_cpp.d44 = mpc_socp__CPG_Dual.d44;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d45[i] = mpc_socp__CPG_Dual.d45[i];
    }
    CPG_Dual_cpp.d46 = mpc_socp__CPG_Dual.d46;
    CPG_Dual_cpp.d47 = mpc_socp__CPG_Dual.d47;
    CPG_Dual_cpp.d48 = mpc_socp__CPG_Dual.d48;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d49[i] = mpc_socp__CPG_Dual.d49[i];
    }
    CPG_Dual_cpp.d50 = mpc_socp__CPG_Dual.d50;
    CPG_Dual_cpp.d51 = mpc_socp__CPG_Dual.d51;
    CPG_Dual_cpp.d52 = mpc_socp__CPG_Dual.d52;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d53[i] = mpc_socp__CPG_Dual.d53[i];
    }
    CPG_Dual_cpp.d54 = mpc_socp__CPG_Dual.d54;
    CPG_Dual_cpp.d55 = mpc_socp__CPG_Dual.d55;
    CPG_Dual_cpp.d56 = mpc_socp__CPG_Dual.d56;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d57[i] = mpc_socp__CPG_Dual.d57[i];
    }
    CPG_Dual_cpp.d58 = mpc_socp__CPG_Dual.d58;
    CPG_Dual_cpp.d59 = mpc_socp__CPG_Dual.d59;
    CPG_Dual_cpp.d60 = mpc_socp__CPG_Dual.d60;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d61[i] = mpc_socp__CPG_Dual.d61[i];
    }
    CPG_Dual_cpp.d62 = mpc_socp__CPG_Dual.d62;
    CPG_Dual_cpp.d63 = mpc_socp__CPG_Dual.d63;
    CPG_Dual_cpp.d64 = mpc_socp__CPG_Dual.d64;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d65[i] = mpc_socp__CPG_Dual.d65[i];
    }
    CPG_Dual_cpp.d66 = mpc_socp__CPG_Dual.d66;
    CPG_Dual_cpp.d67 = mpc_socp__CPG_Dual.d67;
    CPG_Dual_cpp.d68 = mpc_socp__CPG_Dual.d68;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d69[i] = mpc_socp__CPG_Dual.d69[i];
    }
    CPG_Dual_cpp.d70 = mpc_socp__CPG_Dual.d70;
    CPG_Dual_cpp.d71 = mpc_socp__CPG_Dual.d71;
    CPG_Dual_cpp.d72 = mpc_socp__CPG_Dual.d72;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d73[i] = mpc_socp__CPG_Dual.d73[i];
    }
    CPG_Dual_cpp.d74 = mpc_socp__CPG_Dual.d74;
    CPG_Dual_cpp.d75 = mpc_socp__CPG_Dual.d75;
    CPG_Dual_cpp.d76 = mpc_socp__CPG_Dual.d76;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d77[i] = mpc_socp__CPG_Dual.d77[i];
    }
    CPG_Dual_cpp.d78 = mpc_socp__CPG_Dual.d78;
    CPG_Dual_cpp.d79 = mpc_socp__CPG_Dual.d79;
    CPG_Dual_cpp.d80 = mpc_socp__CPG_Dual.d80;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d81[i] = mpc_socp__CPG_Dual.d81[i];
    }
    CPG_Dual_cpp.d82 = mpc_socp__CPG_Dual.d82;
    CPG_Dual_cpp.d83 = mpc_socp__CPG_Dual.d83;
    CPG_Dual_cpp.d84 = mpc_socp__CPG_Dual.d84;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d85[i] = mpc_socp__CPG_Dual.d85[i];
    }
    CPG_Dual_cpp.d86 = mpc_socp__CPG_Dual.d86;
    CPG_Dual_cpp.d87 = mpc_socp__CPG_Dual.d87;
    CPG_Dual_cpp.d88 = mpc_socp__CPG_Dual.d88;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d89[i] = mpc_socp__CPG_Dual.d89[i];
    }
    CPG_Dual_cpp.d90 = mpc_socp__CPG_Dual.d90;
    CPG_Dual_cpp.d91 = mpc_socp__CPG_Dual.d91;
    CPG_Dual_cpp.d92 = mpc_socp__CPG_Dual.d92;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d93[i] = mpc_socp__CPG_Dual.d93[i];
    }
    CPG_Dual_cpp.d94 = mpc_socp__CPG_Dual.d94;
    CPG_Dual_cpp.d95 = mpc_socp__CPG_Dual.d95;
    CPG_Dual_cpp.d96 = mpc_socp__CPG_Dual.d96;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d97[i] = mpc_socp__CPG_Dual.d97[i];
    }
    CPG_Dual_cpp.d98 = mpc_socp__CPG_Dual.d98;
    CPG_Dual_cpp.d99 = mpc_socp__CPG_Dual.d99;
    CPG_Dual_cpp.d100 = mpc_socp__CPG_Dual.d100;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d101[i] = mpc_socp__CPG_Dual.d101[i];
    }
    CPG_Dual_cpp.d102 = mpc_socp__CPG_Dual.d102;
    CPG_Dual_cpp.d103 = mpc_socp__CPG_Dual.d103;
    CPG_Dual_cpp.d104 = mpc_socp__CPG_Dual.d104;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d105[i] = mpc_socp__CPG_Dual.d105[i];
    }
    CPG_Dual_cpp.d106 = mpc_socp__CPG_Dual.d106;
    CPG_Dual_cpp.d107 = mpc_socp__CPG_Dual.d107;
    CPG_Dual_cpp.d108 = mpc_socp__CPG_Dual.d108;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d109[i] = mpc_socp__CPG_Dual.d109[i];
    }
    CPG_Dual_cpp.d110 = mpc_socp__CPG_Dual.d110;
    CPG_Dual_cpp.d111 = mpc_socp__CPG_Dual.d111;
    CPG_Dual_cpp.d112 = mpc_socp__CPG_Dual.d112;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d113[i] = mpc_socp__CPG_Dual.d113[i];
    }
    CPG_Dual_cpp.d114 = mpc_socp__CPG_Dual.d114;
    CPG_Dual_cpp.d115 = mpc_socp__CPG_Dual.d115;
    CPG_Dual_cpp.d116 = mpc_socp__CPG_Dual.d116;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d117[i] = mpc_socp__CPG_Dual.d117[i];
    }
    CPG_Dual_cpp.d118 = mpc_socp__CPG_Dual.d118;
    CPG_Dual_cpp.d119 = mpc_socp__CPG_Dual.d119;
    CPG_Dual_cpp.d120 = mpc_socp__CPG_Dual.d120;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d121[i] = mpc_socp__CPG_Dual.d121[i];
    }
    CPG_Dual_cpp.d122 = mpc_socp__CPG_Dual.d122;
    CPG_Dual_cpp.d123 = mpc_socp__CPG_Dual.d123;
    CPG_Dual_cpp.d124 = mpc_socp__CPG_Dual.d124;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d125[i] = mpc_socp__CPG_Dual.d125[i];
    }
    CPG_Dual_cpp.d126 = mpc_socp__CPG_Dual.d126;
    CPG_Dual_cpp.d127 = mpc_socp__CPG_Dual.d127;
    CPG_Dual_cpp.d128 = mpc_socp__CPG_Dual.d128;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d129[i] = mpc_socp__CPG_Dual.d129[i];
    }
    CPG_Dual_cpp.d130 = mpc_socp__CPG_Dual.d130;
    CPG_Dual_cpp.d131 = mpc_socp__CPG_Dual.d131;
    CPG_Dual_cpp.d132 = mpc_socp__CPG_Dual.d132;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d133[i] = mpc_socp__CPG_Dual.d133[i];
    }
    CPG_Dual_cpp.d134 = mpc_socp__CPG_Dual.d134;
    CPG_Dual_cpp.d135 = mpc_socp__CPG_Dual.d135;
    CPG_Dual_cpp.d136 = mpc_socp__CPG_Dual.d136;
    mpc_socp__CPG_Info_cpp_t CPG_Info_cpp {};
    CPG_Info_cpp.obj_val = mpc_socp__CPG_Info.obj_val;
    CPG_Info_cpp.iter = mpc_socp__CPG_Info.iter;
    CPG_Info_cpp.status = mpc_socp__CPG_Info.status;
    CPG_Info_cpp.pri_res = mpc_socp__CPG_Info.pri_res;
    CPG_Info_cpp.dua_res = mpc_socp__CPG_Info.dua_res;
    CPG_Info_cpp.time = 1.0 * (ASA_end - ASA_start) / CLOCKS_PER_SEC;
    mpc_socp__CPG_Result_cpp_t CPG_Result_cpp {};
    CPG_Result_cpp.prim = CPG_Prim_cpp;
    CPG_Result_cpp.dual = CPG_Dual_cpp;
    CPG_Result_cpp.info = CPG_Info_cpp;
    return CPG_Result_cpp;

}

PYBIND11_MODULE(cpg_module, m) {

    py::class_<mpc_socp__CPG_Params_cpp_t>(m, "mpc_socp__cpg_params")
            .def(py::init<>())
            .def_readwrite("param3972", &mpc_socp__CPG_Params_cpp_t::param3972)
            .def_readwrite("param3965", &mpc_socp__CPG_Params_cpp_t::param3965)
            .def_readwrite("param3966", &mpc_socp__CPG_Params_cpp_t::param3966)
            .def_readwrite("param3969", &mpc_socp__CPG_Params_cpp_t::param3969)
            .def_readwrite("param3970", &mpc_socp__CPG_Params_cpp_t::param3970)
            .def_readwrite("param3967", &mpc_socp__CPG_Params_cpp_t::param3967)
            .def_readwrite("param3968", &mpc_socp__CPG_Params_cpp_t::param3968)
            ;

    py::class_<mpc_socp__CPG_Updated_cpp_t>(m, "mpc_socp__cpg_updated")
            .def(py::init<>())
            .def_readwrite("param3972", &mpc_socp__CPG_Updated_cpp_t::param3972)
            .def_readwrite("param3965", &mpc_socp__CPG_Updated_cpp_t::param3965)
            .def_readwrite("param3966", &mpc_socp__CPG_Updated_cpp_t::param3966)
            .def_readwrite("param3969", &mpc_socp__CPG_Updated_cpp_t::param3969)
            .def_readwrite("param3970", &mpc_socp__CPG_Updated_cpp_t::param3970)
            .def_readwrite("param3967", &mpc_socp__CPG_Updated_cpp_t::param3967)
            .def_readwrite("param3968", &mpc_socp__CPG_Updated_cpp_t::param3968)
            ;

    py::class_<mpc_socp__CPG_Prim_cpp_t>(m, "mpc_socp__cpg_prim")
            .def(py::init<>())
            .def_readwrite("var3963", &mpc_socp__CPG_Prim_cpp_t::var3963)
            .def_readwrite("var3964", &mpc_socp__CPG_Prim_cpp_t::var3964)
            ;

    py::class_<mpc_socp__CPG_Dual_cpp_t>(m, "mpc_socp__cpg_dual")
            .def(py::init<>())
            .def_readwrite("d0", &mpc_socp__CPG_Dual_cpp_t::d0)
            .def_readwrite("d1", &mpc_socp__CPG_Dual_cpp_t::d1)
            .def_readwrite("d2", &mpc_socp__CPG_Dual_cpp_t::d2)
            .def_readwrite("d3", &mpc_socp__CPG_Dual_cpp_t::d3)
            .def_readwrite("d4", &mpc_socp__CPG_Dual_cpp_t::d4)
            .def_readwrite("d5", &mpc_socp__CPG_Dual_cpp_t::d5)
            .def_readwrite("d6", &mpc_socp__CPG_Dual_cpp_t::d6)
            .def_readwrite("d7", &mpc_socp__CPG_Dual_cpp_t::d7)
            .def_readwrite("d8", &mpc_socp__CPG_Dual_cpp_t::d8)
            .def_readwrite("d9", &mpc_socp__CPG_Dual_cpp_t::d9)
            .def_readwrite("d10", &mpc_socp__CPG_Dual_cpp_t::d10)
            .def_readwrite("d11", &mpc_socp__CPG_Dual_cpp_t::d11)
            .def_readwrite("d12", &mpc_socp__CPG_Dual_cpp_t::d12)
            .def_readwrite("d13", &mpc_socp__CPG_Dual_cpp_t::d13)
            .def_readwrite("d14", &mpc_socp__CPG_Dual_cpp_t::d14)
            .def_readwrite("d15", &mpc_socp__CPG_Dual_cpp_t::d15)
            .def_readwrite("d16", &mpc_socp__CPG_Dual_cpp_t::d16)
            .def_readwrite("d17", &mpc_socp__CPG_Dual_cpp_t::d17)
            .def_readwrite("d18", &mpc_socp__CPG_Dual_cpp_t::d18)
            .def_readwrite("d19", &mpc_socp__CPG_Dual_cpp_t::d19)
            .def_readwrite("d20", &mpc_socp__CPG_Dual_cpp_t::d20)
            .def_readwrite("d21", &mpc_socp__CPG_Dual_cpp_t::d21)
            .def_readwrite("d22", &mpc_socp__CPG_Dual_cpp_t::d22)
            .def_readwrite("d23", &mpc_socp__CPG_Dual_cpp_t::d23)
            .def_readwrite("d24", &mpc_socp__CPG_Dual_cpp_t::d24)
            .def_readwrite("d25", &mpc_socp__CPG_Dual_cpp_t::d25)
            .def_readwrite("d26", &mpc_socp__CPG_Dual_cpp_t::d26)
            .def_readwrite("d27", &mpc_socp__CPG_Dual_cpp_t::d27)
            .def_readwrite("d28", &mpc_socp__CPG_Dual_cpp_t::d28)
            .def_readwrite("d29", &mpc_socp__CPG_Dual_cpp_t::d29)
            .def_readwrite("d30", &mpc_socp__CPG_Dual_cpp_t::d30)
            .def_readwrite("d31", &mpc_socp__CPG_Dual_cpp_t::d31)
            .def_readwrite("d32", &mpc_socp__CPG_Dual_cpp_t::d32)
            .def_readwrite("d33", &mpc_socp__CPG_Dual_cpp_t::d33)
            .def_readwrite("d34", &mpc_socp__CPG_Dual_cpp_t::d34)
            .def_readwrite("d35", &mpc_socp__CPG_Dual_cpp_t::d35)
            .def_readwrite("d36", &mpc_socp__CPG_Dual_cpp_t::d36)
            .def_readwrite("d37", &mpc_socp__CPG_Dual_cpp_t::d37)
            .def_readwrite("d38", &mpc_socp__CPG_Dual_cpp_t::d38)
            .def_readwrite("d39", &mpc_socp__CPG_Dual_cpp_t::d39)
            .def_readwrite("d40", &mpc_socp__CPG_Dual_cpp_t::d40)
            .def_readwrite("d41", &mpc_socp__CPG_Dual_cpp_t::d41)
            .def_readwrite("d42", &mpc_socp__CPG_Dual_cpp_t::d42)
            .def_readwrite("d43", &mpc_socp__CPG_Dual_cpp_t::d43)
            .def_readwrite("d44", &mpc_socp__CPG_Dual_cpp_t::d44)
            .def_readwrite("d45", &mpc_socp__CPG_Dual_cpp_t::d45)
            .def_readwrite("d46", &mpc_socp__CPG_Dual_cpp_t::d46)
            .def_readwrite("d47", &mpc_socp__CPG_Dual_cpp_t::d47)
            .def_readwrite("d48", &mpc_socp__CPG_Dual_cpp_t::d48)
            .def_readwrite("d49", &mpc_socp__CPG_Dual_cpp_t::d49)
            .def_readwrite("d50", &mpc_socp__CPG_Dual_cpp_t::d50)
            .def_readwrite("d51", &mpc_socp__CPG_Dual_cpp_t::d51)
            .def_readwrite("d52", &mpc_socp__CPG_Dual_cpp_t::d52)
            .def_readwrite("d53", &mpc_socp__CPG_Dual_cpp_t::d53)
            .def_readwrite("d54", &mpc_socp__CPG_Dual_cpp_t::d54)
            .def_readwrite("d55", &mpc_socp__CPG_Dual_cpp_t::d55)
            .def_readwrite("d56", &mpc_socp__CPG_Dual_cpp_t::d56)
            .def_readwrite("d57", &mpc_socp__CPG_Dual_cpp_t::d57)
            .def_readwrite("d58", &mpc_socp__CPG_Dual_cpp_t::d58)
            .def_readwrite("d59", &mpc_socp__CPG_Dual_cpp_t::d59)
            .def_readwrite("d60", &mpc_socp__CPG_Dual_cpp_t::d60)
            .def_readwrite("d61", &mpc_socp__CPG_Dual_cpp_t::d61)
            .def_readwrite("d62", &mpc_socp__CPG_Dual_cpp_t::d62)
            .def_readwrite("d63", &mpc_socp__CPG_Dual_cpp_t::d63)
            .def_readwrite("d64", &mpc_socp__CPG_Dual_cpp_t::d64)
            .def_readwrite("d65", &mpc_socp__CPG_Dual_cpp_t::d65)
            .def_readwrite("d66", &mpc_socp__CPG_Dual_cpp_t::d66)
            .def_readwrite("d67", &mpc_socp__CPG_Dual_cpp_t::d67)
            .def_readwrite("d68", &mpc_socp__CPG_Dual_cpp_t::d68)
            .def_readwrite("d69", &mpc_socp__CPG_Dual_cpp_t::d69)
            .def_readwrite("d70", &mpc_socp__CPG_Dual_cpp_t::d70)
            .def_readwrite("d71", &mpc_socp__CPG_Dual_cpp_t::d71)
            .def_readwrite("d72", &mpc_socp__CPG_Dual_cpp_t::d72)
            .def_readwrite("d73", &mpc_socp__CPG_Dual_cpp_t::d73)
            .def_readwrite("d74", &mpc_socp__CPG_Dual_cpp_t::d74)
            .def_readwrite("d75", &mpc_socp__CPG_Dual_cpp_t::d75)
            .def_readwrite("d76", &mpc_socp__CPG_Dual_cpp_t::d76)
            .def_readwrite("d77", &mpc_socp__CPG_Dual_cpp_t::d77)
            .def_readwrite("d78", &mpc_socp__CPG_Dual_cpp_t::d78)
            .def_readwrite("d79", &mpc_socp__CPG_Dual_cpp_t::d79)
            .def_readwrite("d80", &mpc_socp__CPG_Dual_cpp_t::d80)
            .def_readwrite("d81", &mpc_socp__CPG_Dual_cpp_t::d81)
            .def_readwrite("d82", &mpc_socp__CPG_Dual_cpp_t::d82)
            .def_readwrite("d83", &mpc_socp__CPG_Dual_cpp_t::d83)
            .def_readwrite("d84", &mpc_socp__CPG_Dual_cpp_t::d84)
            .def_readwrite("d85", &mpc_socp__CPG_Dual_cpp_t::d85)
            .def_readwrite("d86", &mpc_socp__CPG_Dual_cpp_t::d86)
            .def_readwrite("d87", &mpc_socp__CPG_Dual_cpp_t::d87)
            .def_readwrite("d88", &mpc_socp__CPG_Dual_cpp_t::d88)
            .def_readwrite("d89", &mpc_socp__CPG_Dual_cpp_t::d89)
            .def_readwrite("d90", &mpc_socp__CPG_Dual_cpp_t::d90)
            .def_readwrite("d91", &mpc_socp__CPG_Dual_cpp_t::d91)
            .def_readwrite("d92", &mpc_socp__CPG_Dual_cpp_t::d92)
            .def_readwrite("d93", &mpc_socp__CPG_Dual_cpp_t::d93)
            .def_readwrite("d94", &mpc_socp__CPG_Dual_cpp_t::d94)
            .def_readwrite("d95", &mpc_socp__CPG_Dual_cpp_t::d95)
            .def_readwrite("d96", &mpc_socp__CPG_Dual_cpp_t::d96)
            .def_readwrite("d97", &mpc_socp__CPG_Dual_cpp_t::d97)
            .def_readwrite("d98", &mpc_socp__CPG_Dual_cpp_t::d98)
            .def_readwrite("d99", &mpc_socp__CPG_Dual_cpp_t::d99)
            .def_readwrite("d100", &mpc_socp__CPG_Dual_cpp_t::d100)
            .def_readwrite("d101", &mpc_socp__CPG_Dual_cpp_t::d101)
            .def_readwrite("d102", &mpc_socp__CPG_Dual_cpp_t::d102)
            .def_readwrite("d103", &mpc_socp__CPG_Dual_cpp_t::d103)
            .def_readwrite("d104", &mpc_socp__CPG_Dual_cpp_t::d104)
            .def_readwrite("d105", &mpc_socp__CPG_Dual_cpp_t::d105)
            .def_readwrite("d106", &mpc_socp__CPG_Dual_cpp_t::d106)
            .def_readwrite("d107", &mpc_socp__CPG_Dual_cpp_t::d107)
            .def_readwrite("d108", &mpc_socp__CPG_Dual_cpp_t::d108)
            .def_readwrite("d109", &mpc_socp__CPG_Dual_cpp_t::d109)
            .def_readwrite("d110", &mpc_socp__CPG_Dual_cpp_t::d110)
            .def_readwrite("d111", &mpc_socp__CPG_Dual_cpp_t::d111)
            .def_readwrite("d112", &mpc_socp__CPG_Dual_cpp_t::d112)
            .def_readwrite("d113", &mpc_socp__CPG_Dual_cpp_t::d113)
            .def_readwrite("d114", &mpc_socp__CPG_Dual_cpp_t::d114)
            .def_readwrite("d115", &mpc_socp__CPG_Dual_cpp_t::d115)
            .def_readwrite("d116", &mpc_socp__CPG_Dual_cpp_t::d116)
            .def_readwrite("d117", &mpc_socp__CPG_Dual_cpp_t::d117)
            .def_readwrite("d118", &mpc_socp__CPG_Dual_cpp_t::d118)
            .def_readwrite("d119", &mpc_socp__CPG_Dual_cpp_t::d119)
            .def_readwrite("d120", &mpc_socp__CPG_Dual_cpp_t::d120)
            .def_readwrite("d121", &mpc_socp__CPG_Dual_cpp_t::d121)
            .def_readwrite("d122", &mpc_socp__CPG_Dual_cpp_t::d122)
            .def_readwrite("d123", &mpc_socp__CPG_Dual_cpp_t::d123)
            .def_readwrite("d124", &mpc_socp__CPG_Dual_cpp_t::d124)
            .def_readwrite("d125", &mpc_socp__CPG_Dual_cpp_t::d125)
            .def_readwrite("d126", &mpc_socp__CPG_Dual_cpp_t::d126)
            .def_readwrite("d127", &mpc_socp__CPG_Dual_cpp_t::d127)
            .def_readwrite("d128", &mpc_socp__CPG_Dual_cpp_t::d128)
            .def_readwrite("d129", &mpc_socp__CPG_Dual_cpp_t::d129)
            .def_readwrite("d130", &mpc_socp__CPG_Dual_cpp_t::d130)
            .def_readwrite("d131", &mpc_socp__CPG_Dual_cpp_t::d131)
            .def_readwrite("d132", &mpc_socp__CPG_Dual_cpp_t::d132)
            .def_readwrite("d133", &mpc_socp__CPG_Dual_cpp_t::d133)
            .def_readwrite("d134", &mpc_socp__CPG_Dual_cpp_t::d134)
            .def_readwrite("d135", &mpc_socp__CPG_Dual_cpp_t::d135)
            .def_readwrite("d136", &mpc_socp__CPG_Dual_cpp_t::d136)
            ;

    py::class_<mpc_socp__CPG_Info_cpp_t>(m, "mpc_socp__cpg_info")
            .def(py::init<>())
            .def_readwrite("obj_val", &mpc_socp__CPG_Info_cpp_t::obj_val)
            .def_readwrite("iter", &mpc_socp__CPG_Info_cpp_t::iter)
            .def_readwrite("status", &mpc_socp__CPG_Info_cpp_t::status)
            .def_readwrite("pri_res", &mpc_socp__CPG_Info_cpp_t::pri_res)
            .def_readwrite("dua_res", &mpc_socp__CPG_Info_cpp_t::dua_res)
            .def_readwrite("time", &mpc_socp__CPG_Info_cpp_t::time)
            ;

    py::class_<mpc_socp__CPG_Result_cpp_t>(m, "mpc_socp__cpg_result")
            .def(py::init<>())
            .def_readwrite("cpg_prim", &mpc_socp__CPG_Result_cpp_t::prim)
            .def_readwrite("cpg_dual", &mpc_socp__CPG_Result_cpp_t::dual)
            .def_readwrite("cpg_info", &mpc_socp__CPG_Result_cpp_t::info)
            ;

    m.def("solve", &mpc_socp__solve_cpp);

    m.def("set_solver_default_settings", &mpc_socp__cpg_set_solver_default_settings);
    m.def("set_solver_max_iters", &mpc_socp__cpg_set_solver_max_iters);
    m.def("set_solver_bisect_iters", &mpc_socp__cpg_set_solver_bisect_iters);
    m.def("set_solver_ruiz_iters", &mpc_socp__cpg_set_solver_ruiz_iters);
    m.def("set_solver_iter_ref_iters", &mpc_socp__cpg_set_solver_iter_ref_iters);
    m.def("set_solver_kkt_static_reg", &mpc_socp__cpg_set_solver_kkt_static_reg);
    m.def("set_solver_kkt_dynamic_reg", &mpc_socp__cpg_set_solver_kkt_dynamic_reg);
    m.def("set_solver_abstol", &mpc_socp__cpg_set_solver_abstol);
    m.def("set_solver_reltol", &mpc_socp__cpg_set_solver_reltol);
    m.def("set_solver_abstol_inacc", &mpc_socp__cpg_set_solver_abstol_inacc);
    m.def("set_solver_reltol_inacc", &mpc_socp__cpg_set_solver_reltol_inacc);
    m.def("set_solver_verbose", &mpc_socp__cpg_set_solver_verbose);

}
