
/*
Auto-generated by CVXPYgen on May 25, 2025 at 08:58:49.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct mpc_socp__CPG_Params_cpp_t {
    std::array<double, 476> param3972;
    std::array<double, 14> param3966;
    std::array<double, 490> param3967;
    std::array<double, 6664> param3969;
    std::array<double, 1428> param3970;
    std::array<double, 476> param3971;
    std::array<double, 102> param3968;
};

// Flags for updated user-defined parameters
struct mpc_socp__CPG_Updated_cpp_t {
    bool param3972;
    bool param3966;
    bool param3967;
    bool param3969;
    bool param3970;
    bool param3971;
    bool param3968;
};

// Primal solution
struct mpc_socp__CPG_Prim_cpp_t {
    std::array<double, 490> var3963;
    std::array<double, 102> var3964;
    std::array<double, 34> var3965;
};

// Dual solution
struct mpc_socp__CPG_Dual_cpp_t {
    std::array<double, 14> d0;
    std::array<double, 14> d1;
    double d2;
    double d3;
    double d4;
    double d5;
    std::array<double, 14> d6;
    double d7;
    double d8;
    double d9;
    double d10;
    std::array<double, 14> d11;
    double d12;
    double d13;
    double d14;
    double d15;
    std::array<double, 14> d16;
    double d17;
    double d18;
    double d19;
    double d20;
    std::array<double, 14> d21;
    double d22;
    double d23;
    double d24;
    double d25;
    std::array<double, 14> d26;
    double d27;
    double d28;
    double d29;
    double d30;
    std::array<double, 14> d31;
    double d32;
    double d33;
    double d34;
    double d35;
    std::array<double, 14> d36;
    double d37;
    double d38;
    double d39;
    double d40;
    std::array<double, 14> d41;
    double d42;
    double d43;
    double d44;
    double d45;
    std::array<double, 14> d46;
    double d47;
    double d48;
    double d49;
    double d50;
    std::array<double, 14> d51;
    double d52;
    double d53;
    double d54;
    double d55;
    std::array<double, 14> d56;
    double d57;
    double d58;
    double d59;
    double d60;
    std::array<double, 14> d61;
    double d62;
    double d63;
    double d64;
    double d65;
    std::array<double, 14> d66;
    double d67;
    double d68;
    double d69;
    double d70;
    std::array<double, 14> d71;
    double d72;
    double d73;
    double d74;
    double d75;
    std::array<double, 14> d76;
    double d77;
    double d78;
    double d79;
    double d80;
    std::array<double, 14> d81;
    double d82;
    double d83;
    double d84;
    double d85;
    std::array<double, 14> d86;
    double d87;
    double d88;
    double d89;
    double d90;
    std::array<double, 14> d91;
    double d92;
    double d93;
    double d94;
    double d95;
    std::array<double, 14> d96;
    double d97;
    double d98;
    double d99;
    double d100;
    std::array<double, 14> d101;
    double d102;
    double d103;
    double d104;
    double d105;
    std::array<double, 14> d106;
    double d107;
    double d108;
    double d109;
    double d110;
    std::array<double, 14> d111;
    double d112;
    double d113;
    double d114;
    double d115;
    std::array<double, 14> d116;
    double d117;
    double d118;
    double d119;
    double d120;
    std::array<double, 14> d121;
    double d122;
    double d123;
    double d124;
    double d125;
    std::array<double, 14> d126;
    double d127;
    double d128;
    double d129;
    double d130;
    std::array<double, 14> d131;
    double d132;
    double d133;
    double d134;
    double d135;
    std::array<double, 14> d136;
    double d137;
    double d138;
    double d139;
    double d140;
    std::array<double, 14> d141;
    double d142;
    double d143;
    double d144;
    double d145;
    std::array<double, 14> d146;
    double d147;
    double d148;
    double d149;
    double d150;
    std::array<double, 14> d151;
    double d152;
    double d153;
    double d154;
    double d155;
    std::array<double, 14> d156;
    double d157;
    double d158;
    double d159;
    double d160;
    std::array<double, 14> d161;
    double d162;
    double d163;
    double d164;
    double d165;
    std::array<double, 14> d166;
    double d167;
    double d168;
    double d169;
    double d170;
};

// Solver information
struct mpc_socp__CPG_Info_cpp_t {
    double obj_val;
    int iter;
    int status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct mpc_socp__CPG_Result_cpp_t {
    mpc_socp__CPG_Prim_cpp_t prim;
    mpc_socp__CPG_Dual_cpp_t dual;
    mpc_socp__CPG_Info_cpp_t info;
};

// Main solve function
mpc_socp__CPG_Result_cpp_t mpc_socp__solve_cpp(struct mpc_socp__CPG_Updated_cpp_t& CPG_Updated_cpp, struct mpc_socp__CPG_Params_cpp_t& CPG_Params_cpp);
