
/*
Auto-generated by CVXPYgen on May 26, 2025 at 22:53:23.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  mpc_socp__cpg_update_param3972(0, 0.13584763283005923951);
  mpc_socp__cpg_update_param3965(0, -0.04669161672104239075);
  mpc_socp__cpg_update_param3966(0, 0.24783491287596051689);
  mpc_socp__cpg_update_param3969(0, 1.16870903787914093286);
  mpc_socp__cpg_update_param3970(0, 0.48135382352125793970);
  mpc_socp__cpg_update_param3967(0, -0.31958577868295146018);
  mpc_socp__cpg_update_param3968(0, 0.19105730687040864413);

  // Solve the problem instance
  mpc_socp__cpg_solve();

  // Print objective function value
  printf("obj = %f\n", mpc_socp__CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<490; i++) {
    printf("var3963[%d] = %f\n", i, mpc_socp__CPG_Result.prim->var3963[i]);
  }
  for(i=0; i<102; i++) {
    printf("var3964[%d] = %f\n", i, mpc_socp__CPG_Result.prim->var3964[i]);
  }

  // Print dual solution
  for(i=0; i<14; i++) {
    printf("d0[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d0[i]);
  }
  for(i=0; i<14; i++) {
    printf("d1[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d1[i]);
  }
  printf("d2 = %f\n", mpc_socp__CPG_Result.dual->d2);
  printf("d3 = %f\n", mpc_socp__CPG_Result.dual->d3);
  printf("d4 = %f\n", mpc_socp__CPG_Result.dual->d4);
  for(i=0; i<14; i++) {
    printf("d5[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d5[i]);
  }
  printf("d6 = %f\n", mpc_socp__CPG_Result.dual->d6);
  printf("d7 = %f\n", mpc_socp__CPG_Result.dual->d7);
  printf("d8 = %f\n", mpc_socp__CPG_Result.dual->d8);
  for(i=0; i<14; i++) {
    printf("d9[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d9[i]);
  }
  printf("d10 = %f\n", mpc_socp__CPG_Result.dual->d10);
  printf("d11 = %f\n", mpc_socp__CPG_Result.dual->d11);
  printf("d12 = %f\n", mpc_socp__CPG_Result.dual->d12);
  for(i=0; i<14; i++) {
    printf("d13[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d13[i]);
  }
  printf("d14 = %f\n", mpc_socp__CPG_Result.dual->d14);
  printf("d15 = %f\n", mpc_socp__CPG_Result.dual->d15);
  printf("d16 = %f\n", mpc_socp__CPG_Result.dual->d16);
  for(i=0; i<14; i++) {
    printf("d17[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d17[i]);
  }
  printf("d18 = %f\n", mpc_socp__CPG_Result.dual->d18);
  printf("d19 = %f\n", mpc_socp__CPG_Result.dual->d19);
  printf("d20 = %f\n", mpc_socp__CPG_Result.dual->d20);
  for(i=0; i<14; i++) {
    printf("d21[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d21[i]);
  }
  printf("d22 = %f\n", mpc_socp__CPG_Result.dual->d22);
  printf("d23 = %f\n", mpc_socp__CPG_Result.dual->d23);
  printf("d24 = %f\n", mpc_socp__CPG_Result.dual->d24);
  for(i=0; i<14; i++) {
    printf("d25[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d25[i]);
  }
  printf("d26 = %f\n", mpc_socp__CPG_Result.dual->d26);
  printf("d27 = %f\n", mpc_socp__CPG_Result.dual->d27);
  printf("d28 = %f\n", mpc_socp__CPG_Result.dual->d28);
  for(i=0; i<14; i++) {
    printf("d29[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d29[i]);
  }
  printf("d30 = %f\n", mpc_socp__CPG_Result.dual->d30);
  printf("d31 = %f\n", mpc_socp__CPG_Result.dual->d31);
  printf("d32 = %f\n", mpc_socp__CPG_Result.dual->d32);
  for(i=0; i<14; i++) {
    printf("d33[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d33[i]);
  }
  printf("d34 = %f\n", mpc_socp__CPG_Result.dual->d34);
  printf("d35 = %f\n", mpc_socp__CPG_Result.dual->d35);
  printf("d36 = %f\n", mpc_socp__CPG_Result.dual->d36);
  for(i=0; i<14; i++) {
    printf("d37[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d37[i]);
  }
  printf("d38 = %f\n", mpc_socp__CPG_Result.dual->d38);
  printf("d39 = %f\n", mpc_socp__CPG_Result.dual->d39);
  printf("d40 = %f\n", mpc_socp__CPG_Result.dual->d40);
  for(i=0; i<14; i++) {
    printf("d41[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d41[i]);
  }
  printf("d42 = %f\n", mpc_socp__CPG_Result.dual->d42);
  printf("d43 = %f\n", mpc_socp__CPG_Result.dual->d43);
  printf("d44 = %f\n", mpc_socp__CPG_Result.dual->d44);
  for(i=0; i<14; i++) {
    printf("d45[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d45[i]);
  }
  printf("d46 = %f\n", mpc_socp__CPG_Result.dual->d46);
  printf("d47 = %f\n", mpc_socp__CPG_Result.dual->d47);
  printf("d48 = %f\n", mpc_socp__CPG_Result.dual->d48);
  for(i=0; i<14; i++) {
    printf("d49[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d49[i]);
  }
  printf("d50 = %f\n", mpc_socp__CPG_Result.dual->d50);
  printf("d51 = %f\n", mpc_socp__CPG_Result.dual->d51);
  printf("d52 = %f\n", mpc_socp__CPG_Result.dual->d52);
  for(i=0; i<14; i++) {
    printf("d53[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d53[i]);
  }
  printf("d54 = %f\n", mpc_socp__CPG_Result.dual->d54);
  printf("d55 = %f\n", mpc_socp__CPG_Result.dual->d55);
  printf("d56 = %f\n", mpc_socp__CPG_Result.dual->d56);
  for(i=0; i<14; i++) {
    printf("d57[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d57[i]);
  }
  printf("d58 = %f\n", mpc_socp__CPG_Result.dual->d58);
  printf("d59 = %f\n", mpc_socp__CPG_Result.dual->d59);
  printf("d60 = %f\n", mpc_socp__CPG_Result.dual->d60);
  for(i=0; i<14; i++) {
    printf("d61[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d61[i]);
  }
  printf("d62 = %f\n", mpc_socp__CPG_Result.dual->d62);
  printf("d63 = %f\n", mpc_socp__CPG_Result.dual->d63);
  printf("d64 = %f\n", mpc_socp__CPG_Result.dual->d64);
  for(i=0; i<14; i++) {
    printf("d65[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d65[i]);
  }
  printf("d66 = %f\n", mpc_socp__CPG_Result.dual->d66);
  printf("d67 = %f\n", mpc_socp__CPG_Result.dual->d67);
  printf("d68 = %f\n", mpc_socp__CPG_Result.dual->d68);
  for(i=0; i<14; i++) {
    printf("d69[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d69[i]);
  }
  printf("d70 = %f\n", mpc_socp__CPG_Result.dual->d70);
  printf("d71 = %f\n", mpc_socp__CPG_Result.dual->d71);
  printf("d72 = %f\n", mpc_socp__CPG_Result.dual->d72);
  for(i=0; i<14; i++) {
    printf("d73[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d73[i]);
  }
  printf("d74 = %f\n", mpc_socp__CPG_Result.dual->d74);
  printf("d75 = %f\n", mpc_socp__CPG_Result.dual->d75);
  printf("d76 = %f\n", mpc_socp__CPG_Result.dual->d76);
  for(i=0; i<14; i++) {
    printf("d77[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d77[i]);
  }
  printf("d78 = %f\n", mpc_socp__CPG_Result.dual->d78);
  printf("d79 = %f\n", mpc_socp__CPG_Result.dual->d79);
  printf("d80 = %f\n", mpc_socp__CPG_Result.dual->d80);
  for(i=0; i<14; i++) {
    printf("d81[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d81[i]);
  }
  printf("d82 = %f\n", mpc_socp__CPG_Result.dual->d82);
  printf("d83 = %f\n", mpc_socp__CPG_Result.dual->d83);
  printf("d84 = %f\n", mpc_socp__CPG_Result.dual->d84);
  for(i=0; i<14; i++) {
    printf("d85[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d85[i]);
  }
  printf("d86 = %f\n", mpc_socp__CPG_Result.dual->d86);
  printf("d87 = %f\n", mpc_socp__CPG_Result.dual->d87);
  printf("d88 = %f\n", mpc_socp__CPG_Result.dual->d88);
  for(i=0; i<14; i++) {
    printf("d89[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d89[i]);
  }
  printf("d90 = %f\n", mpc_socp__CPG_Result.dual->d90);
  printf("d91 = %f\n", mpc_socp__CPG_Result.dual->d91);
  printf("d92 = %f\n", mpc_socp__CPG_Result.dual->d92);
  for(i=0; i<14; i++) {
    printf("d93[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d93[i]);
  }
  printf("d94 = %f\n", mpc_socp__CPG_Result.dual->d94);
  printf("d95 = %f\n", mpc_socp__CPG_Result.dual->d95);
  printf("d96 = %f\n", mpc_socp__CPG_Result.dual->d96);
  for(i=0; i<14; i++) {
    printf("d97[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d97[i]);
  }
  printf("d98 = %f\n", mpc_socp__CPG_Result.dual->d98);
  printf("d99 = %f\n", mpc_socp__CPG_Result.dual->d99);
  printf("d100 = %f\n", mpc_socp__CPG_Result.dual->d100);
  for(i=0; i<14; i++) {
    printf("d101[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d101[i]);
  }
  printf("d102 = %f\n", mpc_socp__CPG_Result.dual->d102);
  printf("d103 = %f\n", mpc_socp__CPG_Result.dual->d103);
  printf("d104 = %f\n", mpc_socp__CPG_Result.dual->d104);
  for(i=0; i<14; i++) {
    printf("d105[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d105[i]);
  }
  printf("d106 = %f\n", mpc_socp__CPG_Result.dual->d106);
  printf("d107 = %f\n", mpc_socp__CPG_Result.dual->d107);
  printf("d108 = %f\n", mpc_socp__CPG_Result.dual->d108);
  for(i=0; i<14; i++) {
    printf("d109[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d109[i]);
  }
  printf("d110 = %f\n", mpc_socp__CPG_Result.dual->d110);
  printf("d111 = %f\n", mpc_socp__CPG_Result.dual->d111);
  printf("d112 = %f\n", mpc_socp__CPG_Result.dual->d112);
  for(i=0; i<14; i++) {
    printf("d113[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d113[i]);
  }
  printf("d114 = %f\n", mpc_socp__CPG_Result.dual->d114);
  printf("d115 = %f\n", mpc_socp__CPG_Result.dual->d115);
  printf("d116 = %f\n", mpc_socp__CPG_Result.dual->d116);
  for(i=0; i<14; i++) {
    printf("d117[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d117[i]);
  }
  printf("d118 = %f\n", mpc_socp__CPG_Result.dual->d118);
  printf("d119 = %f\n", mpc_socp__CPG_Result.dual->d119);
  printf("d120 = %f\n", mpc_socp__CPG_Result.dual->d120);
  for(i=0; i<14; i++) {
    printf("d121[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d121[i]);
  }
  printf("d122 = %f\n", mpc_socp__CPG_Result.dual->d122);
  printf("d123 = %f\n", mpc_socp__CPG_Result.dual->d123);
  printf("d124 = %f\n", mpc_socp__CPG_Result.dual->d124);
  for(i=0; i<14; i++) {
    printf("d125[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d125[i]);
  }
  printf("d126 = %f\n", mpc_socp__CPG_Result.dual->d126);
  printf("d127 = %f\n", mpc_socp__CPG_Result.dual->d127);
  printf("d128 = %f\n", mpc_socp__CPG_Result.dual->d128);
  for(i=0; i<14; i++) {
    printf("d129[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d129[i]);
  }
  printf("d130 = %f\n", mpc_socp__CPG_Result.dual->d130);
  printf("d131 = %f\n", mpc_socp__CPG_Result.dual->d131);
  printf("d132 = %f\n", mpc_socp__CPG_Result.dual->d132);
  for(i=0; i<14; i++) {
    printf("d133[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d133[i]);
  }
  printf("d134 = %f\n", mpc_socp__CPG_Result.dual->d134);
  printf("d135 = %f\n", mpc_socp__CPG_Result.dual->d135);
  printf("d136 = %f\n", mpc_socp__CPG_Result.dual->d136);

  return 0;

}
