
/*
Auto-generated by CVXPYgen on May 25, 2025 at 08:58:49.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  mpc_socp__cpg_update_param3972(0, 0.00000000000000000000);
  mpc_socp__cpg_update_param3966(0, -0.13649772366075280106);
  mpc_socp__cpg_update_param3967(0, 0.87569481612434219020);
  mpc_socp__cpg_update_param3969(0, 1.74859446882723923444);
  mpc_socp__cpg_update_param3970(0, -1.06418848156509171510);
  mpc_socp__cpg_update_param3971(0, -1.08549758319276734575);
  mpc_socp__cpg_update_param3968(0, -0.28111950160410936750);

  // Solve the problem instance
  mpc_socp__cpg_solve();

  // Print objective function value
  printf("obj = %f\n", mpc_socp__CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<490; i++) {
    printf("var3963[%d] = %f\n", i, mpc_socp__CPG_Result.prim->var3963[i]);
  }
  for(i=0; i<102; i++) {
    printf("var3964[%d] = %f\n", i, mpc_socp__CPG_Result.prim->var3964[i]);
  }
  for(i=0; i<34; i++) {
    printf("var3965[%d] = %f\n", i, mpc_socp__CPG_Result.prim->var3965[i]);
  }

  // Print dual solution
  for(i=0; i<14; i++) {
    printf("d0[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d0[i]);
  }
  for(i=0; i<14; i++) {
    printf("d1[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d1[i]);
  }
  printf("d2 = %f\n", mpc_socp__CPG_Result.dual->d2);
  printf("d3 = %f\n", mpc_socp__CPG_Result.dual->d3);
  printf("d4 = %f\n", mpc_socp__CPG_Result.dual->d4);
  printf("d5 = %f\n", mpc_socp__CPG_Result.dual->d5);
  for(i=0; i<14; i++) {
    printf("d6[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d6[i]);
  }
  printf("d7 = %f\n", mpc_socp__CPG_Result.dual->d7);
  printf("d8 = %f\n", mpc_socp__CPG_Result.dual->d8);
  printf("d9 = %f\n", mpc_socp__CPG_Result.dual->d9);
  printf("d10 = %f\n", mpc_socp__CPG_Result.dual->d10);
  for(i=0; i<14; i++) {
    printf("d11[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d11[i]);
  }
  printf("d12 = %f\n", mpc_socp__CPG_Result.dual->d12);
  printf("d13 = %f\n", mpc_socp__CPG_Result.dual->d13);
  printf("d14 = %f\n", mpc_socp__CPG_Result.dual->d14);
  printf("d15 = %f\n", mpc_socp__CPG_Result.dual->d15);
  for(i=0; i<14; i++) {
    printf("d16[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d16[i]);
  }
  printf("d17 = %f\n", mpc_socp__CPG_Result.dual->d17);
  printf("d18 = %f\n", mpc_socp__CPG_Result.dual->d18);
  printf("d19 = %f\n", mpc_socp__CPG_Result.dual->d19);
  printf("d20 = %f\n", mpc_socp__CPG_Result.dual->d20);
  for(i=0; i<14; i++) {
    printf("d21[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d21[i]);
  }
  printf("d22 = %f\n", mpc_socp__CPG_Result.dual->d22);
  printf("d23 = %f\n", mpc_socp__CPG_Result.dual->d23);
  printf("d24 = %f\n", mpc_socp__CPG_Result.dual->d24);
  printf("d25 = %f\n", mpc_socp__CPG_Result.dual->d25);
  for(i=0; i<14; i++) {
    printf("d26[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d26[i]);
  }
  printf("d27 = %f\n", mpc_socp__CPG_Result.dual->d27);
  printf("d28 = %f\n", mpc_socp__CPG_Result.dual->d28);
  printf("d29 = %f\n", mpc_socp__CPG_Result.dual->d29);
  printf("d30 = %f\n", mpc_socp__CPG_Result.dual->d30);
  for(i=0; i<14; i++) {
    printf("d31[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d31[i]);
  }
  printf("d32 = %f\n", mpc_socp__CPG_Result.dual->d32);
  printf("d33 = %f\n", mpc_socp__CPG_Result.dual->d33);
  printf("d34 = %f\n", mpc_socp__CPG_Result.dual->d34);
  printf("d35 = %f\n", mpc_socp__CPG_Result.dual->d35);
  for(i=0; i<14; i++) {
    printf("d36[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d36[i]);
  }
  printf("d37 = %f\n", mpc_socp__CPG_Result.dual->d37);
  printf("d38 = %f\n", mpc_socp__CPG_Result.dual->d38);
  printf("d39 = %f\n", mpc_socp__CPG_Result.dual->d39);
  printf("d40 = %f\n", mpc_socp__CPG_Result.dual->d40);
  for(i=0; i<14; i++) {
    printf("d41[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d41[i]);
  }
  printf("d42 = %f\n", mpc_socp__CPG_Result.dual->d42);
  printf("d43 = %f\n", mpc_socp__CPG_Result.dual->d43);
  printf("d44 = %f\n", mpc_socp__CPG_Result.dual->d44);
  printf("d45 = %f\n", mpc_socp__CPG_Result.dual->d45);
  for(i=0; i<14; i++) {
    printf("d46[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d46[i]);
  }
  printf("d47 = %f\n", mpc_socp__CPG_Result.dual->d47);
  printf("d48 = %f\n", mpc_socp__CPG_Result.dual->d48);
  printf("d49 = %f\n", mpc_socp__CPG_Result.dual->d49);
  printf("d50 = %f\n", mpc_socp__CPG_Result.dual->d50);
  for(i=0; i<14; i++) {
    printf("d51[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d51[i]);
  }
  printf("d52 = %f\n", mpc_socp__CPG_Result.dual->d52);
  printf("d53 = %f\n", mpc_socp__CPG_Result.dual->d53);
  printf("d54 = %f\n", mpc_socp__CPG_Result.dual->d54);
  printf("d55 = %f\n", mpc_socp__CPG_Result.dual->d55);
  for(i=0; i<14; i++) {
    printf("d56[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d56[i]);
  }
  printf("d57 = %f\n", mpc_socp__CPG_Result.dual->d57);
  printf("d58 = %f\n", mpc_socp__CPG_Result.dual->d58);
  printf("d59 = %f\n", mpc_socp__CPG_Result.dual->d59);
  printf("d60 = %f\n", mpc_socp__CPG_Result.dual->d60);
  for(i=0; i<14; i++) {
    printf("d61[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d61[i]);
  }
  printf("d62 = %f\n", mpc_socp__CPG_Result.dual->d62);
  printf("d63 = %f\n", mpc_socp__CPG_Result.dual->d63);
  printf("d64 = %f\n", mpc_socp__CPG_Result.dual->d64);
  printf("d65 = %f\n", mpc_socp__CPG_Result.dual->d65);
  for(i=0; i<14; i++) {
    printf("d66[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d66[i]);
  }
  printf("d67 = %f\n", mpc_socp__CPG_Result.dual->d67);
  printf("d68 = %f\n", mpc_socp__CPG_Result.dual->d68);
  printf("d69 = %f\n", mpc_socp__CPG_Result.dual->d69);
  printf("d70 = %f\n", mpc_socp__CPG_Result.dual->d70);
  for(i=0; i<14; i++) {
    printf("d71[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d71[i]);
  }
  printf("d72 = %f\n", mpc_socp__CPG_Result.dual->d72);
  printf("d73 = %f\n", mpc_socp__CPG_Result.dual->d73);
  printf("d74 = %f\n", mpc_socp__CPG_Result.dual->d74);
  printf("d75 = %f\n", mpc_socp__CPG_Result.dual->d75);
  for(i=0; i<14; i++) {
    printf("d76[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d76[i]);
  }
  printf("d77 = %f\n", mpc_socp__CPG_Result.dual->d77);
  printf("d78 = %f\n", mpc_socp__CPG_Result.dual->d78);
  printf("d79 = %f\n", mpc_socp__CPG_Result.dual->d79);
  printf("d80 = %f\n", mpc_socp__CPG_Result.dual->d80);
  for(i=0; i<14; i++) {
    printf("d81[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d81[i]);
  }
  printf("d82 = %f\n", mpc_socp__CPG_Result.dual->d82);
  printf("d83 = %f\n", mpc_socp__CPG_Result.dual->d83);
  printf("d84 = %f\n", mpc_socp__CPG_Result.dual->d84);
  printf("d85 = %f\n", mpc_socp__CPG_Result.dual->d85);
  for(i=0; i<14; i++) {
    printf("d86[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d86[i]);
  }
  printf("d87 = %f\n", mpc_socp__CPG_Result.dual->d87);
  printf("d88 = %f\n", mpc_socp__CPG_Result.dual->d88);
  printf("d89 = %f\n", mpc_socp__CPG_Result.dual->d89);
  printf("d90 = %f\n", mpc_socp__CPG_Result.dual->d90);
  for(i=0; i<14; i++) {
    printf("d91[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d91[i]);
  }
  printf("d92 = %f\n", mpc_socp__CPG_Result.dual->d92);
  printf("d93 = %f\n", mpc_socp__CPG_Result.dual->d93);
  printf("d94 = %f\n", mpc_socp__CPG_Result.dual->d94);
  printf("d95 = %f\n", mpc_socp__CPG_Result.dual->d95);
  for(i=0; i<14; i++) {
    printf("d96[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d96[i]);
  }
  printf("d97 = %f\n", mpc_socp__CPG_Result.dual->d97);
  printf("d98 = %f\n", mpc_socp__CPG_Result.dual->d98);
  printf("d99 = %f\n", mpc_socp__CPG_Result.dual->d99);
  printf("d100 = %f\n", mpc_socp__CPG_Result.dual->d100);
  for(i=0; i<14; i++) {
    printf("d101[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d101[i]);
  }
  printf("d102 = %f\n", mpc_socp__CPG_Result.dual->d102);
  printf("d103 = %f\n", mpc_socp__CPG_Result.dual->d103);
  printf("d104 = %f\n", mpc_socp__CPG_Result.dual->d104);
  printf("d105 = %f\n", mpc_socp__CPG_Result.dual->d105);
  for(i=0; i<14; i++) {
    printf("d106[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d106[i]);
  }
  printf("d107 = %f\n", mpc_socp__CPG_Result.dual->d107);
  printf("d108 = %f\n", mpc_socp__CPG_Result.dual->d108);
  printf("d109 = %f\n", mpc_socp__CPG_Result.dual->d109);
  printf("d110 = %f\n", mpc_socp__CPG_Result.dual->d110);
  for(i=0; i<14; i++) {
    printf("d111[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d111[i]);
  }
  printf("d112 = %f\n", mpc_socp__CPG_Result.dual->d112);
  printf("d113 = %f\n", mpc_socp__CPG_Result.dual->d113);
  printf("d114 = %f\n", mpc_socp__CPG_Result.dual->d114);
  printf("d115 = %f\n", mpc_socp__CPG_Result.dual->d115);
  for(i=0; i<14; i++) {
    printf("d116[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d116[i]);
  }
  printf("d117 = %f\n", mpc_socp__CPG_Result.dual->d117);
  printf("d118 = %f\n", mpc_socp__CPG_Result.dual->d118);
  printf("d119 = %f\n", mpc_socp__CPG_Result.dual->d119);
  printf("d120 = %f\n", mpc_socp__CPG_Result.dual->d120);
  for(i=0; i<14; i++) {
    printf("d121[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d121[i]);
  }
  printf("d122 = %f\n", mpc_socp__CPG_Result.dual->d122);
  printf("d123 = %f\n", mpc_socp__CPG_Result.dual->d123);
  printf("d124 = %f\n", mpc_socp__CPG_Result.dual->d124);
  printf("d125 = %f\n", mpc_socp__CPG_Result.dual->d125);
  for(i=0; i<14; i++) {
    printf("d126[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d126[i]);
  }
  printf("d127 = %f\n", mpc_socp__CPG_Result.dual->d127);
  printf("d128 = %f\n", mpc_socp__CPG_Result.dual->d128);
  printf("d129 = %f\n", mpc_socp__CPG_Result.dual->d129);
  printf("d130 = %f\n", mpc_socp__CPG_Result.dual->d130);
  for(i=0; i<14; i++) {
    printf("d131[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d131[i]);
  }
  printf("d132 = %f\n", mpc_socp__CPG_Result.dual->d132);
  printf("d133 = %f\n", mpc_socp__CPG_Result.dual->d133);
  printf("d134 = %f\n", mpc_socp__CPG_Result.dual->d134);
  printf("d135 = %f\n", mpc_socp__CPG_Result.dual->d135);
  for(i=0; i<14; i++) {
    printf("d136[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d136[i]);
  }
  printf("d137 = %f\n", mpc_socp__CPG_Result.dual->d137);
  printf("d138 = %f\n", mpc_socp__CPG_Result.dual->d138);
  printf("d139 = %f\n", mpc_socp__CPG_Result.dual->d139);
  printf("d140 = %f\n", mpc_socp__CPG_Result.dual->d140);
  for(i=0; i<14; i++) {
    printf("d141[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d141[i]);
  }
  printf("d142 = %f\n", mpc_socp__CPG_Result.dual->d142);
  printf("d143 = %f\n", mpc_socp__CPG_Result.dual->d143);
  printf("d144 = %f\n", mpc_socp__CPG_Result.dual->d144);
  printf("d145 = %f\n", mpc_socp__CPG_Result.dual->d145);
  for(i=0; i<14; i++) {
    printf("d146[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d146[i]);
  }
  printf("d147 = %f\n", mpc_socp__CPG_Result.dual->d147);
  printf("d148 = %f\n", mpc_socp__CPG_Result.dual->d148);
  printf("d149 = %f\n", mpc_socp__CPG_Result.dual->d149);
  printf("d150 = %f\n", mpc_socp__CPG_Result.dual->d150);
  for(i=0; i<14; i++) {
    printf("d151[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d151[i]);
  }
  printf("d152 = %f\n", mpc_socp__CPG_Result.dual->d152);
  printf("d153 = %f\n", mpc_socp__CPG_Result.dual->d153);
  printf("d154 = %f\n", mpc_socp__CPG_Result.dual->d154);
  printf("d155 = %f\n", mpc_socp__CPG_Result.dual->d155);
  for(i=0; i<14; i++) {
    printf("d156[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d156[i]);
  }
  printf("d157 = %f\n", mpc_socp__CPG_Result.dual->d157);
  printf("d158 = %f\n", mpc_socp__CPG_Result.dual->d158);
  printf("d159 = %f\n", mpc_socp__CPG_Result.dual->d159);
  printf("d160 = %f\n", mpc_socp__CPG_Result.dual->d160);
  for(i=0; i<14; i++) {
    printf("d161[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d161[i]);
  }
  printf("d162 = %f\n", mpc_socp__CPG_Result.dual->d162);
  printf("d163 = %f\n", mpc_socp__CPG_Result.dual->d163);
  printf("d164 = %f\n", mpc_socp__CPG_Result.dual->d164);
  printf("d165 = %f\n", mpc_socp__CPG_Result.dual->d165);
  for(i=0; i<14; i++) {
    printf("d166[%d] = %f\n", i, mpc_socp__CPG_Result.dual->d166[i]);
  }
  printf("d167 = %f\n", mpc_socp__CPG_Result.dual->d167);
  printf("d168 = %f\n", mpc_socp__CPG_Result.dual->d168);
  printf("d169 = %f\n", mpc_socp__CPG_Result.dual->d169);
  printf("d170 = %f\n", mpc_socp__CPG_Result.dual->d170);

  return 0;

}
