
/*
Auto-generated by CVXPYgen on May 26, 2025 at 22:53:23.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void mpc_socp__cpg_update_param3972(cpg_int idx, cpg_float val){
  mpc_socp__cpg_params_vec[idx+0] = val;
  mpc_socp__Canon_Outdated.A = 1;
}

void mpc_socp__cpg_update_param3965(cpg_int idx, cpg_float val){
  mpc_socp__cpg_params_vec[idx+476] = val;
  mpc_socp__Canon_Outdated.b = 1;
}

void mpc_socp__cpg_update_param3966(cpg_int idx, cpg_float val){
  mpc_socp__cpg_params_vec[idx+490] = val;
  mpc_socp__Canon_Outdated.b = 1;
}

void mpc_socp__cpg_update_param3969(cpg_int idx, cpg_float val){
  mpc_socp__cpg_params_vec[idx+980] = val;
  mpc_socp__Canon_Outdated.A = 1;
}

void mpc_socp__cpg_update_param3970(cpg_int idx, cpg_float val){
  mpc_socp__cpg_params_vec[idx+7644] = val;
  mpc_socp__Canon_Outdated.A = 1;
}

void mpc_socp__cpg_update_param3967(cpg_int idx, cpg_float val){
  mpc_socp__cpg_params_vec[idx+9072] = val;
  mpc_socp__Canon_Outdated.G = 1;
  mpc_socp__Canon_Outdated.h = 1;
}

void mpc_socp__cpg_update_param3968(cpg_int idx, cpg_float val){
  mpc_socp__cpg_params_vec[idx+9174] = val;
  mpc_socp__Canon_Outdated.h = 1;
}

// Map user-defined to canonical parameters
void mpc_socp__cpg_canonicalize_A(){
  for(i=0; i<9738; i++){
    mpc_socp__Canon_Params.A->x[i] = 0;
    for(j=mpc_socp__canon_A_map.p[i]; j<mpc_socp__canon_A_map.p[i+1]; j++){
      mpc_socp__Canon_Params.A->x[i] += mpc_socp__canon_A_map.x[j]*mpc_socp__cpg_params_vec[mpc_socp__canon_A_map.i[j]];
    }
  }
}

void mpc_socp__cpg_canonicalize_b(){
  for(i=0; i<1068; i++){
    mpc_socp__Canon_Params.b[i] = 0;
    for(j=mpc_socp__canon_b_map.p[i]; j<mpc_socp__canon_b_map.p[i+1]; j++){
      mpc_socp__Canon_Params.b[i] += mpc_socp__canon_b_map.x[j]*mpc_socp__cpg_params_vec[mpc_socp__canon_b_map.i[j]];
    }
  }
}

void mpc_socp__cpg_canonicalize_G(){
  for(i=0; i<544; i++){
    mpc_socp__Canon_Params.G->x[i] = 0;
    for(j=mpc_socp__canon_G_map.p[i]; j<mpc_socp__canon_G_map.p[i+1]; j++){
      mpc_socp__Canon_Params.G->x[i] += mpc_socp__canon_G_map.x[j]*mpc_socp__cpg_params_vec[mpc_socp__canon_G_map.i[j]];
    }
  }
}

void mpc_socp__cpg_canonicalize_h(){
  for(i=0; i<510; i++){
    mpc_socp__Canon_Params.h[i] = 0;
    for(j=mpc_socp__canon_h_map.p[i]; j<mpc_socp__canon_h_map.p[i+1]; j++){
      mpc_socp__Canon_Params.h[i] += mpc_socp__canon_h_map.x[j]*mpc_socp__cpg_params_vec[mpc_socp__canon_h_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void mpc_socp__cpg_retrieve_prim(){
  mpc_socp__CPG_Prim.var3963[0] = mpc_socp__qoco_solver->sol->x[578];
  mpc_socp__CPG_Prim.var3963[1] = mpc_socp__qoco_solver->sol->x[579];
  mpc_socp__CPG_Prim.var3963[2] = mpc_socp__qoco_solver->sol->x[580];
  mpc_socp__CPG_Prim.var3963[3] = mpc_socp__qoco_solver->sol->x[581];
  mpc_socp__CPG_Prim.var3963[4] = mpc_socp__qoco_solver->sol->x[582];
  mpc_socp__CPG_Prim.var3963[5] = mpc_socp__qoco_solver->sol->x[583];
  mpc_socp__CPG_Prim.var3963[6] = mpc_socp__qoco_solver->sol->x[584];
  mpc_socp__CPG_Prim.var3963[7] = mpc_socp__qoco_solver->sol->x[585];
  mpc_socp__CPG_Prim.var3963[8] = mpc_socp__qoco_solver->sol->x[586];
  mpc_socp__CPG_Prim.var3963[9] = mpc_socp__qoco_solver->sol->x[587];
  mpc_socp__CPG_Prim.var3963[10] = mpc_socp__qoco_solver->sol->x[588];
  mpc_socp__CPG_Prim.var3963[11] = mpc_socp__qoco_solver->sol->x[589];
  mpc_socp__CPG_Prim.var3963[12] = mpc_socp__qoco_solver->sol->x[590];
  mpc_socp__CPG_Prim.var3963[13] = mpc_socp__qoco_solver->sol->x[591];
  mpc_socp__CPG_Prim.var3963[14] = mpc_socp__qoco_solver->sol->x[592];
  mpc_socp__CPG_Prim.var3963[15] = mpc_socp__qoco_solver->sol->x[593];
  mpc_socp__CPG_Prim.var3963[16] = mpc_socp__qoco_solver->sol->x[594];
  mpc_socp__CPG_Prim.var3963[17] = mpc_socp__qoco_solver->sol->x[595];
  mpc_socp__CPG_Prim.var3963[18] = mpc_socp__qoco_solver->sol->x[596];
  mpc_socp__CPG_Prim.var3963[19] = mpc_socp__qoco_solver->sol->x[597];
  mpc_socp__CPG_Prim.var3963[20] = mpc_socp__qoco_solver->sol->x[598];
  mpc_socp__CPG_Prim.var3963[21] = mpc_socp__qoco_solver->sol->x[599];
  mpc_socp__CPG_Prim.var3963[22] = mpc_socp__qoco_solver->sol->x[600];
  mpc_socp__CPG_Prim.var3963[23] = mpc_socp__qoco_solver->sol->x[601];
  mpc_socp__CPG_Prim.var3963[24] = mpc_socp__qoco_solver->sol->x[602];
  mpc_socp__CPG_Prim.var3963[25] = mpc_socp__qoco_solver->sol->x[603];
  mpc_socp__CPG_Prim.var3963[26] = mpc_socp__qoco_solver->sol->x[604];
  mpc_socp__CPG_Prim.var3963[27] = mpc_socp__qoco_solver->sol->x[605];
  mpc_socp__CPG_Prim.var3963[28] = mpc_socp__qoco_solver->sol->x[606];
  mpc_socp__CPG_Prim.var3963[29] = mpc_socp__qoco_solver->sol->x[607];
  mpc_socp__CPG_Prim.var3963[30] = mpc_socp__qoco_solver->sol->x[608];
  mpc_socp__CPG_Prim.var3963[31] = mpc_socp__qoco_solver->sol->x[609];
  mpc_socp__CPG_Prim.var3963[32] = mpc_socp__qoco_solver->sol->x[610];
  mpc_socp__CPG_Prim.var3963[33] = mpc_socp__qoco_solver->sol->x[611];
  mpc_socp__CPG_Prim.var3963[34] = mpc_socp__qoco_solver->sol->x[612];
  mpc_socp__CPG_Prim.var3963[35] = mpc_socp__qoco_solver->sol->x[613];
  mpc_socp__CPG_Prim.var3963[36] = mpc_socp__qoco_solver->sol->x[614];
  mpc_socp__CPG_Prim.var3963[37] = mpc_socp__qoco_solver->sol->x[615];
  mpc_socp__CPG_Prim.var3963[38] = mpc_socp__qoco_solver->sol->x[616];
  mpc_socp__CPG_Prim.var3963[39] = mpc_socp__qoco_solver->sol->x[617];
  mpc_socp__CPG_Prim.var3963[40] = mpc_socp__qoco_solver->sol->x[618];
  mpc_socp__CPG_Prim.var3963[41] = mpc_socp__qoco_solver->sol->x[619];
  mpc_socp__CPG_Prim.var3963[42] = mpc_socp__qoco_solver->sol->x[620];
  mpc_socp__CPG_Prim.var3963[43] = mpc_socp__qoco_solver->sol->x[621];
  mpc_socp__CPG_Prim.var3963[44] = mpc_socp__qoco_solver->sol->x[622];
  mpc_socp__CPG_Prim.var3963[45] = mpc_socp__qoco_solver->sol->x[623];
  mpc_socp__CPG_Prim.var3963[46] = mpc_socp__qoco_solver->sol->x[624];
  mpc_socp__CPG_Prim.var3963[47] = mpc_socp__qoco_solver->sol->x[625];
  mpc_socp__CPG_Prim.var3963[48] = mpc_socp__qoco_solver->sol->x[626];
  mpc_socp__CPG_Prim.var3963[49] = mpc_socp__qoco_solver->sol->x[627];
  mpc_socp__CPG_Prim.var3963[50] = mpc_socp__qoco_solver->sol->x[628];
  mpc_socp__CPG_Prim.var3963[51] = mpc_socp__qoco_solver->sol->x[629];
  mpc_socp__CPG_Prim.var3963[52] = mpc_socp__qoco_solver->sol->x[630];
  mpc_socp__CPG_Prim.var3963[53] = mpc_socp__qoco_solver->sol->x[631];
  mpc_socp__CPG_Prim.var3963[54] = mpc_socp__qoco_solver->sol->x[632];
  mpc_socp__CPG_Prim.var3963[55] = mpc_socp__qoco_solver->sol->x[633];
  mpc_socp__CPG_Prim.var3963[56] = mpc_socp__qoco_solver->sol->x[634];
  mpc_socp__CPG_Prim.var3963[57] = mpc_socp__qoco_solver->sol->x[635];
  mpc_socp__CPG_Prim.var3963[58] = mpc_socp__qoco_solver->sol->x[636];
  mpc_socp__CPG_Prim.var3963[59] = mpc_socp__qoco_solver->sol->x[637];
  mpc_socp__CPG_Prim.var3963[60] = mpc_socp__qoco_solver->sol->x[638];
  mpc_socp__CPG_Prim.var3963[61] = mpc_socp__qoco_solver->sol->x[639];
  mpc_socp__CPG_Prim.var3963[62] = mpc_socp__qoco_solver->sol->x[640];
  mpc_socp__CPG_Prim.var3963[63] = mpc_socp__qoco_solver->sol->x[641];
  mpc_socp__CPG_Prim.var3963[64] = mpc_socp__qoco_solver->sol->x[642];
  mpc_socp__CPG_Prim.var3963[65] = mpc_socp__qoco_solver->sol->x[643];
  mpc_socp__CPG_Prim.var3963[66] = mpc_socp__qoco_solver->sol->x[644];
  mpc_socp__CPG_Prim.var3963[67] = mpc_socp__qoco_solver->sol->x[645];
  mpc_socp__CPG_Prim.var3963[68] = mpc_socp__qoco_solver->sol->x[646];
  mpc_socp__CPG_Prim.var3963[69] = mpc_socp__qoco_solver->sol->x[647];
  mpc_socp__CPG_Prim.var3963[70] = mpc_socp__qoco_solver->sol->x[648];
  mpc_socp__CPG_Prim.var3963[71] = mpc_socp__qoco_solver->sol->x[649];
  mpc_socp__CPG_Prim.var3963[72] = mpc_socp__qoco_solver->sol->x[650];
  mpc_socp__CPG_Prim.var3963[73] = mpc_socp__qoco_solver->sol->x[651];
  mpc_socp__CPG_Prim.var3963[74] = mpc_socp__qoco_solver->sol->x[652];
  mpc_socp__CPG_Prim.var3963[75] = mpc_socp__qoco_solver->sol->x[653];
  mpc_socp__CPG_Prim.var3963[76] = mpc_socp__qoco_solver->sol->x[654];
  mpc_socp__CPG_Prim.var3963[77] = mpc_socp__qoco_solver->sol->x[655];
  mpc_socp__CPG_Prim.var3963[78] = mpc_socp__qoco_solver->sol->x[656];
  mpc_socp__CPG_Prim.var3963[79] = mpc_socp__qoco_solver->sol->x[657];
  mpc_socp__CPG_Prim.var3963[80] = mpc_socp__qoco_solver->sol->x[658];
  mpc_socp__CPG_Prim.var3963[81] = mpc_socp__qoco_solver->sol->x[659];
  mpc_socp__CPG_Prim.var3963[82] = mpc_socp__qoco_solver->sol->x[660];
  mpc_socp__CPG_Prim.var3963[83] = mpc_socp__qoco_solver->sol->x[661];
  mpc_socp__CPG_Prim.var3963[84] = mpc_socp__qoco_solver->sol->x[662];
  mpc_socp__CPG_Prim.var3963[85] = mpc_socp__qoco_solver->sol->x[663];
  mpc_socp__CPG_Prim.var3963[86] = mpc_socp__qoco_solver->sol->x[664];
  mpc_socp__CPG_Prim.var3963[87] = mpc_socp__qoco_solver->sol->x[665];
  mpc_socp__CPG_Prim.var3963[88] = mpc_socp__qoco_solver->sol->x[666];
  mpc_socp__CPG_Prim.var3963[89] = mpc_socp__qoco_solver->sol->x[667];
  mpc_socp__CPG_Prim.var3963[90] = mpc_socp__qoco_solver->sol->x[668];
  mpc_socp__CPG_Prim.var3963[91] = mpc_socp__qoco_solver->sol->x[669];
  mpc_socp__CPG_Prim.var3963[92] = mpc_socp__qoco_solver->sol->x[670];
  mpc_socp__CPG_Prim.var3963[93] = mpc_socp__qoco_solver->sol->x[671];
  mpc_socp__CPG_Prim.var3963[94] = mpc_socp__qoco_solver->sol->x[672];
  mpc_socp__CPG_Prim.var3963[95] = mpc_socp__qoco_solver->sol->x[673];
  mpc_socp__CPG_Prim.var3963[96] = mpc_socp__qoco_solver->sol->x[674];
  mpc_socp__CPG_Prim.var3963[97] = mpc_socp__qoco_solver->sol->x[675];
  mpc_socp__CPG_Prim.var3963[98] = mpc_socp__qoco_solver->sol->x[676];
  mpc_socp__CPG_Prim.var3963[99] = mpc_socp__qoco_solver->sol->x[677];
  mpc_socp__CPG_Prim.var3963[100] = mpc_socp__qoco_solver->sol->x[678];
  mpc_socp__CPG_Prim.var3963[101] = mpc_socp__qoco_solver->sol->x[679];
  mpc_socp__CPG_Prim.var3963[102] = mpc_socp__qoco_solver->sol->x[680];
  mpc_socp__CPG_Prim.var3963[103] = mpc_socp__qoco_solver->sol->x[681];
  mpc_socp__CPG_Prim.var3963[104] = mpc_socp__qoco_solver->sol->x[682];
  mpc_socp__CPG_Prim.var3963[105] = mpc_socp__qoco_solver->sol->x[683];
  mpc_socp__CPG_Prim.var3963[106] = mpc_socp__qoco_solver->sol->x[684];
  mpc_socp__CPG_Prim.var3963[107] = mpc_socp__qoco_solver->sol->x[685];
  mpc_socp__CPG_Prim.var3963[108] = mpc_socp__qoco_solver->sol->x[686];
  mpc_socp__CPG_Prim.var3963[109] = mpc_socp__qoco_solver->sol->x[687];
  mpc_socp__CPG_Prim.var3963[110] = mpc_socp__qoco_solver->sol->x[688];
  mpc_socp__CPG_Prim.var3963[111] = mpc_socp__qoco_solver->sol->x[689];
  mpc_socp__CPG_Prim.var3963[112] = mpc_socp__qoco_solver->sol->x[690];
  mpc_socp__CPG_Prim.var3963[113] = mpc_socp__qoco_solver->sol->x[691];
  mpc_socp__CPG_Prim.var3963[114] = mpc_socp__qoco_solver->sol->x[692];
  mpc_socp__CPG_Prim.var3963[115] = mpc_socp__qoco_solver->sol->x[693];
  mpc_socp__CPG_Prim.var3963[116] = mpc_socp__qoco_solver->sol->x[694];
  mpc_socp__CPG_Prim.var3963[117] = mpc_socp__qoco_solver->sol->x[695];
  mpc_socp__CPG_Prim.var3963[118] = mpc_socp__qoco_solver->sol->x[696];
  mpc_socp__CPG_Prim.var3963[119] = mpc_socp__qoco_solver->sol->x[697];
  mpc_socp__CPG_Prim.var3963[120] = mpc_socp__qoco_solver->sol->x[698];
  mpc_socp__CPG_Prim.var3963[121] = mpc_socp__qoco_solver->sol->x[699];
  mpc_socp__CPG_Prim.var3963[122] = mpc_socp__qoco_solver->sol->x[700];
  mpc_socp__CPG_Prim.var3963[123] = mpc_socp__qoco_solver->sol->x[701];
  mpc_socp__CPG_Prim.var3963[124] = mpc_socp__qoco_solver->sol->x[702];
  mpc_socp__CPG_Prim.var3963[125] = mpc_socp__qoco_solver->sol->x[703];
  mpc_socp__CPG_Prim.var3963[126] = mpc_socp__qoco_solver->sol->x[704];
  mpc_socp__CPG_Prim.var3963[127] = mpc_socp__qoco_solver->sol->x[705];
  mpc_socp__CPG_Prim.var3963[128] = mpc_socp__qoco_solver->sol->x[706];
  mpc_socp__CPG_Prim.var3963[129] = mpc_socp__qoco_solver->sol->x[707];
  mpc_socp__CPG_Prim.var3963[130] = mpc_socp__qoco_solver->sol->x[708];
  mpc_socp__CPG_Prim.var3963[131] = mpc_socp__qoco_solver->sol->x[709];
  mpc_socp__CPG_Prim.var3963[132] = mpc_socp__qoco_solver->sol->x[710];
  mpc_socp__CPG_Prim.var3963[133] = mpc_socp__qoco_solver->sol->x[711];
  mpc_socp__CPG_Prim.var3963[134] = mpc_socp__qoco_solver->sol->x[712];
  mpc_socp__CPG_Prim.var3963[135] = mpc_socp__qoco_solver->sol->x[713];
  mpc_socp__CPG_Prim.var3963[136] = mpc_socp__qoco_solver->sol->x[714];
  mpc_socp__CPG_Prim.var3963[137] = mpc_socp__qoco_solver->sol->x[715];
  mpc_socp__CPG_Prim.var3963[138] = mpc_socp__qoco_solver->sol->x[716];
  mpc_socp__CPG_Prim.var3963[139] = mpc_socp__qoco_solver->sol->x[717];
  mpc_socp__CPG_Prim.var3963[140] = mpc_socp__qoco_solver->sol->x[718];
  mpc_socp__CPG_Prim.var3963[141] = mpc_socp__qoco_solver->sol->x[719];
  mpc_socp__CPG_Prim.var3963[142] = mpc_socp__qoco_solver->sol->x[720];
  mpc_socp__CPG_Prim.var3963[143] = mpc_socp__qoco_solver->sol->x[721];
  mpc_socp__CPG_Prim.var3963[144] = mpc_socp__qoco_solver->sol->x[722];
  mpc_socp__CPG_Prim.var3963[145] = mpc_socp__qoco_solver->sol->x[723];
  mpc_socp__CPG_Prim.var3963[146] = mpc_socp__qoco_solver->sol->x[724];
  mpc_socp__CPG_Prim.var3963[147] = mpc_socp__qoco_solver->sol->x[725];
  mpc_socp__CPG_Prim.var3963[148] = mpc_socp__qoco_solver->sol->x[726];
  mpc_socp__CPG_Prim.var3963[149] = mpc_socp__qoco_solver->sol->x[727];
  mpc_socp__CPG_Prim.var3963[150] = mpc_socp__qoco_solver->sol->x[728];
  mpc_socp__CPG_Prim.var3963[151] = mpc_socp__qoco_solver->sol->x[729];
  mpc_socp__CPG_Prim.var3963[152] = mpc_socp__qoco_solver->sol->x[730];
  mpc_socp__CPG_Prim.var3963[153] = mpc_socp__qoco_solver->sol->x[731];
  mpc_socp__CPG_Prim.var3963[154] = mpc_socp__qoco_solver->sol->x[732];
  mpc_socp__CPG_Prim.var3963[155] = mpc_socp__qoco_solver->sol->x[733];
  mpc_socp__CPG_Prim.var3963[156] = mpc_socp__qoco_solver->sol->x[734];
  mpc_socp__CPG_Prim.var3963[157] = mpc_socp__qoco_solver->sol->x[735];
  mpc_socp__CPG_Prim.var3963[158] = mpc_socp__qoco_solver->sol->x[736];
  mpc_socp__CPG_Prim.var3963[159] = mpc_socp__qoco_solver->sol->x[737];
  mpc_socp__CPG_Prim.var3963[160] = mpc_socp__qoco_solver->sol->x[738];
  mpc_socp__CPG_Prim.var3963[161] = mpc_socp__qoco_solver->sol->x[739];
  mpc_socp__CPG_Prim.var3963[162] = mpc_socp__qoco_solver->sol->x[740];
  mpc_socp__CPG_Prim.var3963[163] = mpc_socp__qoco_solver->sol->x[741];
  mpc_socp__CPG_Prim.var3963[164] = mpc_socp__qoco_solver->sol->x[742];
  mpc_socp__CPG_Prim.var3963[165] = mpc_socp__qoco_solver->sol->x[743];
  mpc_socp__CPG_Prim.var3963[166] = mpc_socp__qoco_solver->sol->x[744];
  mpc_socp__CPG_Prim.var3963[167] = mpc_socp__qoco_solver->sol->x[745];
  mpc_socp__CPG_Prim.var3963[168] = mpc_socp__qoco_solver->sol->x[746];
  mpc_socp__CPG_Prim.var3963[169] = mpc_socp__qoco_solver->sol->x[747];
  mpc_socp__CPG_Prim.var3963[170] = mpc_socp__qoco_solver->sol->x[748];
  mpc_socp__CPG_Prim.var3963[171] = mpc_socp__qoco_solver->sol->x[749];
  mpc_socp__CPG_Prim.var3963[172] = mpc_socp__qoco_solver->sol->x[750];
  mpc_socp__CPG_Prim.var3963[173] = mpc_socp__qoco_solver->sol->x[751];
  mpc_socp__CPG_Prim.var3963[174] = mpc_socp__qoco_solver->sol->x[752];
  mpc_socp__CPG_Prim.var3963[175] = mpc_socp__qoco_solver->sol->x[753];
  mpc_socp__CPG_Prim.var3963[176] = mpc_socp__qoco_solver->sol->x[754];
  mpc_socp__CPG_Prim.var3963[177] = mpc_socp__qoco_solver->sol->x[755];
  mpc_socp__CPG_Prim.var3963[178] = mpc_socp__qoco_solver->sol->x[756];
  mpc_socp__CPG_Prim.var3963[179] = mpc_socp__qoco_solver->sol->x[757];
  mpc_socp__CPG_Prim.var3963[180] = mpc_socp__qoco_solver->sol->x[758];
  mpc_socp__CPG_Prim.var3963[181] = mpc_socp__qoco_solver->sol->x[759];
  mpc_socp__CPG_Prim.var3963[182] = mpc_socp__qoco_solver->sol->x[760];
  mpc_socp__CPG_Prim.var3963[183] = mpc_socp__qoco_solver->sol->x[761];
  mpc_socp__CPG_Prim.var3963[184] = mpc_socp__qoco_solver->sol->x[762];
  mpc_socp__CPG_Prim.var3963[185] = mpc_socp__qoco_solver->sol->x[763];
  mpc_socp__CPG_Prim.var3963[186] = mpc_socp__qoco_solver->sol->x[764];
  mpc_socp__CPG_Prim.var3963[187] = mpc_socp__qoco_solver->sol->x[765];
  mpc_socp__CPG_Prim.var3963[188] = mpc_socp__qoco_solver->sol->x[766];
  mpc_socp__CPG_Prim.var3963[189] = mpc_socp__qoco_solver->sol->x[767];
  mpc_socp__CPG_Prim.var3963[190] = mpc_socp__qoco_solver->sol->x[768];
  mpc_socp__CPG_Prim.var3963[191] = mpc_socp__qoco_solver->sol->x[769];
  mpc_socp__CPG_Prim.var3963[192] = mpc_socp__qoco_solver->sol->x[770];
  mpc_socp__CPG_Prim.var3963[193] = mpc_socp__qoco_solver->sol->x[771];
  mpc_socp__CPG_Prim.var3963[194] = mpc_socp__qoco_solver->sol->x[772];
  mpc_socp__CPG_Prim.var3963[195] = mpc_socp__qoco_solver->sol->x[773];
  mpc_socp__CPG_Prim.var3963[196] = mpc_socp__qoco_solver->sol->x[774];
  mpc_socp__CPG_Prim.var3963[197] = mpc_socp__qoco_solver->sol->x[775];
  mpc_socp__CPG_Prim.var3963[198] = mpc_socp__qoco_solver->sol->x[776];
  mpc_socp__CPG_Prim.var3963[199] = mpc_socp__qoco_solver->sol->x[777];
  mpc_socp__CPG_Prim.var3963[200] = mpc_socp__qoco_solver->sol->x[778];
  mpc_socp__CPG_Prim.var3963[201] = mpc_socp__qoco_solver->sol->x[779];
  mpc_socp__CPG_Prim.var3963[202] = mpc_socp__qoco_solver->sol->x[780];
  mpc_socp__CPG_Prim.var3963[203] = mpc_socp__qoco_solver->sol->x[781];
  mpc_socp__CPG_Prim.var3963[204] = mpc_socp__qoco_solver->sol->x[782];
  mpc_socp__CPG_Prim.var3963[205] = mpc_socp__qoco_solver->sol->x[783];
  mpc_socp__CPG_Prim.var3963[206] = mpc_socp__qoco_solver->sol->x[784];
  mpc_socp__CPG_Prim.var3963[207] = mpc_socp__qoco_solver->sol->x[785];
  mpc_socp__CPG_Prim.var3963[208] = mpc_socp__qoco_solver->sol->x[786];
  mpc_socp__CPG_Prim.var3963[209] = mpc_socp__qoco_solver->sol->x[787];
  mpc_socp__CPG_Prim.var3963[210] = mpc_socp__qoco_solver->sol->x[788];
  mpc_socp__CPG_Prim.var3963[211] = mpc_socp__qoco_solver->sol->x[789];
  mpc_socp__CPG_Prim.var3963[212] = mpc_socp__qoco_solver->sol->x[790];
  mpc_socp__CPG_Prim.var3963[213] = mpc_socp__qoco_solver->sol->x[791];
  mpc_socp__CPG_Prim.var3963[214] = mpc_socp__qoco_solver->sol->x[792];
  mpc_socp__CPG_Prim.var3963[215] = mpc_socp__qoco_solver->sol->x[793];
  mpc_socp__CPG_Prim.var3963[216] = mpc_socp__qoco_solver->sol->x[794];
  mpc_socp__CPG_Prim.var3963[217] = mpc_socp__qoco_solver->sol->x[795];
  mpc_socp__CPG_Prim.var3963[218] = mpc_socp__qoco_solver->sol->x[796];
  mpc_socp__CPG_Prim.var3963[219] = mpc_socp__qoco_solver->sol->x[797];
  mpc_socp__CPG_Prim.var3963[220] = mpc_socp__qoco_solver->sol->x[798];
  mpc_socp__CPG_Prim.var3963[221] = mpc_socp__qoco_solver->sol->x[799];
  mpc_socp__CPG_Prim.var3963[222] = mpc_socp__qoco_solver->sol->x[800];
  mpc_socp__CPG_Prim.var3963[223] = mpc_socp__qoco_solver->sol->x[801];
  mpc_socp__CPG_Prim.var3963[224] = mpc_socp__qoco_solver->sol->x[802];
  mpc_socp__CPG_Prim.var3963[225] = mpc_socp__qoco_solver->sol->x[803];
  mpc_socp__CPG_Prim.var3963[226] = mpc_socp__qoco_solver->sol->x[804];
  mpc_socp__CPG_Prim.var3963[227] = mpc_socp__qoco_solver->sol->x[805];
  mpc_socp__CPG_Prim.var3963[228] = mpc_socp__qoco_solver->sol->x[806];
  mpc_socp__CPG_Prim.var3963[229] = mpc_socp__qoco_solver->sol->x[807];
  mpc_socp__CPG_Prim.var3963[230] = mpc_socp__qoco_solver->sol->x[808];
  mpc_socp__CPG_Prim.var3963[231] = mpc_socp__qoco_solver->sol->x[809];
  mpc_socp__CPG_Prim.var3963[232] = mpc_socp__qoco_solver->sol->x[810];
  mpc_socp__CPG_Prim.var3963[233] = mpc_socp__qoco_solver->sol->x[811];
  mpc_socp__CPG_Prim.var3963[234] = mpc_socp__qoco_solver->sol->x[812];
  mpc_socp__CPG_Prim.var3963[235] = mpc_socp__qoco_solver->sol->x[813];
  mpc_socp__CPG_Prim.var3963[236] = mpc_socp__qoco_solver->sol->x[814];
  mpc_socp__CPG_Prim.var3963[237] = mpc_socp__qoco_solver->sol->x[815];
  mpc_socp__CPG_Prim.var3963[238] = mpc_socp__qoco_solver->sol->x[816];
  mpc_socp__CPG_Prim.var3963[239] = mpc_socp__qoco_solver->sol->x[817];
  mpc_socp__CPG_Prim.var3963[240] = mpc_socp__qoco_solver->sol->x[818];
  mpc_socp__CPG_Prim.var3963[241] = mpc_socp__qoco_solver->sol->x[819];
  mpc_socp__CPG_Prim.var3963[242] = mpc_socp__qoco_solver->sol->x[820];
  mpc_socp__CPG_Prim.var3963[243] = mpc_socp__qoco_solver->sol->x[821];
  mpc_socp__CPG_Prim.var3963[244] = mpc_socp__qoco_solver->sol->x[822];
  mpc_socp__CPG_Prim.var3963[245] = mpc_socp__qoco_solver->sol->x[823];
  mpc_socp__CPG_Prim.var3963[246] = mpc_socp__qoco_solver->sol->x[824];
  mpc_socp__CPG_Prim.var3963[247] = mpc_socp__qoco_solver->sol->x[825];
  mpc_socp__CPG_Prim.var3963[248] = mpc_socp__qoco_solver->sol->x[826];
  mpc_socp__CPG_Prim.var3963[249] = mpc_socp__qoco_solver->sol->x[827];
  mpc_socp__CPG_Prim.var3963[250] = mpc_socp__qoco_solver->sol->x[828];
  mpc_socp__CPG_Prim.var3963[251] = mpc_socp__qoco_solver->sol->x[829];
  mpc_socp__CPG_Prim.var3963[252] = mpc_socp__qoco_solver->sol->x[830];
  mpc_socp__CPG_Prim.var3963[253] = mpc_socp__qoco_solver->sol->x[831];
  mpc_socp__CPG_Prim.var3963[254] = mpc_socp__qoco_solver->sol->x[832];
  mpc_socp__CPG_Prim.var3963[255] = mpc_socp__qoco_solver->sol->x[833];
  mpc_socp__CPG_Prim.var3963[256] = mpc_socp__qoco_solver->sol->x[834];
  mpc_socp__CPG_Prim.var3963[257] = mpc_socp__qoco_solver->sol->x[835];
  mpc_socp__CPG_Prim.var3963[258] = mpc_socp__qoco_solver->sol->x[836];
  mpc_socp__CPG_Prim.var3963[259] = mpc_socp__qoco_solver->sol->x[837];
  mpc_socp__CPG_Prim.var3963[260] = mpc_socp__qoco_solver->sol->x[838];
  mpc_socp__CPG_Prim.var3963[261] = mpc_socp__qoco_solver->sol->x[839];
  mpc_socp__CPG_Prim.var3963[262] = mpc_socp__qoco_solver->sol->x[840];
  mpc_socp__CPG_Prim.var3963[263] = mpc_socp__qoco_solver->sol->x[841];
  mpc_socp__CPG_Prim.var3963[264] = mpc_socp__qoco_solver->sol->x[842];
  mpc_socp__CPG_Prim.var3963[265] = mpc_socp__qoco_solver->sol->x[843];
  mpc_socp__CPG_Prim.var3963[266] = mpc_socp__qoco_solver->sol->x[844];
  mpc_socp__CPG_Prim.var3963[267] = mpc_socp__qoco_solver->sol->x[845];
  mpc_socp__CPG_Prim.var3963[268] = mpc_socp__qoco_solver->sol->x[846];
  mpc_socp__CPG_Prim.var3963[269] = mpc_socp__qoco_solver->sol->x[847];
  mpc_socp__CPG_Prim.var3963[270] = mpc_socp__qoco_solver->sol->x[848];
  mpc_socp__CPG_Prim.var3963[271] = mpc_socp__qoco_solver->sol->x[849];
  mpc_socp__CPG_Prim.var3963[272] = mpc_socp__qoco_solver->sol->x[850];
  mpc_socp__CPG_Prim.var3963[273] = mpc_socp__qoco_solver->sol->x[851];
  mpc_socp__CPG_Prim.var3963[274] = mpc_socp__qoco_solver->sol->x[852];
  mpc_socp__CPG_Prim.var3963[275] = mpc_socp__qoco_solver->sol->x[853];
  mpc_socp__CPG_Prim.var3963[276] = mpc_socp__qoco_solver->sol->x[854];
  mpc_socp__CPG_Prim.var3963[277] = mpc_socp__qoco_solver->sol->x[855];
  mpc_socp__CPG_Prim.var3963[278] = mpc_socp__qoco_solver->sol->x[856];
  mpc_socp__CPG_Prim.var3963[279] = mpc_socp__qoco_solver->sol->x[857];
  mpc_socp__CPG_Prim.var3963[280] = mpc_socp__qoco_solver->sol->x[858];
  mpc_socp__CPG_Prim.var3963[281] = mpc_socp__qoco_solver->sol->x[859];
  mpc_socp__CPG_Prim.var3963[282] = mpc_socp__qoco_solver->sol->x[860];
  mpc_socp__CPG_Prim.var3963[283] = mpc_socp__qoco_solver->sol->x[861];
  mpc_socp__CPG_Prim.var3963[284] = mpc_socp__qoco_solver->sol->x[862];
  mpc_socp__CPG_Prim.var3963[285] = mpc_socp__qoco_solver->sol->x[863];
  mpc_socp__CPG_Prim.var3963[286] = mpc_socp__qoco_solver->sol->x[864];
  mpc_socp__CPG_Prim.var3963[287] = mpc_socp__qoco_solver->sol->x[865];
  mpc_socp__CPG_Prim.var3963[288] = mpc_socp__qoco_solver->sol->x[866];
  mpc_socp__CPG_Prim.var3963[289] = mpc_socp__qoco_solver->sol->x[867];
  mpc_socp__CPG_Prim.var3963[290] = mpc_socp__qoco_solver->sol->x[868];
  mpc_socp__CPG_Prim.var3963[291] = mpc_socp__qoco_solver->sol->x[869];
  mpc_socp__CPG_Prim.var3963[292] = mpc_socp__qoco_solver->sol->x[870];
  mpc_socp__CPG_Prim.var3963[293] = mpc_socp__qoco_solver->sol->x[871];
  mpc_socp__CPG_Prim.var3963[294] = mpc_socp__qoco_solver->sol->x[872];
  mpc_socp__CPG_Prim.var3963[295] = mpc_socp__qoco_solver->sol->x[873];
  mpc_socp__CPG_Prim.var3963[296] = mpc_socp__qoco_solver->sol->x[874];
  mpc_socp__CPG_Prim.var3963[297] = mpc_socp__qoco_solver->sol->x[875];
  mpc_socp__CPG_Prim.var3963[298] = mpc_socp__qoco_solver->sol->x[876];
  mpc_socp__CPG_Prim.var3963[299] = mpc_socp__qoco_solver->sol->x[877];
  mpc_socp__CPG_Prim.var3963[300] = mpc_socp__qoco_solver->sol->x[878];
  mpc_socp__CPG_Prim.var3963[301] = mpc_socp__qoco_solver->sol->x[879];
  mpc_socp__CPG_Prim.var3963[302] = mpc_socp__qoco_solver->sol->x[880];
  mpc_socp__CPG_Prim.var3963[303] = mpc_socp__qoco_solver->sol->x[881];
  mpc_socp__CPG_Prim.var3963[304] = mpc_socp__qoco_solver->sol->x[882];
  mpc_socp__CPG_Prim.var3963[305] = mpc_socp__qoco_solver->sol->x[883];
  mpc_socp__CPG_Prim.var3963[306] = mpc_socp__qoco_solver->sol->x[884];
  mpc_socp__CPG_Prim.var3963[307] = mpc_socp__qoco_solver->sol->x[885];
  mpc_socp__CPG_Prim.var3963[308] = mpc_socp__qoco_solver->sol->x[886];
  mpc_socp__CPG_Prim.var3963[309] = mpc_socp__qoco_solver->sol->x[887];
  mpc_socp__CPG_Prim.var3963[310] = mpc_socp__qoco_solver->sol->x[888];
  mpc_socp__CPG_Prim.var3963[311] = mpc_socp__qoco_solver->sol->x[889];
  mpc_socp__CPG_Prim.var3963[312] = mpc_socp__qoco_solver->sol->x[890];
  mpc_socp__CPG_Prim.var3963[313] = mpc_socp__qoco_solver->sol->x[891];
  mpc_socp__CPG_Prim.var3963[314] = mpc_socp__qoco_solver->sol->x[892];
  mpc_socp__CPG_Prim.var3963[315] = mpc_socp__qoco_solver->sol->x[893];
  mpc_socp__CPG_Prim.var3963[316] = mpc_socp__qoco_solver->sol->x[894];
  mpc_socp__CPG_Prim.var3963[317] = mpc_socp__qoco_solver->sol->x[895];
  mpc_socp__CPG_Prim.var3963[318] = mpc_socp__qoco_solver->sol->x[896];
  mpc_socp__CPG_Prim.var3963[319] = mpc_socp__qoco_solver->sol->x[897];
  mpc_socp__CPG_Prim.var3963[320] = mpc_socp__qoco_solver->sol->x[898];
  mpc_socp__CPG_Prim.var3963[321] = mpc_socp__qoco_solver->sol->x[899];
  mpc_socp__CPG_Prim.var3963[322] = mpc_socp__qoco_solver->sol->x[900];
  mpc_socp__CPG_Prim.var3963[323] = mpc_socp__qoco_solver->sol->x[901];
  mpc_socp__CPG_Prim.var3963[324] = mpc_socp__qoco_solver->sol->x[902];
  mpc_socp__CPG_Prim.var3963[325] = mpc_socp__qoco_solver->sol->x[903];
  mpc_socp__CPG_Prim.var3963[326] = mpc_socp__qoco_solver->sol->x[904];
  mpc_socp__CPG_Prim.var3963[327] = mpc_socp__qoco_solver->sol->x[905];
  mpc_socp__CPG_Prim.var3963[328] = mpc_socp__qoco_solver->sol->x[906];
  mpc_socp__CPG_Prim.var3963[329] = mpc_socp__qoco_solver->sol->x[907];
  mpc_socp__CPG_Prim.var3963[330] = mpc_socp__qoco_solver->sol->x[908];
  mpc_socp__CPG_Prim.var3963[331] = mpc_socp__qoco_solver->sol->x[909];
  mpc_socp__CPG_Prim.var3963[332] = mpc_socp__qoco_solver->sol->x[910];
  mpc_socp__CPG_Prim.var3963[333] = mpc_socp__qoco_solver->sol->x[911];
  mpc_socp__CPG_Prim.var3963[334] = mpc_socp__qoco_solver->sol->x[912];
  mpc_socp__CPG_Prim.var3963[335] = mpc_socp__qoco_solver->sol->x[913];
  mpc_socp__CPG_Prim.var3963[336] = mpc_socp__qoco_solver->sol->x[914];
  mpc_socp__CPG_Prim.var3963[337] = mpc_socp__qoco_solver->sol->x[915];
  mpc_socp__CPG_Prim.var3963[338] = mpc_socp__qoco_solver->sol->x[916];
  mpc_socp__CPG_Prim.var3963[339] = mpc_socp__qoco_solver->sol->x[917];
  mpc_socp__CPG_Prim.var3963[340] = mpc_socp__qoco_solver->sol->x[918];
  mpc_socp__CPG_Prim.var3963[341] = mpc_socp__qoco_solver->sol->x[919];
  mpc_socp__CPG_Prim.var3963[342] = mpc_socp__qoco_solver->sol->x[920];
  mpc_socp__CPG_Prim.var3963[343] = mpc_socp__qoco_solver->sol->x[921];
  mpc_socp__CPG_Prim.var3963[344] = mpc_socp__qoco_solver->sol->x[922];
  mpc_socp__CPG_Prim.var3963[345] = mpc_socp__qoco_solver->sol->x[923];
  mpc_socp__CPG_Prim.var3963[346] = mpc_socp__qoco_solver->sol->x[924];
  mpc_socp__CPG_Prim.var3963[347] = mpc_socp__qoco_solver->sol->x[925];
  mpc_socp__CPG_Prim.var3963[348] = mpc_socp__qoco_solver->sol->x[926];
  mpc_socp__CPG_Prim.var3963[349] = mpc_socp__qoco_solver->sol->x[927];
  mpc_socp__CPG_Prim.var3963[350] = mpc_socp__qoco_solver->sol->x[928];
  mpc_socp__CPG_Prim.var3963[351] = mpc_socp__qoco_solver->sol->x[929];
  mpc_socp__CPG_Prim.var3963[352] = mpc_socp__qoco_solver->sol->x[930];
  mpc_socp__CPG_Prim.var3963[353] = mpc_socp__qoco_solver->sol->x[931];
  mpc_socp__CPG_Prim.var3963[354] = mpc_socp__qoco_solver->sol->x[932];
  mpc_socp__CPG_Prim.var3963[355] = mpc_socp__qoco_solver->sol->x[933];
  mpc_socp__CPG_Prim.var3963[356] = mpc_socp__qoco_solver->sol->x[934];
  mpc_socp__CPG_Prim.var3963[357] = mpc_socp__qoco_solver->sol->x[935];
  mpc_socp__CPG_Prim.var3963[358] = mpc_socp__qoco_solver->sol->x[936];
  mpc_socp__CPG_Prim.var3963[359] = mpc_socp__qoco_solver->sol->x[937];
  mpc_socp__CPG_Prim.var3963[360] = mpc_socp__qoco_solver->sol->x[938];
  mpc_socp__CPG_Prim.var3963[361] = mpc_socp__qoco_solver->sol->x[939];
  mpc_socp__CPG_Prim.var3963[362] = mpc_socp__qoco_solver->sol->x[940];
  mpc_socp__CPG_Prim.var3963[363] = mpc_socp__qoco_solver->sol->x[941];
  mpc_socp__CPG_Prim.var3963[364] = mpc_socp__qoco_solver->sol->x[942];
  mpc_socp__CPG_Prim.var3963[365] = mpc_socp__qoco_solver->sol->x[943];
  mpc_socp__CPG_Prim.var3963[366] = mpc_socp__qoco_solver->sol->x[944];
  mpc_socp__CPG_Prim.var3963[367] = mpc_socp__qoco_solver->sol->x[945];
  mpc_socp__CPG_Prim.var3963[368] = mpc_socp__qoco_solver->sol->x[946];
  mpc_socp__CPG_Prim.var3963[369] = mpc_socp__qoco_solver->sol->x[947];
  mpc_socp__CPG_Prim.var3963[370] = mpc_socp__qoco_solver->sol->x[948];
  mpc_socp__CPG_Prim.var3963[371] = mpc_socp__qoco_solver->sol->x[949];
  mpc_socp__CPG_Prim.var3963[372] = mpc_socp__qoco_solver->sol->x[950];
  mpc_socp__CPG_Prim.var3963[373] = mpc_socp__qoco_solver->sol->x[951];
  mpc_socp__CPG_Prim.var3963[374] = mpc_socp__qoco_solver->sol->x[952];
  mpc_socp__CPG_Prim.var3963[375] = mpc_socp__qoco_solver->sol->x[953];
  mpc_socp__CPG_Prim.var3963[376] = mpc_socp__qoco_solver->sol->x[954];
  mpc_socp__CPG_Prim.var3963[377] = mpc_socp__qoco_solver->sol->x[955];
  mpc_socp__CPG_Prim.var3963[378] = mpc_socp__qoco_solver->sol->x[956];
  mpc_socp__CPG_Prim.var3963[379] = mpc_socp__qoco_solver->sol->x[957];
  mpc_socp__CPG_Prim.var3963[380] = mpc_socp__qoco_solver->sol->x[958];
  mpc_socp__CPG_Prim.var3963[381] = mpc_socp__qoco_solver->sol->x[959];
  mpc_socp__CPG_Prim.var3963[382] = mpc_socp__qoco_solver->sol->x[960];
  mpc_socp__CPG_Prim.var3963[383] = mpc_socp__qoco_solver->sol->x[961];
  mpc_socp__CPG_Prim.var3963[384] = mpc_socp__qoco_solver->sol->x[962];
  mpc_socp__CPG_Prim.var3963[385] = mpc_socp__qoco_solver->sol->x[963];
  mpc_socp__CPG_Prim.var3963[386] = mpc_socp__qoco_solver->sol->x[964];
  mpc_socp__CPG_Prim.var3963[387] = mpc_socp__qoco_solver->sol->x[965];
  mpc_socp__CPG_Prim.var3963[388] = mpc_socp__qoco_solver->sol->x[966];
  mpc_socp__CPG_Prim.var3963[389] = mpc_socp__qoco_solver->sol->x[967];
  mpc_socp__CPG_Prim.var3963[390] = mpc_socp__qoco_solver->sol->x[968];
  mpc_socp__CPG_Prim.var3963[391] = mpc_socp__qoco_solver->sol->x[969];
  mpc_socp__CPG_Prim.var3963[392] = mpc_socp__qoco_solver->sol->x[970];
  mpc_socp__CPG_Prim.var3963[393] = mpc_socp__qoco_solver->sol->x[971];
  mpc_socp__CPG_Prim.var3963[394] = mpc_socp__qoco_solver->sol->x[972];
  mpc_socp__CPG_Prim.var3963[395] = mpc_socp__qoco_solver->sol->x[973];
  mpc_socp__CPG_Prim.var3963[396] = mpc_socp__qoco_solver->sol->x[974];
  mpc_socp__CPG_Prim.var3963[397] = mpc_socp__qoco_solver->sol->x[975];
  mpc_socp__CPG_Prim.var3963[398] = mpc_socp__qoco_solver->sol->x[976];
  mpc_socp__CPG_Prim.var3963[399] = mpc_socp__qoco_solver->sol->x[977];
  mpc_socp__CPG_Prim.var3963[400] = mpc_socp__qoco_solver->sol->x[978];
  mpc_socp__CPG_Prim.var3963[401] = mpc_socp__qoco_solver->sol->x[979];
  mpc_socp__CPG_Prim.var3963[402] = mpc_socp__qoco_solver->sol->x[980];
  mpc_socp__CPG_Prim.var3963[403] = mpc_socp__qoco_solver->sol->x[981];
  mpc_socp__CPG_Prim.var3963[404] = mpc_socp__qoco_solver->sol->x[982];
  mpc_socp__CPG_Prim.var3963[405] = mpc_socp__qoco_solver->sol->x[983];
  mpc_socp__CPG_Prim.var3963[406] = mpc_socp__qoco_solver->sol->x[984];
  mpc_socp__CPG_Prim.var3963[407] = mpc_socp__qoco_solver->sol->x[985];
  mpc_socp__CPG_Prim.var3963[408] = mpc_socp__qoco_solver->sol->x[986];
  mpc_socp__CPG_Prim.var3963[409] = mpc_socp__qoco_solver->sol->x[987];
  mpc_socp__CPG_Prim.var3963[410] = mpc_socp__qoco_solver->sol->x[988];
  mpc_socp__CPG_Prim.var3963[411] = mpc_socp__qoco_solver->sol->x[989];
  mpc_socp__CPG_Prim.var3963[412] = mpc_socp__qoco_solver->sol->x[990];
  mpc_socp__CPG_Prim.var3963[413] = mpc_socp__qoco_solver->sol->x[991];
  mpc_socp__CPG_Prim.var3963[414] = mpc_socp__qoco_solver->sol->x[992];
  mpc_socp__CPG_Prim.var3963[415] = mpc_socp__qoco_solver->sol->x[993];
  mpc_socp__CPG_Prim.var3963[416] = mpc_socp__qoco_solver->sol->x[994];
  mpc_socp__CPG_Prim.var3963[417] = mpc_socp__qoco_solver->sol->x[995];
  mpc_socp__CPG_Prim.var3963[418] = mpc_socp__qoco_solver->sol->x[996];
  mpc_socp__CPG_Prim.var3963[419] = mpc_socp__qoco_solver->sol->x[997];
  mpc_socp__CPG_Prim.var3963[420] = mpc_socp__qoco_solver->sol->x[998];
  mpc_socp__CPG_Prim.var3963[421] = mpc_socp__qoco_solver->sol->x[999];
  mpc_socp__CPG_Prim.var3963[422] = mpc_socp__qoco_solver->sol->x[1000];
  mpc_socp__CPG_Prim.var3963[423] = mpc_socp__qoco_solver->sol->x[1001];
  mpc_socp__CPG_Prim.var3963[424] = mpc_socp__qoco_solver->sol->x[1002];
  mpc_socp__CPG_Prim.var3963[425] = mpc_socp__qoco_solver->sol->x[1003];
  mpc_socp__CPG_Prim.var3963[426] = mpc_socp__qoco_solver->sol->x[1004];
  mpc_socp__CPG_Prim.var3963[427] = mpc_socp__qoco_solver->sol->x[1005];
  mpc_socp__CPG_Prim.var3963[428] = mpc_socp__qoco_solver->sol->x[1006];
  mpc_socp__CPG_Prim.var3963[429] = mpc_socp__qoco_solver->sol->x[1007];
  mpc_socp__CPG_Prim.var3963[430] = mpc_socp__qoco_solver->sol->x[1008];
  mpc_socp__CPG_Prim.var3963[431] = mpc_socp__qoco_solver->sol->x[1009];
  mpc_socp__CPG_Prim.var3963[432] = mpc_socp__qoco_solver->sol->x[1010];
  mpc_socp__CPG_Prim.var3963[433] = mpc_socp__qoco_solver->sol->x[1011];
  mpc_socp__CPG_Prim.var3963[434] = mpc_socp__qoco_solver->sol->x[1012];
  mpc_socp__CPG_Prim.var3963[435] = mpc_socp__qoco_solver->sol->x[1013];
  mpc_socp__CPG_Prim.var3963[436] = mpc_socp__qoco_solver->sol->x[1014];
  mpc_socp__CPG_Prim.var3963[437] = mpc_socp__qoco_solver->sol->x[1015];
  mpc_socp__CPG_Prim.var3963[438] = mpc_socp__qoco_solver->sol->x[1016];
  mpc_socp__CPG_Prim.var3963[439] = mpc_socp__qoco_solver->sol->x[1017];
  mpc_socp__CPG_Prim.var3963[440] = mpc_socp__qoco_solver->sol->x[1018];
  mpc_socp__CPG_Prim.var3963[441] = mpc_socp__qoco_solver->sol->x[1019];
  mpc_socp__CPG_Prim.var3963[442] = mpc_socp__qoco_solver->sol->x[1020];
  mpc_socp__CPG_Prim.var3963[443] = mpc_socp__qoco_solver->sol->x[1021];
  mpc_socp__CPG_Prim.var3963[444] = mpc_socp__qoco_solver->sol->x[1022];
  mpc_socp__CPG_Prim.var3963[445] = mpc_socp__qoco_solver->sol->x[1023];
  mpc_socp__CPG_Prim.var3963[446] = mpc_socp__qoco_solver->sol->x[1024];
  mpc_socp__CPG_Prim.var3963[447] = mpc_socp__qoco_solver->sol->x[1025];
  mpc_socp__CPG_Prim.var3963[448] = mpc_socp__qoco_solver->sol->x[1026];
  mpc_socp__CPG_Prim.var3963[449] = mpc_socp__qoco_solver->sol->x[1027];
  mpc_socp__CPG_Prim.var3963[450] = mpc_socp__qoco_solver->sol->x[1028];
  mpc_socp__CPG_Prim.var3963[451] = mpc_socp__qoco_solver->sol->x[1029];
  mpc_socp__CPG_Prim.var3963[452] = mpc_socp__qoco_solver->sol->x[1030];
  mpc_socp__CPG_Prim.var3963[453] = mpc_socp__qoco_solver->sol->x[1031];
  mpc_socp__CPG_Prim.var3963[454] = mpc_socp__qoco_solver->sol->x[1032];
  mpc_socp__CPG_Prim.var3963[455] = mpc_socp__qoco_solver->sol->x[1033];
  mpc_socp__CPG_Prim.var3963[456] = mpc_socp__qoco_solver->sol->x[1034];
  mpc_socp__CPG_Prim.var3963[457] = mpc_socp__qoco_solver->sol->x[1035];
  mpc_socp__CPG_Prim.var3963[458] = mpc_socp__qoco_solver->sol->x[1036];
  mpc_socp__CPG_Prim.var3963[459] = mpc_socp__qoco_solver->sol->x[1037];
  mpc_socp__CPG_Prim.var3963[460] = mpc_socp__qoco_solver->sol->x[1038];
  mpc_socp__CPG_Prim.var3963[461] = mpc_socp__qoco_solver->sol->x[1039];
  mpc_socp__CPG_Prim.var3963[462] = mpc_socp__qoco_solver->sol->x[1040];
  mpc_socp__CPG_Prim.var3963[463] = mpc_socp__qoco_solver->sol->x[1041];
  mpc_socp__CPG_Prim.var3963[464] = mpc_socp__qoco_solver->sol->x[1042];
  mpc_socp__CPG_Prim.var3963[465] = mpc_socp__qoco_solver->sol->x[1043];
  mpc_socp__CPG_Prim.var3963[466] = mpc_socp__qoco_solver->sol->x[1044];
  mpc_socp__CPG_Prim.var3963[467] = mpc_socp__qoco_solver->sol->x[1045];
  mpc_socp__CPG_Prim.var3963[468] = mpc_socp__qoco_solver->sol->x[1046];
  mpc_socp__CPG_Prim.var3963[469] = mpc_socp__qoco_solver->sol->x[1047];
  mpc_socp__CPG_Prim.var3963[470] = mpc_socp__qoco_solver->sol->x[1048];
  mpc_socp__CPG_Prim.var3963[471] = mpc_socp__qoco_solver->sol->x[1049];
  mpc_socp__CPG_Prim.var3963[472] = mpc_socp__qoco_solver->sol->x[1050];
  mpc_socp__CPG_Prim.var3963[473] = mpc_socp__qoco_solver->sol->x[1051];
  mpc_socp__CPG_Prim.var3963[474] = mpc_socp__qoco_solver->sol->x[1052];
  mpc_socp__CPG_Prim.var3963[475] = mpc_socp__qoco_solver->sol->x[1053];
  mpc_socp__CPG_Prim.var3963[476] = mpc_socp__qoco_solver->sol->x[1054];
  mpc_socp__CPG_Prim.var3963[477] = mpc_socp__qoco_solver->sol->x[1055];
  mpc_socp__CPG_Prim.var3963[478] = mpc_socp__qoco_solver->sol->x[1056];
  mpc_socp__CPG_Prim.var3963[479] = mpc_socp__qoco_solver->sol->x[1057];
  mpc_socp__CPG_Prim.var3963[480] = mpc_socp__qoco_solver->sol->x[1058];
  mpc_socp__CPG_Prim.var3963[481] = mpc_socp__qoco_solver->sol->x[1059];
  mpc_socp__CPG_Prim.var3963[482] = mpc_socp__qoco_solver->sol->x[1060];
  mpc_socp__CPG_Prim.var3963[483] = mpc_socp__qoco_solver->sol->x[1061];
  mpc_socp__CPG_Prim.var3963[484] = mpc_socp__qoco_solver->sol->x[1062];
  mpc_socp__CPG_Prim.var3963[485] = mpc_socp__qoco_solver->sol->x[1063];
  mpc_socp__CPG_Prim.var3963[486] = mpc_socp__qoco_solver->sol->x[1064];
  mpc_socp__CPG_Prim.var3963[487] = mpc_socp__qoco_solver->sol->x[1065];
  mpc_socp__CPG_Prim.var3963[488] = mpc_socp__qoco_solver->sol->x[1066];
  mpc_socp__CPG_Prim.var3963[489] = mpc_socp__qoco_solver->sol->x[1067];
  mpc_socp__CPG_Prim.var3964[0] = mpc_socp__qoco_solver->sol->x[1068];
  mpc_socp__CPG_Prim.var3964[1] = mpc_socp__qoco_solver->sol->x[1069];
  mpc_socp__CPG_Prim.var3964[2] = mpc_socp__qoco_solver->sol->x[1070];
  mpc_socp__CPG_Prim.var3964[3] = mpc_socp__qoco_solver->sol->x[1071];
  mpc_socp__CPG_Prim.var3964[4] = mpc_socp__qoco_solver->sol->x[1072];
  mpc_socp__CPG_Prim.var3964[5] = mpc_socp__qoco_solver->sol->x[1073];
  mpc_socp__CPG_Prim.var3964[6] = mpc_socp__qoco_solver->sol->x[1074];
  mpc_socp__CPG_Prim.var3964[7] = mpc_socp__qoco_solver->sol->x[1075];
  mpc_socp__CPG_Prim.var3964[8] = mpc_socp__qoco_solver->sol->x[1076];
  mpc_socp__CPG_Prim.var3964[9] = mpc_socp__qoco_solver->sol->x[1077];
  mpc_socp__CPG_Prim.var3964[10] = mpc_socp__qoco_solver->sol->x[1078];
  mpc_socp__CPG_Prim.var3964[11] = mpc_socp__qoco_solver->sol->x[1079];
  mpc_socp__CPG_Prim.var3964[12] = mpc_socp__qoco_solver->sol->x[1080];
  mpc_socp__CPG_Prim.var3964[13] = mpc_socp__qoco_solver->sol->x[1081];
  mpc_socp__CPG_Prim.var3964[14] = mpc_socp__qoco_solver->sol->x[1082];
  mpc_socp__CPG_Prim.var3964[15] = mpc_socp__qoco_solver->sol->x[1083];
  mpc_socp__CPG_Prim.var3964[16] = mpc_socp__qoco_solver->sol->x[1084];
  mpc_socp__CPG_Prim.var3964[17] = mpc_socp__qoco_solver->sol->x[1085];
  mpc_socp__CPG_Prim.var3964[18] = mpc_socp__qoco_solver->sol->x[1086];
  mpc_socp__CPG_Prim.var3964[19] = mpc_socp__qoco_solver->sol->x[1087];
  mpc_socp__CPG_Prim.var3964[20] = mpc_socp__qoco_solver->sol->x[1088];
  mpc_socp__CPG_Prim.var3964[21] = mpc_socp__qoco_solver->sol->x[1089];
  mpc_socp__CPG_Prim.var3964[22] = mpc_socp__qoco_solver->sol->x[1090];
  mpc_socp__CPG_Prim.var3964[23] = mpc_socp__qoco_solver->sol->x[1091];
  mpc_socp__CPG_Prim.var3964[24] = mpc_socp__qoco_solver->sol->x[1092];
  mpc_socp__CPG_Prim.var3964[25] = mpc_socp__qoco_solver->sol->x[1093];
  mpc_socp__CPG_Prim.var3964[26] = mpc_socp__qoco_solver->sol->x[1094];
  mpc_socp__CPG_Prim.var3964[27] = mpc_socp__qoco_solver->sol->x[1095];
  mpc_socp__CPG_Prim.var3964[28] = mpc_socp__qoco_solver->sol->x[1096];
  mpc_socp__CPG_Prim.var3964[29] = mpc_socp__qoco_solver->sol->x[1097];
  mpc_socp__CPG_Prim.var3964[30] = mpc_socp__qoco_solver->sol->x[1098];
  mpc_socp__CPG_Prim.var3964[31] = mpc_socp__qoco_solver->sol->x[1099];
  mpc_socp__CPG_Prim.var3964[32] = mpc_socp__qoco_solver->sol->x[1100];
  mpc_socp__CPG_Prim.var3964[33] = mpc_socp__qoco_solver->sol->x[1101];
  mpc_socp__CPG_Prim.var3964[34] = mpc_socp__qoco_solver->sol->x[1102];
  mpc_socp__CPG_Prim.var3964[35] = mpc_socp__qoco_solver->sol->x[1103];
  mpc_socp__CPG_Prim.var3964[36] = mpc_socp__qoco_solver->sol->x[1104];
  mpc_socp__CPG_Prim.var3964[37] = mpc_socp__qoco_solver->sol->x[1105];
  mpc_socp__CPG_Prim.var3964[38] = mpc_socp__qoco_solver->sol->x[1106];
  mpc_socp__CPG_Prim.var3964[39] = mpc_socp__qoco_solver->sol->x[1107];
  mpc_socp__CPG_Prim.var3964[40] = mpc_socp__qoco_solver->sol->x[1108];
  mpc_socp__CPG_Prim.var3964[41] = mpc_socp__qoco_solver->sol->x[1109];
  mpc_socp__CPG_Prim.var3964[42] = mpc_socp__qoco_solver->sol->x[1110];
  mpc_socp__CPG_Prim.var3964[43] = mpc_socp__qoco_solver->sol->x[1111];
  mpc_socp__CPG_Prim.var3964[44] = mpc_socp__qoco_solver->sol->x[1112];
  mpc_socp__CPG_Prim.var3964[45] = mpc_socp__qoco_solver->sol->x[1113];
  mpc_socp__CPG_Prim.var3964[46] = mpc_socp__qoco_solver->sol->x[1114];
  mpc_socp__CPG_Prim.var3964[47] = mpc_socp__qoco_solver->sol->x[1115];
  mpc_socp__CPG_Prim.var3964[48] = mpc_socp__qoco_solver->sol->x[1116];
  mpc_socp__CPG_Prim.var3964[49] = mpc_socp__qoco_solver->sol->x[1117];
  mpc_socp__CPG_Prim.var3964[50] = mpc_socp__qoco_solver->sol->x[1118];
  mpc_socp__CPG_Prim.var3964[51] = mpc_socp__qoco_solver->sol->x[1119];
  mpc_socp__CPG_Prim.var3964[52] = mpc_socp__qoco_solver->sol->x[1120];
  mpc_socp__CPG_Prim.var3964[53] = mpc_socp__qoco_solver->sol->x[1121];
  mpc_socp__CPG_Prim.var3964[54] = mpc_socp__qoco_solver->sol->x[1122];
  mpc_socp__CPG_Prim.var3964[55] = mpc_socp__qoco_solver->sol->x[1123];
  mpc_socp__CPG_Prim.var3964[56] = mpc_socp__qoco_solver->sol->x[1124];
  mpc_socp__CPG_Prim.var3964[57] = mpc_socp__qoco_solver->sol->x[1125];
  mpc_socp__CPG_Prim.var3964[58] = mpc_socp__qoco_solver->sol->x[1126];
  mpc_socp__CPG_Prim.var3964[59] = mpc_socp__qoco_solver->sol->x[1127];
  mpc_socp__CPG_Prim.var3964[60] = mpc_socp__qoco_solver->sol->x[1128];
  mpc_socp__CPG_Prim.var3964[61] = mpc_socp__qoco_solver->sol->x[1129];
  mpc_socp__CPG_Prim.var3964[62] = mpc_socp__qoco_solver->sol->x[1130];
  mpc_socp__CPG_Prim.var3964[63] = mpc_socp__qoco_solver->sol->x[1131];
  mpc_socp__CPG_Prim.var3964[64] = mpc_socp__qoco_solver->sol->x[1132];
  mpc_socp__CPG_Prim.var3964[65] = mpc_socp__qoco_solver->sol->x[1133];
  mpc_socp__CPG_Prim.var3964[66] = mpc_socp__qoco_solver->sol->x[1134];
  mpc_socp__CPG_Prim.var3964[67] = mpc_socp__qoco_solver->sol->x[1135];
  mpc_socp__CPG_Prim.var3964[68] = mpc_socp__qoco_solver->sol->x[1136];
  mpc_socp__CPG_Prim.var3964[69] = mpc_socp__qoco_solver->sol->x[1137];
  mpc_socp__CPG_Prim.var3964[70] = mpc_socp__qoco_solver->sol->x[1138];
  mpc_socp__CPG_Prim.var3964[71] = mpc_socp__qoco_solver->sol->x[1139];
  mpc_socp__CPG_Prim.var3964[72] = mpc_socp__qoco_solver->sol->x[1140];
  mpc_socp__CPG_Prim.var3964[73] = mpc_socp__qoco_solver->sol->x[1141];
  mpc_socp__CPG_Prim.var3964[74] = mpc_socp__qoco_solver->sol->x[1142];
  mpc_socp__CPG_Prim.var3964[75] = mpc_socp__qoco_solver->sol->x[1143];
  mpc_socp__CPG_Prim.var3964[76] = mpc_socp__qoco_solver->sol->x[1144];
  mpc_socp__CPG_Prim.var3964[77] = mpc_socp__qoco_solver->sol->x[1145];
  mpc_socp__CPG_Prim.var3964[78] = mpc_socp__qoco_solver->sol->x[1146];
  mpc_socp__CPG_Prim.var3964[79] = mpc_socp__qoco_solver->sol->x[1147];
  mpc_socp__CPG_Prim.var3964[80] = mpc_socp__qoco_solver->sol->x[1148];
  mpc_socp__CPG_Prim.var3964[81] = mpc_socp__qoco_solver->sol->x[1149];
  mpc_socp__CPG_Prim.var3964[82] = mpc_socp__qoco_solver->sol->x[1150];
  mpc_socp__CPG_Prim.var3964[83] = mpc_socp__qoco_solver->sol->x[1151];
  mpc_socp__CPG_Prim.var3964[84] = mpc_socp__qoco_solver->sol->x[1152];
  mpc_socp__CPG_Prim.var3964[85] = mpc_socp__qoco_solver->sol->x[1153];
  mpc_socp__CPG_Prim.var3964[86] = mpc_socp__qoco_solver->sol->x[1154];
  mpc_socp__CPG_Prim.var3964[87] = mpc_socp__qoco_solver->sol->x[1155];
  mpc_socp__CPG_Prim.var3964[88] = mpc_socp__qoco_solver->sol->x[1156];
  mpc_socp__CPG_Prim.var3964[89] = mpc_socp__qoco_solver->sol->x[1157];
  mpc_socp__CPG_Prim.var3964[90] = mpc_socp__qoco_solver->sol->x[1158];
  mpc_socp__CPG_Prim.var3964[91] = mpc_socp__qoco_solver->sol->x[1159];
  mpc_socp__CPG_Prim.var3964[92] = mpc_socp__qoco_solver->sol->x[1160];
  mpc_socp__CPG_Prim.var3964[93] = mpc_socp__qoco_solver->sol->x[1161];
  mpc_socp__CPG_Prim.var3964[94] = mpc_socp__qoco_solver->sol->x[1162];
  mpc_socp__CPG_Prim.var3964[95] = mpc_socp__qoco_solver->sol->x[1163];
  mpc_socp__CPG_Prim.var3964[96] = mpc_socp__qoco_solver->sol->x[1164];
  mpc_socp__CPG_Prim.var3964[97] = mpc_socp__qoco_solver->sol->x[1165];
  mpc_socp__CPG_Prim.var3964[98] = mpc_socp__qoco_solver->sol->x[1166];
  mpc_socp__CPG_Prim.var3964[99] = mpc_socp__qoco_solver->sol->x[1167];
  mpc_socp__CPG_Prim.var3964[100] = mpc_socp__qoco_solver->sol->x[1168];
  mpc_socp__CPG_Prim.var3964[101] = mpc_socp__qoco_solver->sol->x[1169];
}

// Retrieve dual solution in terms of user-defined constraints
void mpc_socp__cpg_retrieve_dual(){
  mpc_socp__CPG_Dual.d0[0] = mpc_socp__qoco_solver->sol->y[578];
  mpc_socp__CPG_Dual.d0[1] = mpc_socp__qoco_solver->sol->y[579];
  mpc_socp__CPG_Dual.d0[2] = mpc_socp__qoco_solver->sol->y[580];
  mpc_socp__CPG_Dual.d0[3] = mpc_socp__qoco_solver->sol->y[581];
  mpc_socp__CPG_Dual.d0[4] = mpc_socp__qoco_solver->sol->y[582];
  mpc_socp__CPG_Dual.d0[5] = mpc_socp__qoco_solver->sol->y[583];
  mpc_socp__CPG_Dual.d0[6] = mpc_socp__qoco_solver->sol->y[584];
  mpc_socp__CPG_Dual.d0[7] = mpc_socp__qoco_solver->sol->y[585];
  mpc_socp__CPG_Dual.d0[8] = mpc_socp__qoco_solver->sol->y[586];
  mpc_socp__CPG_Dual.d0[9] = mpc_socp__qoco_solver->sol->y[587];
  mpc_socp__CPG_Dual.d0[10] = mpc_socp__qoco_solver->sol->y[588];
  mpc_socp__CPG_Dual.d0[11] = mpc_socp__qoco_solver->sol->y[589];
  mpc_socp__CPG_Dual.d0[12] = mpc_socp__qoco_solver->sol->y[590];
  mpc_socp__CPG_Dual.d0[13] = mpc_socp__qoco_solver->sol->y[591];
  mpc_socp__CPG_Dual.d1[0] = mpc_socp__qoco_solver->sol->y[592];
  mpc_socp__CPG_Dual.d1[1] = mpc_socp__qoco_solver->sol->y[593];
  mpc_socp__CPG_Dual.d1[2] = mpc_socp__qoco_solver->sol->y[594];
  mpc_socp__CPG_Dual.d1[3] = mpc_socp__qoco_solver->sol->y[595];
  mpc_socp__CPG_Dual.d1[4] = mpc_socp__qoco_solver->sol->y[596];
  mpc_socp__CPG_Dual.d1[5] = mpc_socp__qoco_solver->sol->y[597];
  mpc_socp__CPG_Dual.d1[6] = mpc_socp__qoco_solver->sol->y[598];
  mpc_socp__CPG_Dual.d1[7] = mpc_socp__qoco_solver->sol->y[599];
  mpc_socp__CPG_Dual.d1[8] = mpc_socp__qoco_solver->sol->y[600];
  mpc_socp__CPG_Dual.d1[9] = mpc_socp__qoco_solver->sol->y[601];
  mpc_socp__CPG_Dual.d1[10] = mpc_socp__qoco_solver->sol->y[602];
  mpc_socp__CPG_Dual.d1[11] = mpc_socp__qoco_solver->sol->y[603];
  mpc_socp__CPG_Dual.d1[12] = mpc_socp__qoco_solver->sol->y[604];
  mpc_socp__CPG_Dual.d1[13] = mpc_socp__qoco_solver->sol->y[605];
  mpc_socp__CPG_Dual.d2 = mpc_socp__qoco_solver->sol->z[0];
  mpc_socp__CPG_Dual.d3 = mpc_socp__qoco_solver->sol->z[1];
  mpc_socp__CPG_Dual.d4 = mpc_socp__qoco_solver->sol->z[2];
  mpc_socp__CPG_Dual.d5[0] = mpc_socp__qoco_solver->sol->y[606];
  mpc_socp__CPG_Dual.d5[1] = mpc_socp__qoco_solver->sol->y[607];
  mpc_socp__CPG_Dual.d5[2] = mpc_socp__qoco_solver->sol->y[608];
  mpc_socp__CPG_Dual.d5[3] = mpc_socp__qoco_solver->sol->y[609];
  mpc_socp__CPG_Dual.d5[4] = mpc_socp__qoco_solver->sol->y[610];
  mpc_socp__CPG_Dual.d5[5] = mpc_socp__qoco_solver->sol->y[611];
  mpc_socp__CPG_Dual.d5[6] = mpc_socp__qoco_solver->sol->y[612];
  mpc_socp__CPG_Dual.d5[7] = mpc_socp__qoco_solver->sol->y[613];
  mpc_socp__CPG_Dual.d5[8] = mpc_socp__qoco_solver->sol->y[614];
  mpc_socp__CPG_Dual.d5[9] = mpc_socp__qoco_solver->sol->y[615];
  mpc_socp__CPG_Dual.d5[10] = mpc_socp__qoco_solver->sol->y[616];
  mpc_socp__CPG_Dual.d5[11] = mpc_socp__qoco_solver->sol->y[617];
  mpc_socp__CPG_Dual.d5[12] = mpc_socp__qoco_solver->sol->y[618];
  mpc_socp__CPG_Dual.d5[13] = mpc_socp__qoco_solver->sol->y[619];
  mpc_socp__CPG_Dual.d6 = mpc_socp__qoco_solver->sol->z[3];
  mpc_socp__CPG_Dual.d7 = mpc_socp__qoco_solver->sol->z[4];
  mpc_socp__CPG_Dual.d8 = mpc_socp__qoco_solver->sol->z[5];
  mpc_socp__CPG_Dual.d9[0] = mpc_socp__qoco_solver->sol->y[620];
  mpc_socp__CPG_Dual.d9[1] = mpc_socp__qoco_solver->sol->y[621];
  mpc_socp__CPG_Dual.d9[2] = mpc_socp__qoco_solver->sol->y[622];
  mpc_socp__CPG_Dual.d9[3] = mpc_socp__qoco_solver->sol->y[623];
  mpc_socp__CPG_Dual.d9[4] = mpc_socp__qoco_solver->sol->y[624];
  mpc_socp__CPG_Dual.d9[5] = mpc_socp__qoco_solver->sol->y[625];
  mpc_socp__CPG_Dual.d9[6] = mpc_socp__qoco_solver->sol->y[626];
  mpc_socp__CPG_Dual.d9[7] = mpc_socp__qoco_solver->sol->y[627];
  mpc_socp__CPG_Dual.d9[8] = mpc_socp__qoco_solver->sol->y[628];
  mpc_socp__CPG_Dual.d9[9] = mpc_socp__qoco_solver->sol->y[629];
  mpc_socp__CPG_Dual.d9[10] = mpc_socp__qoco_solver->sol->y[630];
  mpc_socp__CPG_Dual.d9[11] = mpc_socp__qoco_solver->sol->y[631];
  mpc_socp__CPG_Dual.d9[12] = mpc_socp__qoco_solver->sol->y[632];
  mpc_socp__CPG_Dual.d9[13] = mpc_socp__qoco_solver->sol->y[633];
  mpc_socp__CPG_Dual.d10 = mpc_socp__qoco_solver->sol->z[6];
  mpc_socp__CPG_Dual.d11 = mpc_socp__qoco_solver->sol->z[7];
  mpc_socp__CPG_Dual.d12 = mpc_socp__qoco_solver->sol->z[8];
  mpc_socp__CPG_Dual.d13[0] = mpc_socp__qoco_solver->sol->y[634];
  mpc_socp__CPG_Dual.d13[1] = mpc_socp__qoco_solver->sol->y[635];
  mpc_socp__CPG_Dual.d13[2] = mpc_socp__qoco_solver->sol->y[636];
  mpc_socp__CPG_Dual.d13[3] = mpc_socp__qoco_solver->sol->y[637];
  mpc_socp__CPG_Dual.d13[4] = mpc_socp__qoco_solver->sol->y[638];
  mpc_socp__CPG_Dual.d13[5] = mpc_socp__qoco_solver->sol->y[639];
  mpc_socp__CPG_Dual.d13[6] = mpc_socp__qoco_solver->sol->y[640];
  mpc_socp__CPG_Dual.d13[7] = mpc_socp__qoco_solver->sol->y[641];
  mpc_socp__CPG_Dual.d13[8] = mpc_socp__qoco_solver->sol->y[642];
  mpc_socp__CPG_Dual.d13[9] = mpc_socp__qoco_solver->sol->y[643];
  mpc_socp__CPG_Dual.d13[10] = mpc_socp__qoco_solver->sol->y[644];
  mpc_socp__CPG_Dual.d13[11] = mpc_socp__qoco_solver->sol->y[645];
  mpc_socp__CPG_Dual.d13[12] = mpc_socp__qoco_solver->sol->y[646];
  mpc_socp__CPG_Dual.d13[13] = mpc_socp__qoco_solver->sol->y[647];
  mpc_socp__CPG_Dual.d14 = mpc_socp__qoco_solver->sol->z[9];
  mpc_socp__CPG_Dual.d15 = mpc_socp__qoco_solver->sol->z[10];
  mpc_socp__CPG_Dual.d16 = mpc_socp__qoco_solver->sol->z[11];
  mpc_socp__CPG_Dual.d17[0] = mpc_socp__qoco_solver->sol->y[648];
  mpc_socp__CPG_Dual.d17[1] = mpc_socp__qoco_solver->sol->y[649];
  mpc_socp__CPG_Dual.d17[2] = mpc_socp__qoco_solver->sol->y[650];
  mpc_socp__CPG_Dual.d17[3] = mpc_socp__qoco_solver->sol->y[651];
  mpc_socp__CPG_Dual.d17[4] = mpc_socp__qoco_solver->sol->y[652];
  mpc_socp__CPG_Dual.d17[5] = mpc_socp__qoco_solver->sol->y[653];
  mpc_socp__CPG_Dual.d17[6] = mpc_socp__qoco_solver->sol->y[654];
  mpc_socp__CPG_Dual.d17[7] = mpc_socp__qoco_solver->sol->y[655];
  mpc_socp__CPG_Dual.d17[8] = mpc_socp__qoco_solver->sol->y[656];
  mpc_socp__CPG_Dual.d17[9] = mpc_socp__qoco_solver->sol->y[657];
  mpc_socp__CPG_Dual.d17[10] = mpc_socp__qoco_solver->sol->y[658];
  mpc_socp__CPG_Dual.d17[11] = mpc_socp__qoco_solver->sol->y[659];
  mpc_socp__CPG_Dual.d17[12] = mpc_socp__qoco_solver->sol->y[660];
  mpc_socp__CPG_Dual.d17[13] = mpc_socp__qoco_solver->sol->y[661];
  mpc_socp__CPG_Dual.d18 = mpc_socp__qoco_solver->sol->z[12];
  mpc_socp__CPG_Dual.d19 = mpc_socp__qoco_solver->sol->z[13];
  mpc_socp__CPG_Dual.d20 = mpc_socp__qoco_solver->sol->z[14];
  mpc_socp__CPG_Dual.d21[0] = mpc_socp__qoco_solver->sol->y[662];
  mpc_socp__CPG_Dual.d21[1] = mpc_socp__qoco_solver->sol->y[663];
  mpc_socp__CPG_Dual.d21[2] = mpc_socp__qoco_solver->sol->y[664];
  mpc_socp__CPG_Dual.d21[3] = mpc_socp__qoco_solver->sol->y[665];
  mpc_socp__CPG_Dual.d21[4] = mpc_socp__qoco_solver->sol->y[666];
  mpc_socp__CPG_Dual.d21[5] = mpc_socp__qoco_solver->sol->y[667];
  mpc_socp__CPG_Dual.d21[6] = mpc_socp__qoco_solver->sol->y[668];
  mpc_socp__CPG_Dual.d21[7] = mpc_socp__qoco_solver->sol->y[669];
  mpc_socp__CPG_Dual.d21[8] = mpc_socp__qoco_solver->sol->y[670];
  mpc_socp__CPG_Dual.d21[9] = mpc_socp__qoco_solver->sol->y[671];
  mpc_socp__CPG_Dual.d21[10] = mpc_socp__qoco_solver->sol->y[672];
  mpc_socp__CPG_Dual.d21[11] = mpc_socp__qoco_solver->sol->y[673];
  mpc_socp__CPG_Dual.d21[12] = mpc_socp__qoco_solver->sol->y[674];
  mpc_socp__CPG_Dual.d21[13] = mpc_socp__qoco_solver->sol->y[675];
  mpc_socp__CPG_Dual.d22 = mpc_socp__qoco_solver->sol->z[15];
  mpc_socp__CPG_Dual.d23 = mpc_socp__qoco_solver->sol->z[16];
  mpc_socp__CPG_Dual.d24 = mpc_socp__qoco_solver->sol->z[17];
  mpc_socp__CPG_Dual.d25[0] = mpc_socp__qoco_solver->sol->y[676];
  mpc_socp__CPG_Dual.d25[1] = mpc_socp__qoco_solver->sol->y[677];
  mpc_socp__CPG_Dual.d25[2] = mpc_socp__qoco_solver->sol->y[678];
  mpc_socp__CPG_Dual.d25[3] = mpc_socp__qoco_solver->sol->y[679];
  mpc_socp__CPG_Dual.d25[4] = mpc_socp__qoco_solver->sol->y[680];
  mpc_socp__CPG_Dual.d25[5] = mpc_socp__qoco_solver->sol->y[681];
  mpc_socp__CPG_Dual.d25[6] = mpc_socp__qoco_solver->sol->y[682];
  mpc_socp__CPG_Dual.d25[7] = mpc_socp__qoco_solver->sol->y[683];
  mpc_socp__CPG_Dual.d25[8] = mpc_socp__qoco_solver->sol->y[684];
  mpc_socp__CPG_Dual.d25[9] = mpc_socp__qoco_solver->sol->y[685];
  mpc_socp__CPG_Dual.d25[10] = mpc_socp__qoco_solver->sol->y[686];
  mpc_socp__CPG_Dual.d25[11] = mpc_socp__qoco_solver->sol->y[687];
  mpc_socp__CPG_Dual.d25[12] = mpc_socp__qoco_solver->sol->y[688];
  mpc_socp__CPG_Dual.d25[13] = mpc_socp__qoco_solver->sol->y[689];
  mpc_socp__CPG_Dual.d26 = mpc_socp__qoco_solver->sol->z[18];
  mpc_socp__CPG_Dual.d27 = mpc_socp__qoco_solver->sol->z[19];
  mpc_socp__CPG_Dual.d28 = mpc_socp__qoco_solver->sol->z[20];
  mpc_socp__CPG_Dual.d29[0] = mpc_socp__qoco_solver->sol->y[690];
  mpc_socp__CPG_Dual.d29[1] = mpc_socp__qoco_solver->sol->y[691];
  mpc_socp__CPG_Dual.d29[2] = mpc_socp__qoco_solver->sol->y[692];
  mpc_socp__CPG_Dual.d29[3] = mpc_socp__qoco_solver->sol->y[693];
  mpc_socp__CPG_Dual.d29[4] = mpc_socp__qoco_solver->sol->y[694];
  mpc_socp__CPG_Dual.d29[5] = mpc_socp__qoco_solver->sol->y[695];
  mpc_socp__CPG_Dual.d29[6] = mpc_socp__qoco_solver->sol->y[696];
  mpc_socp__CPG_Dual.d29[7] = mpc_socp__qoco_solver->sol->y[697];
  mpc_socp__CPG_Dual.d29[8] = mpc_socp__qoco_solver->sol->y[698];
  mpc_socp__CPG_Dual.d29[9] = mpc_socp__qoco_solver->sol->y[699];
  mpc_socp__CPG_Dual.d29[10] = mpc_socp__qoco_solver->sol->y[700];
  mpc_socp__CPG_Dual.d29[11] = mpc_socp__qoco_solver->sol->y[701];
  mpc_socp__CPG_Dual.d29[12] = mpc_socp__qoco_solver->sol->y[702];
  mpc_socp__CPG_Dual.d29[13] = mpc_socp__qoco_solver->sol->y[703];
  mpc_socp__CPG_Dual.d30 = mpc_socp__qoco_solver->sol->z[21];
  mpc_socp__CPG_Dual.d31 = mpc_socp__qoco_solver->sol->z[22];
  mpc_socp__CPG_Dual.d32 = mpc_socp__qoco_solver->sol->z[23];
  mpc_socp__CPG_Dual.d33[0] = mpc_socp__qoco_solver->sol->y[704];
  mpc_socp__CPG_Dual.d33[1] = mpc_socp__qoco_solver->sol->y[705];
  mpc_socp__CPG_Dual.d33[2] = mpc_socp__qoco_solver->sol->y[706];
  mpc_socp__CPG_Dual.d33[3] = mpc_socp__qoco_solver->sol->y[707];
  mpc_socp__CPG_Dual.d33[4] = mpc_socp__qoco_solver->sol->y[708];
  mpc_socp__CPG_Dual.d33[5] = mpc_socp__qoco_solver->sol->y[709];
  mpc_socp__CPG_Dual.d33[6] = mpc_socp__qoco_solver->sol->y[710];
  mpc_socp__CPG_Dual.d33[7] = mpc_socp__qoco_solver->sol->y[711];
  mpc_socp__CPG_Dual.d33[8] = mpc_socp__qoco_solver->sol->y[712];
  mpc_socp__CPG_Dual.d33[9] = mpc_socp__qoco_solver->sol->y[713];
  mpc_socp__CPG_Dual.d33[10] = mpc_socp__qoco_solver->sol->y[714];
  mpc_socp__CPG_Dual.d33[11] = mpc_socp__qoco_solver->sol->y[715];
  mpc_socp__CPG_Dual.d33[12] = mpc_socp__qoco_solver->sol->y[716];
  mpc_socp__CPG_Dual.d33[13] = mpc_socp__qoco_solver->sol->y[717];
  mpc_socp__CPG_Dual.d34 = mpc_socp__qoco_solver->sol->z[24];
  mpc_socp__CPG_Dual.d35 = mpc_socp__qoco_solver->sol->z[25];
  mpc_socp__CPG_Dual.d36 = mpc_socp__qoco_solver->sol->z[26];
  mpc_socp__CPG_Dual.d37[0] = mpc_socp__qoco_solver->sol->y[718];
  mpc_socp__CPG_Dual.d37[1] = mpc_socp__qoco_solver->sol->y[719];
  mpc_socp__CPG_Dual.d37[2] = mpc_socp__qoco_solver->sol->y[720];
  mpc_socp__CPG_Dual.d37[3] = mpc_socp__qoco_solver->sol->y[721];
  mpc_socp__CPG_Dual.d37[4] = mpc_socp__qoco_solver->sol->y[722];
  mpc_socp__CPG_Dual.d37[5] = mpc_socp__qoco_solver->sol->y[723];
  mpc_socp__CPG_Dual.d37[6] = mpc_socp__qoco_solver->sol->y[724];
  mpc_socp__CPG_Dual.d37[7] = mpc_socp__qoco_solver->sol->y[725];
  mpc_socp__CPG_Dual.d37[8] = mpc_socp__qoco_solver->sol->y[726];
  mpc_socp__CPG_Dual.d37[9] = mpc_socp__qoco_solver->sol->y[727];
  mpc_socp__CPG_Dual.d37[10] = mpc_socp__qoco_solver->sol->y[728];
  mpc_socp__CPG_Dual.d37[11] = mpc_socp__qoco_solver->sol->y[729];
  mpc_socp__CPG_Dual.d37[12] = mpc_socp__qoco_solver->sol->y[730];
  mpc_socp__CPG_Dual.d37[13] = mpc_socp__qoco_solver->sol->y[731];
  mpc_socp__CPG_Dual.d38 = mpc_socp__qoco_solver->sol->z[27];
  mpc_socp__CPG_Dual.d39 = mpc_socp__qoco_solver->sol->z[28];
  mpc_socp__CPG_Dual.d40 = mpc_socp__qoco_solver->sol->z[29];
  mpc_socp__CPG_Dual.d41[0] = mpc_socp__qoco_solver->sol->y[732];
  mpc_socp__CPG_Dual.d41[1] = mpc_socp__qoco_solver->sol->y[733];
  mpc_socp__CPG_Dual.d41[2] = mpc_socp__qoco_solver->sol->y[734];
  mpc_socp__CPG_Dual.d41[3] = mpc_socp__qoco_solver->sol->y[735];
  mpc_socp__CPG_Dual.d41[4] = mpc_socp__qoco_solver->sol->y[736];
  mpc_socp__CPG_Dual.d41[5] = mpc_socp__qoco_solver->sol->y[737];
  mpc_socp__CPG_Dual.d41[6] = mpc_socp__qoco_solver->sol->y[738];
  mpc_socp__CPG_Dual.d41[7] = mpc_socp__qoco_solver->sol->y[739];
  mpc_socp__CPG_Dual.d41[8] = mpc_socp__qoco_solver->sol->y[740];
  mpc_socp__CPG_Dual.d41[9] = mpc_socp__qoco_solver->sol->y[741];
  mpc_socp__CPG_Dual.d41[10] = mpc_socp__qoco_solver->sol->y[742];
  mpc_socp__CPG_Dual.d41[11] = mpc_socp__qoco_solver->sol->y[743];
  mpc_socp__CPG_Dual.d41[12] = mpc_socp__qoco_solver->sol->y[744];
  mpc_socp__CPG_Dual.d41[13] = mpc_socp__qoco_solver->sol->y[745];
  mpc_socp__CPG_Dual.d42 = mpc_socp__qoco_solver->sol->z[30];
  mpc_socp__CPG_Dual.d43 = mpc_socp__qoco_solver->sol->z[31];
  mpc_socp__CPG_Dual.d44 = mpc_socp__qoco_solver->sol->z[32];
  mpc_socp__CPG_Dual.d45[0] = mpc_socp__qoco_solver->sol->y[746];
  mpc_socp__CPG_Dual.d45[1] = mpc_socp__qoco_solver->sol->y[747];
  mpc_socp__CPG_Dual.d45[2] = mpc_socp__qoco_solver->sol->y[748];
  mpc_socp__CPG_Dual.d45[3] = mpc_socp__qoco_solver->sol->y[749];
  mpc_socp__CPG_Dual.d45[4] = mpc_socp__qoco_solver->sol->y[750];
  mpc_socp__CPG_Dual.d45[5] = mpc_socp__qoco_solver->sol->y[751];
  mpc_socp__CPG_Dual.d45[6] = mpc_socp__qoco_solver->sol->y[752];
  mpc_socp__CPG_Dual.d45[7] = mpc_socp__qoco_solver->sol->y[753];
  mpc_socp__CPG_Dual.d45[8] = mpc_socp__qoco_solver->sol->y[754];
  mpc_socp__CPG_Dual.d45[9] = mpc_socp__qoco_solver->sol->y[755];
  mpc_socp__CPG_Dual.d45[10] = mpc_socp__qoco_solver->sol->y[756];
  mpc_socp__CPG_Dual.d45[11] = mpc_socp__qoco_solver->sol->y[757];
  mpc_socp__CPG_Dual.d45[12] = mpc_socp__qoco_solver->sol->y[758];
  mpc_socp__CPG_Dual.d45[13] = mpc_socp__qoco_solver->sol->y[759];
  mpc_socp__CPG_Dual.d46 = mpc_socp__qoco_solver->sol->z[33];
  mpc_socp__CPG_Dual.d47 = mpc_socp__qoco_solver->sol->z[34];
  mpc_socp__CPG_Dual.d48 = mpc_socp__qoco_solver->sol->z[35];
  mpc_socp__CPG_Dual.d49[0] = mpc_socp__qoco_solver->sol->y[760];
  mpc_socp__CPG_Dual.d49[1] = mpc_socp__qoco_solver->sol->y[761];
  mpc_socp__CPG_Dual.d49[2] = mpc_socp__qoco_solver->sol->y[762];
  mpc_socp__CPG_Dual.d49[3] = mpc_socp__qoco_solver->sol->y[763];
  mpc_socp__CPG_Dual.d49[4] = mpc_socp__qoco_solver->sol->y[764];
  mpc_socp__CPG_Dual.d49[5] = mpc_socp__qoco_solver->sol->y[765];
  mpc_socp__CPG_Dual.d49[6] = mpc_socp__qoco_solver->sol->y[766];
  mpc_socp__CPG_Dual.d49[7] = mpc_socp__qoco_solver->sol->y[767];
  mpc_socp__CPG_Dual.d49[8] = mpc_socp__qoco_solver->sol->y[768];
  mpc_socp__CPG_Dual.d49[9] = mpc_socp__qoco_solver->sol->y[769];
  mpc_socp__CPG_Dual.d49[10] = mpc_socp__qoco_solver->sol->y[770];
  mpc_socp__CPG_Dual.d49[11] = mpc_socp__qoco_solver->sol->y[771];
  mpc_socp__CPG_Dual.d49[12] = mpc_socp__qoco_solver->sol->y[772];
  mpc_socp__CPG_Dual.d49[13] = mpc_socp__qoco_solver->sol->y[773];
  mpc_socp__CPG_Dual.d50 = mpc_socp__qoco_solver->sol->z[36];
  mpc_socp__CPG_Dual.d51 = mpc_socp__qoco_solver->sol->z[37];
  mpc_socp__CPG_Dual.d52 = mpc_socp__qoco_solver->sol->z[38];
  mpc_socp__CPG_Dual.d53[0] = mpc_socp__qoco_solver->sol->y[774];
  mpc_socp__CPG_Dual.d53[1] = mpc_socp__qoco_solver->sol->y[775];
  mpc_socp__CPG_Dual.d53[2] = mpc_socp__qoco_solver->sol->y[776];
  mpc_socp__CPG_Dual.d53[3] = mpc_socp__qoco_solver->sol->y[777];
  mpc_socp__CPG_Dual.d53[4] = mpc_socp__qoco_solver->sol->y[778];
  mpc_socp__CPG_Dual.d53[5] = mpc_socp__qoco_solver->sol->y[779];
  mpc_socp__CPG_Dual.d53[6] = mpc_socp__qoco_solver->sol->y[780];
  mpc_socp__CPG_Dual.d53[7] = mpc_socp__qoco_solver->sol->y[781];
  mpc_socp__CPG_Dual.d53[8] = mpc_socp__qoco_solver->sol->y[782];
  mpc_socp__CPG_Dual.d53[9] = mpc_socp__qoco_solver->sol->y[783];
  mpc_socp__CPG_Dual.d53[10] = mpc_socp__qoco_solver->sol->y[784];
  mpc_socp__CPG_Dual.d53[11] = mpc_socp__qoco_solver->sol->y[785];
  mpc_socp__CPG_Dual.d53[12] = mpc_socp__qoco_solver->sol->y[786];
  mpc_socp__CPG_Dual.d53[13] = mpc_socp__qoco_solver->sol->y[787];
  mpc_socp__CPG_Dual.d54 = mpc_socp__qoco_solver->sol->z[39];
  mpc_socp__CPG_Dual.d55 = mpc_socp__qoco_solver->sol->z[40];
  mpc_socp__CPG_Dual.d56 = mpc_socp__qoco_solver->sol->z[41];
  mpc_socp__CPG_Dual.d57[0] = mpc_socp__qoco_solver->sol->y[788];
  mpc_socp__CPG_Dual.d57[1] = mpc_socp__qoco_solver->sol->y[789];
  mpc_socp__CPG_Dual.d57[2] = mpc_socp__qoco_solver->sol->y[790];
  mpc_socp__CPG_Dual.d57[3] = mpc_socp__qoco_solver->sol->y[791];
  mpc_socp__CPG_Dual.d57[4] = mpc_socp__qoco_solver->sol->y[792];
  mpc_socp__CPG_Dual.d57[5] = mpc_socp__qoco_solver->sol->y[793];
  mpc_socp__CPG_Dual.d57[6] = mpc_socp__qoco_solver->sol->y[794];
  mpc_socp__CPG_Dual.d57[7] = mpc_socp__qoco_solver->sol->y[795];
  mpc_socp__CPG_Dual.d57[8] = mpc_socp__qoco_solver->sol->y[796];
  mpc_socp__CPG_Dual.d57[9] = mpc_socp__qoco_solver->sol->y[797];
  mpc_socp__CPG_Dual.d57[10] = mpc_socp__qoco_solver->sol->y[798];
  mpc_socp__CPG_Dual.d57[11] = mpc_socp__qoco_solver->sol->y[799];
  mpc_socp__CPG_Dual.d57[12] = mpc_socp__qoco_solver->sol->y[800];
  mpc_socp__CPG_Dual.d57[13] = mpc_socp__qoco_solver->sol->y[801];
  mpc_socp__CPG_Dual.d58 = mpc_socp__qoco_solver->sol->z[42];
  mpc_socp__CPG_Dual.d59 = mpc_socp__qoco_solver->sol->z[43];
  mpc_socp__CPG_Dual.d60 = mpc_socp__qoco_solver->sol->z[44];
  mpc_socp__CPG_Dual.d61[0] = mpc_socp__qoco_solver->sol->y[802];
  mpc_socp__CPG_Dual.d61[1] = mpc_socp__qoco_solver->sol->y[803];
  mpc_socp__CPG_Dual.d61[2] = mpc_socp__qoco_solver->sol->y[804];
  mpc_socp__CPG_Dual.d61[3] = mpc_socp__qoco_solver->sol->y[805];
  mpc_socp__CPG_Dual.d61[4] = mpc_socp__qoco_solver->sol->y[806];
  mpc_socp__CPG_Dual.d61[5] = mpc_socp__qoco_solver->sol->y[807];
  mpc_socp__CPG_Dual.d61[6] = mpc_socp__qoco_solver->sol->y[808];
  mpc_socp__CPG_Dual.d61[7] = mpc_socp__qoco_solver->sol->y[809];
  mpc_socp__CPG_Dual.d61[8] = mpc_socp__qoco_solver->sol->y[810];
  mpc_socp__CPG_Dual.d61[9] = mpc_socp__qoco_solver->sol->y[811];
  mpc_socp__CPG_Dual.d61[10] = mpc_socp__qoco_solver->sol->y[812];
  mpc_socp__CPG_Dual.d61[11] = mpc_socp__qoco_solver->sol->y[813];
  mpc_socp__CPG_Dual.d61[12] = mpc_socp__qoco_solver->sol->y[814];
  mpc_socp__CPG_Dual.d61[13] = mpc_socp__qoco_solver->sol->y[815];
  mpc_socp__CPG_Dual.d62 = mpc_socp__qoco_solver->sol->z[45];
  mpc_socp__CPG_Dual.d63 = mpc_socp__qoco_solver->sol->z[46];
  mpc_socp__CPG_Dual.d64 = mpc_socp__qoco_solver->sol->z[47];
  mpc_socp__CPG_Dual.d65[0] = mpc_socp__qoco_solver->sol->y[816];
  mpc_socp__CPG_Dual.d65[1] = mpc_socp__qoco_solver->sol->y[817];
  mpc_socp__CPG_Dual.d65[2] = mpc_socp__qoco_solver->sol->y[818];
  mpc_socp__CPG_Dual.d65[3] = mpc_socp__qoco_solver->sol->y[819];
  mpc_socp__CPG_Dual.d65[4] = mpc_socp__qoco_solver->sol->y[820];
  mpc_socp__CPG_Dual.d65[5] = mpc_socp__qoco_solver->sol->y[821];
  mpc_socp__CPG_Dual.d65[6] = mpc_socp__qoco_solver->sol->y[822];
  mpc_socp__CPG_Dual.d65[7] = mpc_socp__qoco_solver->sol->y[823];
  mpc_socp__CPG_Dual.d65[8] = mpc_socp__qoco_solver->sol->y[824];
  mpc_socp__CPG_Dual.d65[9] = mpc_socp__qoco_solver->sol->y[825];
  mpc_socp__CPG_Dual.d65[10] = mpc_socp__qoco_solver->sol->y[826];
  mpc_socp__CPG_Dual.d65[11] = mpc_socp__qoco_solver->sol->y[827];
  mpc_socp__CPG_Dual.d65[12] = mpc_socp__qoco_solver->sol->y[828];
  mpc_socp__CPG_Dual.d65[13] = mpc_socp__qoco_solver->sol->y[829];
  mpc_socp__CPG_Dual.d66 = mpc_socp__qoco_solver->sol->z[48];
  mpc_socp__CPG_Dual.d67 = mpc_socp__qoco_solver->sol->z[49];
  mpc_socp__CPG_Dual.d68 = mpc_socp__qoco_solver->sol->z[50];
  mpc_socp__CPG_Dual.d69[0] = mpc_socp__qoco_solver->sol->y[830];
  mpc_socp__CPG_Dual.d69[1] = mpc_socp__qoco_solver->sol->y[831];
  mpc_socp__CPG_Dual.d69[2] = mpc_socp__qoco_solver->sol->y[832];
  mpc_socp__CPG_Dual.d69[3] = mpc_socp__qoco_solver->sol->y[833];
  mpc_socp__CPG_Dual.d69[4] = mpc_socp__qoco_solver->sol->y[834];
  mpc_socp__CPG_Dual.d69[5] = mpc_socp__qoco_solver->sol->y[835];
  mpc_socp__CPG_Dual.d69[6] = mpc_socp__qoco_solver->sol->y[836];
  mpc_socp__CPG_Dual.d69[7] = mpc_socp__qoco_solver->sol->y[837];
  mpc_socp__CPG_Dual.d69[8] = mpc_socp__qoco_solver->sol->y[838];
  mpc_socp__CPG_Dual.d69[9] = mpc_socp__qoco_solver->sol->y[839];
  mpc_socp__CPG_Dual.d69[10] = mpc_socp__qoco_solver->sol->y[840];
  mpc_socp__CPG_Dual.d69[11] = mpc_socp__qoco_solver->sol->y[841];
  mpc_socp__CPG_Dual.d69[12] = mpc_socp__qoco_solver->sol->y[842];
  mpc_socp__CPG_Dual.d69[13] = mpc_socp__qoco_solver->sol->y[843];
  mpc_socp__CPG_Dual.d70 = mpc_socp__qoco_solver->sol->z[51];
  mpc_socp__CPG_Dual.d71 = mpc_socp__qoco_solver->sol->z[52];
  mpc_socp__CPG_Dual.d72 = mpc_socp__qoco_solver->sol->z[53];
  mpc_socp__CPG_Dual.d73[0] = mpc_socp__qoco_solver->sol->y[844];
  mpc_socp__CPG_Dual.d73[1] = mpc_socp__qoco_solver->sol->y[845];
  mpc_socp__CPG_Dual.d73[2] = mpc_socp__qoco_solver->sol->y[846];
  mpc_socp__CPG_Dual.d73[3] = mpc_socp__qoco_solver->sol->y[847];
  mpc_socp__CPG_Dual.d73[4] = mpc_socp__qoco_solver->sol->y[848];
  mpc_socp__CPG_Dual.d73[5] = mpc_socp__qoco_solver->sol->y[849];
  mpc_socp__CPG_Dual.d73[6] = mpc_socp__qoco_solver->sol->y[850];
  mpc_socp__CPG_Dual.d73[7] = mpc_socp__qoco_solver->sol->y[851];
  mpc_socp__CPG_Dual.d73[8] = mpc_socp__qoco_solver->sol->y[852];
  mpc_socp__CPG_Dual.d73[9] = mpc_socp__qoco_solver->sol->y[853];
  mpc_socp__CPG_Dual.d73[10] = mpc_socp__qoco_solver->sol->y[854];
  mpc_socp__CPG_Dual.d73[11] = mpc_socp__qoco_solver->sol->y[855];
  mpc_socp__CPG_Dual.d73[12] = mpc_socp__qoco_solver->sol->y[856];
  mpc_socp__CPG_Dual.d73[13] = mpc_socp__qoco_solver->sol->y[857];
  mpc_socp__CPG_Dual.d74 = mpc_socp__qoco_solver->sol->z[54];
  mpc_socp__CPG_Dual.d75 = mpc_socp__qoco_solver->sol->z[55];
  mpc_socp__CPG_Dual.d76 = mpc_socp__qoco_solver->sol->z[56];
  mpc_socp__CPG_Dual.d77[0] = mpc_socp__qoco_solver->sol->y[858];
  mpc_socp__CPG_Dual.d77[1] = mpc_socp__qoco_solver->sol->y[859];
  mpc_socp__CPG_Dual.d77[2] = mpc_socp__qoco_solver->sol->y[860];
  mpc_socp__CPG_Dual.d77[3] = mpc_socp__qoco_solver->sol->y[861];
  mpc_socp__CPG_Dual.d77[4] = mpc_socp__qoco_solver->sol->y[862];
  mpc_socp__CPG_Dual.d77[5] = mpc_socp__qoco_solver->sol->y[863];
  mpc_socp__CPG_Dual.d77[6] = mpc_socp__qoco_solver->sol->y[864];
  mpc_socp__CPG_Dual.d77[7] = mpc_socp__qoco_solver->sol->y[865];
  mpc_socp__CPG_Dual.d77[8] = mpc_socp__qoco_solver->sol->y[866];
  mpc_socp__CPG_Dual.d77[9] = mpc_socp__qoco_solver->sol->y[867];
  mpc_socp__CPG_Dual.d77[10] = mpc_socp__qoco_solver->sol->y[868];
  mpc_socp__CPG_Dual.d77[11] = mpc_socp__qoco_solver->sol->y[869];
  mpc_socp__CPG_Dual.d77[12] = mpc_socp__qoco_solver->sol->y[870];
  mpc_socp__CPG_Dual.d77[13] = mpc_socp__qoco_solver->sol->y[871];
  mpc_socp__CPG_Dual.d78 = mpc_socp__qoco_solver->sol->z[57];
  mpc_socp__CPG_Dual.d79 = mpc_socp__qoco_solver->sol->z[58];
  mpc_socp__CPG_Dual.d80 = mpc_socp__qoco_solver->sol->z[59];
  mpc_socp__CPG_Dual.d81[0] = mpc_socp__qoco_solver->sol->y[872];
  mpc_socp__CPG_Dual.d81[1] = mpc_socp__qoco_solver->sol->y[873];
  mpc_socp__CPG_Dual.d81[2] = mpc_socp__qoco_solver->sol->y[874];
  mpc_socp__CPG_Dual.d81[3] = mpc_socp__qoco_solver->sol->y[875];
  mpc_socp__CPG_Dual.d81[4] = mpc_socp__qoco_solver->sol->y[876];
  mpc_socp__CPG_Dual.d81[5] = mpc_socp__qoco_solver->sol->y[877];
  mpc_socp__CPG_Dual.d81[6] = mpc_socp__qoco_solver->sol->y[878];
  mpc_socp__CPG_Dual.d81[7] = mpc_socp__qoco_solver->sol->y[879];
  mpc_socp__CPG_Dual.d81[8] = mpc_socp__qoco_solver->sol->y[880];
  mpc_socp__CPG_Dual.d81[9] = mpc_socp__qoco_solver->sol->y[881];
  mpc_socp__CPG_Dual.d81[10] = mpc_socp__qoco_solver->sol->y[882];
  mpc_socp__CPG_Dual.d81[11] = mpc_socp__qoco_solver->sol->y[883];
  mpc_socp__CPG_Dual.d81[12] = mpc_socp__qoco_solver->sol->y[884];
  mpc_socp__CPG_Dual.d81[13] = mpc_socp__qoco_solver->sol->y[885];
  mpc_socp__CPG_Dual.d82 = mpc_socp__qoco_solver->sol->z[60];
  mpc_socp__CPG_Dual.d83 = mpc_socp__qoco_solver->sol->z[61];
  mpc_socp__CPG_Dual.d84 = mpc_socp__qoco_solver->sol->z[62];
  mpc_socp__CPG_Dual.d85[0] = mpc_socp__qoco_solver->sol->y[886];
  mpc_socp__CPG_Dual.d85[1] = mpc_socp__qoco_solver->sol->y[887];
  mpc_socp__CPG_Dual.d85[2] = mpc_socp__qoco_solver->sol->y[888];
  mpc_socp__CPG_Dual.d85[3] = mpc_socp__qoco_solver->sol->y[889];
  mpc_socp__CPG_Dual.d85[4] = mpc_socp__qoco_solver->sol->y[890];
  mpc_socp__CPG_Dual.d85[5] = mpc_socp__qoco_solver->sol->y[891];
  mpc_socp__CPG_Dual.d85[6] = mpc_socp__qoco_solver->sol->y[892];
  mpc_socp__CPG_Dual.d85[7] = mpc_socp__qoco_solver->sol->y[893];
  mpc_socp__CPG_Dual.d85[8] = mpc_socp__qoco_solver->sol->y[894];
  mpc_socp__CPG_Dual.d85[9] = mpc_socp__qoco_solver->sol->y[895];
  mpc_socp__CPG_Dual.d85[10] = mpc_socp__qoco_solver->sol->y[896];
  mpc_socp__CPG_Dual.d85[11] = mpc_socp__qoco_solver->sol->y[897];
  mpc_socp__CPG_Dual.d85[12] = mpc_socp__qoco_solver->sol->y[898];
  mpc_socp__CPG_Dual.d85[13] = mpc_socp__qoco_solver->sol->y[899];
  mpc_socp__CPG_Dual.d86 = mpc_socp__qoco_solver->sol->z[63];
  mpc_socp__CPG_Dual.d87 = mpc_socp__qoco_solver->sol->z[64];
  mpc_socp__CPG_Dual.d88 = mpc_socp__qoco_solver->sol->z[65];
  mpc_socp__CPG_Dual.d89[0] = mpc_socp__qoco_solver->sol->y[900];
  mpc_socp__CPG_Dual.d89[1] = mpc_socp__qoco_solver->sol->y[901];
  mpc_socp__CPG_Dual.d89[2] = mpc_socp__qoco_solver->sol->y[902];
  mpc_socp__CPG_Dual.d89[3] = mpc_socp__qoco_solver->sol->y[903];
  mpc_socp__CPG_Dual.d89[4] = mpc_socp__qoco_solver->sol->y[904];
  mpc_socp__CPG_Dual.d89[5] = mpc_socp__qoco_solver->sol->y[905];
  mpc_socp__CPG_Dual.d89[6] = mpc_socp__qoco_solver->sol->y[906];
  mpc_socp__CPG_Dual.d89[7] = mpc_socp__qoco_solver->sol->y[907];
  mpc_socp__CPG_Dual.d89[8] = mpc_socp__qoco_solver->sol->y[908];
  mpc_socp__CPG_Dual.d89[9] = mpc_socp__qoco_solver->sol->y[909];
  mpc_socp__CPG_Dual.d89[10] = mpc_socp__qoco_solver->sol->y[910];
  mpc_socp__CPG_Dual.d89[11] = mpc_socp__qoco_solver->sol->y[911];
  mpc_socp__CPG_Dual.d89[12] = mpc_socp__qoco_solver->sol->y[912];
  mpc_socp__CPG_Dual.d89[13] = mpc_socp__qoco_solver->sol->y[913];
  mpc_socp__CPG_Dual.d90 = mpc_socp__qoco_solver->sol->z[66];
  mpc_socp__CPG_Dual.d91 = mpc_socp__qoco_solver->sol->z[67];
  mpc_socp__CPG_Dual.d92 = mpc_socp__qoco_solver->sol->z[68];
  mpc_socp__CPG_Dual.d93[0] = mpc_socp__qoco_solver->sol->y[914];
  mpc_socp__CPG_Dual.d93[1] = mpc_socp__qoco_solver->sol->y[915];
  mpc_socp__CPG_Dual.d93[2] = mpc_socp__qoco_solver->sol->y[916];
  mpc_socp__CPG_Dual.d93[3] = mpc_socp__qoco_solver->sol->y[917];
  mpc_socp__CPG_Dual.d93[4] = mpc_socp__qoco_solver->sol->y[918];
  mpc_socp__CPG_Dual.d93[5] = mpc_socp__qoco_solver->sol->y[919];
  mpc_socp__CPG_Dual.d93[6] = mpc_socp__qoco_solver->sol->y[920];
  mpc_socp__CPG_Dual.d93[7] = mpc_socp__qoco_solver->sol->y[921];
  mpc_socp__CPG_Dual.d93[8] = mpc_socp__qoco_solver->sol->y[922];
  mpc_socp__CPG_Dual.d93[9] = mpc_socp__qoco_solver->sol->y[923];
  mpc_socp__CPG_Dual.d93[10] = mpc_socp__qoco_solver->sol->y[924];
  mpc_socp__CPG_Dual.d93[11] = mpc_socp__qoco_solver->sol->y[925];
  mpc_socp__CPG_Dual.d93[12] = mpc_socp__qoco_solver->sol->y[926];
  mpc_socp__CPG_Dual.d93[13] = mpc_socp__qoco_solver->sol->y[927];
  mpc_socp__CPG_Dual.d94 = mpc_socp__qoco_solver->sol->z[69];
  mpc_socp__CPG_Dual.d95 = mpc_socp__qoco_solver->sol->z[70];
  mpc_socp__CPG_Dual.d96 = mpc_socp__qoco_solver->sol->z[71];
  mpc_socp__CPG_Dual.d97[0] = mpc_socp__qoco_solver->sol->y[928];
  mpc_socp__CPG_Dual.d97[1] = mpc_socp__qoco_solver->sol->y[929];
  mpc_socp__CPG_Dual.d97[2] = mpc_socp__qoco_solver->sol->y[930];
  mpc_socp__CPG_Dual.d97[3] = mpc_socp__qoco_solver->sol->y[931];
  mpc_socp__CPG_Dual.d97[4] = mpc_socp__qoco_solver->sol->y[932];
  mpc_socp__CPG_Dual.d97[5] = mpc_socp__qoco_solver->sol->y[933];
  mpc_socp__CPG_Dual.d97[6] = mpc_socp__qoco_solver->sol->y[934];
  mpc_socp__CPG_Dual.d97[7] = mpc_socp__qoco_solver->sol->y[935];
  mpc_socp__CPG_Dual.d97[8] = mpc_socp__qoco_solver->sol->y[936];
  mpc_socp__CPG_Dual.d97[9] = mpc_socp__qoco_solver->sol->y[937];
  mpc_socp__CPG_Dual.d97[10] = mpc_socp__qoco_solver->sol->y[938];
  mpc_socp__CPG_Dual.d97[11] = mpc_socp__qoco_solver->sol->y[939];
  mpc_socp__CPG_Dual.d97[12] = mpc_socp__qoco_solver->sol->y[940];
  mpc_socp__CPG_Dual.d97[13] = mpc_socp__qoco_solver->sol->y[941];
  mpc_socp__CPG_Dual.d98 = mpc_socp__qoco_solver->sol->z[72];
  mpc_socp__CPG_Dual.d99 = mpc_socp__qoco_solver->sol->z[73];
  mpc_socp__CPG_Dual.d100 = mpc_socp__qoco_solver->sol->z[74];
  mpc_socp__CPG_Dual.d101[0] = mpc_socp__qoco_solver->sol->y[942];
  mpc_socp__CPG_Dual.d101[1] = mpc_socp__qoco_solver->sol->y[943];
  mpc_socp__CPG_Dual.d101[2] = mpc_socp__qoco_solver->sol->y[944];
  mpc_socp__CPG_Dual.d101[3] = mpc_socp__qoco_solver->sol->y[945];
  mpc_socp__CPG_Dual.d101[4] = mpc_socp__qoco_solver->sol->y[946];
  mpc_socp__CPG_Dual.d101[5] = mpc_socp__qoco_solver->sol->y[947];
  mpc_socp__CPG_Dual.d101[6] = mpc_socp__qoco_solver->sol->y[948];
  mpc_socp__CPG_Dual.d101[7] = mpc_socp__qoco_solver->sol->y[949];
  mpc_socp__CPG_Dual.d101[8] = mpc_socp__qoco_solver->sol->y[950];
  mpc_socp__CPG_Dual.d101[9] = mpc_socp__qoco_solver->sol->y[951];
  mpc_socp__CPG_Dual.d101[10] = mpc_socp__qoco_solver->sol->y[952];
  mpc_socp__CPG_Dual.d101[11] = mpc_socp__qoco_solver->sol->y[953];
  mpc_socp__CPG_Dual.d101[12] = mpc_socp__qoco_solver->sol->y[954];
  mpc_socp__CPG_Dual.d101[13] = mpc_socp__qoco_solver->sol->y[955];
  mpc_socp__CPG_Dual.d102 = mpc_socp__qoco_solver->sol->z[75];
  mpc_socp__CPG_Dual.d103 = mpc_socp__qoco_solver->sol->z[76];
  mpc_socp__CPG_Dual.d104 = mpc_socp__qoco_solver->sol->z[77];
  mpc_socp__CPG_Dual.d105[0] = mpc_socp__qoco_solver->sol->y[956];
  mpc_socp__CPG_Dual.d105[1] = mpc_socp__qoco_solver->sol->y[957];
  mpc_socp__CPG_Dual.d105[2] = mpc_socp__qoco_solver->sol->y[958];
  mpc_socp__CPG_Dual.d105[3] = mpc_socp__qoco_solver->sol->y[959];
  mpc_socp__CPG_Dual.d105[4] = mpc_socp__qoco_solver->sol->y[960];
  mpc_socp__CPG_Dual.d105[5] = mpc_socp__qoco_solver->sol->y[961];
  mpc_socp__CPG_Dual.d105[6] = mpc_socp__qoco_solver->sol->y[962];
  mpc_socp__CPG_Dual.d105[7] = mpc_socp__qoco_solver->sol->y[963];
  mpc_socp__CPG_Dual.d105[8] = mpc_socp__qoco_solver->sol->y[964];
  mpc_socp__CPG_Dual.d105[9] = mpc_socp__qoco_solver->sol->y[965];
  mpc_socp__CPG_Dual.d105[10] = mpc_socp__qoco_solver->sol->y[966];
  mpc_socp__CPG_Dual.d105[11] = mpc_socp__qoco_solver->sol->y[967];
  mpc_socp__CPG_Dual.d105[12] = mpc_socp__qoco_solver->sol->y[968];
  mpc_socp__CPG_Dual.d105[13] = mpc_socp__qoco_solver->sol->y[969];
  mpc_socp__CPG_Dual.d106 = mpc_socp__qoco_solver->sol->z[78];
  mpc_socp__CPG_Dual.d107 = mpc_socp__qoco_solver->sol->z[79];
  mpc_socp__CPG_Dual.d108 = mpc_socp__qoco_solver->sol->z[80];
  mpc_socp__CPG_Dual.d109[0] = mpc_socp__qoco_solver->sol->y[970];
  mpc_socp__CPG_Dual.d109[1] = mpc_socp__qoco_solver->sol->y[971];
  mpc_socp__CPG_Dual.d109[2] = mpc_socp__qoco_solver->sol->y[972];
  mpc_socp__CPG_Dual.d109[3] = mpc_socp__qoco_solver->sol->y[973];
  mpc_socp__CPG_Dual.d109[4] = mpc_socp__qoco_solver->sol->y[974];
  mpc_socp__CPG_Dual.d109[5] = mpc_socp__qoco_solver->sol->y[975];
  mpc_socp__CPG_Dual.d109[6] = mpc_socp__qoco_solver->sol->y[976];
  mpc_socp__CPG_Dual.d109[7] = mpc_socp__qoco_solver->sol->y[977];
  mpc_socp__CPG_Dual.d109[8] = mpc_socp__qoco_solver->sol->y[978];
  mpc_socp__CPG_Dual.d109[9] = mpc_socp__qoco_solver->sol->y[979];
  mpc_socp__CPG_Dual.d109[10] = mpc_socp__qoco_solver->sol->y[980];
  mpc_socp__CPG_Dual.d109[11] = mpc_socp__qoco_solver->sol->y[981];
  mpc_socp__CPG_Dual.d109[12] = mpc_socp__qoco_solver->sol->y[982];
  mpc_socp__CPG_Dual.d109[13] = mpc_socp__qoco_solver->sol->y[983];
  mpc_socp__CPG_Dual.d110 = mpc_socp__qoco_solver->sol->z[81];
  mpc_socp__CPG_Dual.d111 = mpc_socp__qoco_solver->sol->z[82];
  mpc_socp__CPG_Dual.d112 = mpc_socp__qoco_solver->sol->z[83];
  mpc_socp__CPG_Dual.d113[0] = mpc_socp__qoco_solver->sol->y[984];
  mpc_socp__CPG_Dual.d113[1] = mpc_socp__qoco_solver->sol->y[985];
  mpc_socp__CPG_Dual.d113[2] = mpc_socp__qoco_solver->sol->y[986];
  mpc_socp__CPG_Dual.d113[3] = mpc_socp__qoco_solver->sol->y[987];
  mpc_socp__CPG_Dual.d113[4] = mpc_socp__qoco_solver->sol->y[988];
  mpc_socp__CPG_Dual.d113[5] = mpc_socp__qoco_solver->sol->y[989];
  mpc_socp__CPG_Dual.d113[6] = mpc_socp__qoco_solver->sol->y[990];
  mpc_socp__CPG_Dual.d113[7] = mpc_socp__qoco_solver->sol->y[991];
  mpc_socp__CPG_Dual.d113[8] = mpc_socp__qoco_solver->sol->y[992];
  mpc_socp__CPG_Dual.d113[9] = mpc_socp__qoco_solver->sol->y[993];
  mpc_socp__CPG_Dual.d113[10] = mpc_socp__qoco_solver->sol->y[994];
  mpc_socp__CPG_Dual.d113[11] = mpc_socp__qoco_solver->sol->y[995];
  mpc_socp__CPG_Dual.d113[12] = mpc_socp__qoco_solver->sol->y[996];
  mpc_socp__CPG_Dual.d113[13] = mpc_socp__qoco_solver->sol->y[997];
  mpc_socp__CPG_Dual.d114 = mpc_socp__qoco_solver->sol->z[84];
  mpc_socp__CPG_Dual.d115 = mpc_socp__qoco_solver->sol->z[85];
  mpc_socp__CPG_Dual.d116 = mpc_socp__qoco_solver->sol->z[86];
  mpc_socp__CPG_Dual.d117[0] = mpc_socp__qoco_solver->sol->y[998];
  mpc_socp__CPG_Dual.d117[1] = mpc_socp__qoco_solver->sol->y[999];
  mpc_socp__CPG_Dual.d117[2] = mpc_socp__qoco_solver->sol->y[1000];
  mpc_socp__CPG_Dual.d117[3] = mpc_socp__qoco_solver->sol->y[1001];
  mpc_socp__CPG_Dual.d117[4] = mpc_socp__qoco_solver->sol->y[1002];
  mpc_socp__CPG_Dual.d117[5] = mpc_socp__qoco_solver->sol->y[1003];
  mpc_socp__CPG_Dual.d117[6] = mpc_socp__qoco_solver->sol->y[1004];
  mpc_socp__CPG_Dual.d117[7] = mpc_socp__qoco_solver->sol->y[1005];
  mpc_socp__CPG_Dual.d117[8] = mpc_socp__qoco_solver->sol->y[1006];
  mpc_socp__CPG_Dual.d117[9] = mpc_socp__qoco_solver->sol->y[1007];
  mpc_socp__CPG_Dual.d117[10] = mpc_socp__qoco_solver->sol->y[1008];
  mpc_socp__CPG_Dual.d117[11] = mpc_socp__qoco_solver->sol->y[1009];
  mpc_socp__CPG_Dual.d117[12] = mpc_socp__qoco_solver->sol->y[1010];
  mpc_socp__CPG_Dual.d117[13] = mpc_socp__qoco_solver->sol->y[1011];
  mpc_socp__CPG_Dual.d118 = mpc_socp__qoco_solver->sol->z[87];
  mpc_socp__CPG_Dual.d119 = mpc_socp__qoco_solver->sol->z[88];
  mpc_socp__CPG_Dual.d120 = mpc_socp__qoco_solver->sol->z[89];
  mpc_socp__CPG_Dual.d121[0] = mpc_socp__qoco_solver->sol->y[1012];
  mpc_socp__CPG_Dual.d121[1] = mpc_socp__qoco_solver->sol->y[1013];
  mpc_socp__CPG_Dual.d121[2] = mpc_socp__qoco_solver->sol->y[1014];
  mpc_socp__CPG_Dual.d121[3] = mpc_socp__qoco_solver->sol->y[1015];
  mpc_socp__CPG_Dual.d121[4] = mpc_socp__qoco_solver->sol->y[1016];
  mpc_socp__CPG_Dual.d121[5] = mpc_socp__qoco_solver->sol->y[1017];
  mpc_socp__CPG_Dual.d121[6] = mpc_socp__qoco_solver->sol->y[1018];
  mpc_socp__CPG_Dual.d121[7] = mpc_socp__qoco_solver->sol->y[1019];
  mpc_socp__CPG_Dual.d121[8] = mpc_socp__qoco_solver->sol->y[1020];
  mpc_socp__CPG_Dual.d121[9] = mpc_socp__qoco_solver->sol->y[1021];
  mpc_socp__CPG_Dual.d121[10] = mpc_socp__qoco_solver->sol->y[1022];
  mpc_socp__CPG_Dual.d121[11] = mpc_socp__qoco_solver->sol->y[1023];
  mpc_socp__CPG_Dual.d121[12] = mpc_socp__qoco_solver->sol->y[1024];
  mpc_socp__CPG_Dual.d121[13] = mpc_socp__qoco_solver->sol->y[1025];
  mpc_socp__CPG_Dual.d122 = mpc_socp__qoco_solver->sol->z[90];
  mpc_socp__CPG_Dual.d123 = mpc_socp__qoco_solver->sol->z[91];
  mpc_socp__CPG_Dual.d124 = mpc_socp__qoco_solver->sol->z[92];
  mpc_socp__CPG_Dual.d125[0] = mpc_socp__qoco_solver->sol->y[1026];
  mpc_socp__CPG_Dual.d125[1] = mpc_socp__qoco_solver->sol->y[1027];
  mpc_socp__CPG_Dual.d125[2] = mpc_socp__qoco_solver->sol->y[1028];
  mpc_socp__CPG_Dual.d125[3] = mpc_socp__qoco_solver->sol->y[1029];
  mpc_socp__CPG_Dual.d125[4] = mpc_socp__qoco_solver->sol->y[1030];
  mpc_socp__CPG_Dual.d125[5] = mpc_socp__qoco_solver->sol->y[1031];
  mpc_socp__CPG_Dual.d125[6] = mpc_socp__qoco_solver->sol->y[1032];
  mpc_socp__CPG_Dual.d125[7] = mpc_socp__qoco_solver->sol->y[1033];
  mpc_socp__CPG_Dual.d125[8] = mpc_socp__qoco_solver->sol->y[1034];
  mpc_socp__CPG_Dual.d125[9] = mpc_socp__qoco_solver->sol->y[1035];
  mpc_socp__CPG_Dual.d125[10] = mpc_socp__qoco_solver->sol->y[1036];
  mpc_socp__CPG_Dual.d125[11] = mpc_socp__qoco_solver->sol->y[1037];
  mpc_socp__CPG_Dual.d125[12] = mpc_socp__qoco_solver->sol->y[1038];
  mpc_socp__CPG_Dual.d125[13] = mpc_socp__qoco_solver->sol->y[1039];
  mpc_socp__CPG_Dual.d126 = mpc_socp__qoco_solver->sol->z[93];
  mpc_socp__CPG_Dual.d127 = mpc_socp__qoco_solver->sol->z[94];
  mpc_socp__CPG_Dual.d128 = mpc_socp__qoco_solver->sol->z[95];
  mpc_socp__CPG_Dual.d129[0] = mpc_socp__qoco_solver->sol->y[1040];
  mpc_socp__CPG_Dual.d129[1] = mpc_socp__qoco_solver->sol->y[1041];
  mpc_socp__CPG_Dual.d129[2] = mpc_socp__qoco_solver->sol->y[1042];
  mpc_socp__CPG_Dual.d129[3] = mpc_socp__qoco_solver->sol->y[1043];
  mpc_socp__CPG_Dual.d129[4] = mpc_socp__qoco_solver->sol->y[1044];
  mpc_socp__CPG_Dual.d129[5] = mpc_socp__qoco_solver->sol->y[1045];
  mpc_socp__CPG_Dual.d129[6] = mpc_socp__qoco_solver->sol->y[1046];
  mpc_socp__CPG_Dual.d129[7] = mpc_socp__qoco_solver->sol->y[1047];
  mpc_socp__CPG_Dual.d129[8] = mpc_socp__qoco_solver->sol->y[1048];
  mpc_socp__CPG_Dual.d129[9] = mpc_socp__qoco_solver->sol->y[1049];
  mpc_socp__CPG_Dual.d129[10] = mpc_socp__qoco_solver->sol->y[1050];
  mpc_socp__CPG_Dual.d129[11] = mpc_socp__qoco_solver->sol->y[1051];
  mpc_socp__CPG_Dual.d129[12] = mpc_socp__qoco_solver->sol->y[1052];
  mpc_socp__CPG_Dual.d129[13] = mpc_socp__qoco_solver->sol->y[1053];
  mpc_socp__CPG_Dual.d130 = mpc_socp__qoco_solver->sol->z[96];
  mpc_socp__CPG_Dual.d131 = mpc_socp__qoco_solver->sol->z[97];
  mpc_socp__CPG_Dual.d132 = mpc_socp__qoco_solver->sol->z[98];
  mpc_socp__CPG_Dual.d133[0] = mpc_socp__qoco_solver->sol->y[1054];
  mpc_socp__CPG_Dual.d133[1] = mpc_socp__qoco_solver->sol->y[1055];
  mpc_socp__CPG_Dual.d133[2] = mpc_socp__qoco_solver->sol->y[1056];
  mpc_socp__CPG_Dual.d133[3] = mpc_socp__qoco_solver->sol->y[1057];
  mpc_socp__CPG_Dual.d133[4] = mpc_socp__qoco_solver->sol->y[1058];
  mpc_socp__CPG_Dual.d133[5] = mpc_socp__qoco_solver->sol->y[1059];
  mpc_socp__CPG_Dual.d133[6] = mpc_socp__qoco_solver->sol->y[1060];
  mpc_socp__CPG_Dual.d133[7] = mpc_socp__qoco_solver->sol->y[1061];
  mpc_socp__CPG_Dual.d133[8] = mpc_socp__qoco_solver->sol->y[1062];
  mpc_socp__CPG_Dual.d133[9] = mpc_socp__qoco_solver->sol->y[1063];
  mpc_socp__CPG_Dual.d133[10] = mpc_socp__qoco_solver->sol->y[1064];
  mpc_socp__CPG_Dual.d133[11] = mpc_socp__qoco_solver->sol->y[1065];
  mpc_socp__CPG_Dual.d133[12] = mpc_socp__qoco_solver->sol->y[1066];
  mpc_socp__CPG_Dual.d133[13] = mpc_socp__qoco_solver->sol->y[1067];
  mpc_socp__CPG_Dual.d134 = mpc_socp__qoco_solver->sol->z[99];
  mpc_socp__CPG_Dual.d135 = mpc_socp__qoco_solver->sol->z[100];
  mpc_socp__CPG_Dual.d136 = mpc_socp__qoco_solver->sol->z[101];
}

// Retrieve solver info
void mpc_socp__cpg_retrieve_info(){
  mpc_socp__CPG_Info.obj_val = (mpc_socp__qoco_solver->sol->obj);
  mpc_socp__CPG_Info.iter = mpc_socp__qoco_solver->sol->iters;
  mpc_socp__CPG_Info.status = mpc_socp__qoco_solver->sol->status;
  mpc_socp__CPG_Info.pri_res = mpc_socp__qoco_solver->sol->pres;
  mpc_socp__CPG_Info.dua_res = mpc_socp__qoco_solver->sol->dres;
}

// Copy canonical parameters for preconditioning
void mpc_socp__cpg_copy_P(){
  for (i=0; i<578; i++){
    mpc_socp__Canon_Params_conditioning.P->x[i] = mpc_socp__Canon_Params.P->x[i];
  }
}

void mpc_socp__cpg_copy_c(){
  for (i=0; i<1272; i++){
    mpc_socp__Canon_Params_conditioning.c[i] = mpc_socp__Canon_Params.c[i];
  }
}

void mpc_socp__cpg_copy_A(){
  for (i=0; i<9738; i++){
    mpc_socp__Canon_Params_conditioning.A->x[i] = mpc_socp__Canon_Params.A->x[i];
  }
}

void mpc_socp__cpg_copy_b(){
  for (i=0; i<1068; i++){
    mpc_socp__Canon_Params_conditioning.b[i] = mpc_socp__Canon_Params.b[i];
  }
}

void mpc_socp__cpg_copy_G(){
  for (i=0; i<544; i++){
    mpc_socp__Canon_Params_conditioning.G->x[i] = mpc_socp__Canon_Params.G->x[i];
  }
}

void mpc_socp__cpg_copy_h(){
  for (i=0; i<510; i++){
    mpc_socp__Canon_Params_conditioning.h[i] = mpc_socp__Canon_Params.h[i];
  }
}

void mpc_socp__cpg_copy_all(){
  mpc_socp__cpg_copy_P();
  mpc_socp__cpg_copy_c();
  mpc_socp__cpg_copy_A();
  mpc_socp__cpg_copy_b();
  mpc_socp__cpg_copy_G();
  mpc_socp__cpg_copy_h();
}

// Solve via canonicalization, canonical solve, retrieval
void mpc_socp__cpg_solve(){
  // Canonicalize if necessary
  if (mpc_socp__Canon_Outdated.A) {
    mpc_socp__cpg_canonicalize_A();
  }
  if (mpc_socp__Canon_Outdated.b) {
    mpc_socp__cpg_canonicalize_b();
  }
  if (mpc_socp__Canon_Outdated.G) {
    mpc_socp__cpg_canonicalize_G();
  }
  if (mpc_socp__Canon_Outdated.h) {
    mpc_socp__cpg_canonicalize_h();
  }
  if (!mpc_socp__qoco_solver ) {
    mpc_socp__cpg_copy_all();
   QOCOCscMatrix* P = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* A = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* G = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   qoco_set_csc(P, 1272, 1272, mpc_socp__Canon_Params.P->nnz, mpc_socp__Canon_Params.P->x, mpc_socp__Canon_Params.P->p, mpc_socp__Canon_Params.P->i);
   qoco_set_csc(A, 1068, 1272, mpc_socp__Canon_Params.A->nnz, mpc_socp__Canon_Params.A->x, mpc_socp__Canon_Params.A->p, mpc_socp__Canon_Params.A->i);
   qoco_set_csc(G, 510, 1272, mpc_socp__Canon_Params.G->nnz, mpc_socp__Canon_Params.G->x, mpc_socp__Canon_Params.G->p, mpc_socp__Canon_Params.G->i);
   QOCOSettings* qoco_settings = (QOCOSettings*)malloc(sizeof(QOCOSettings));
   set_default_settings(qoco_settings);
   mpc_socp__qoco_solver = (QOCOSolver*)malloc(sizeof(QOCOSolver));
   qoco_setup(mpc_socp__qoco_solver, 1272, 510, 1068, P, mpc_socp__Canon_Params.c, A, mpc_socp__Canon_Params.b, G, mpc_socp__Canon_Params.h, 102, 102, (int *) &mpc_socp__qoco_q, qoco_settings);
  }
  if (mpc_socp__Canon_Outdated.A) {
    update_matrix_data(mpc_socp__qoco_solver, NULL, mpc_socp__Canon_Params.A->x, NULL);
  }
  if (mpc_socp__Canon_Outdated.G) {
    update_matrix_data(mpc_socp__qoco_solver, NULL, NULL, mpc_socp__Canon_Params.G->x);
  }
  if (mpc_socp__Canon_Outdated.h) {
    update_vector_data(mpc_socp__qoco_solver, NULL, NULL, mpc_socp__Canon_Params.h);
  }
  if (mpc_socp__Canon_Outdated.b) {
    update_vector_data(mpc_socp__qoco_solver, NULL, mpc_socp__Canon_Params.b, NULL);
  }
  mpc_socp__qoco_solver->settings->max_iters = mpc_socp__Canon_Settings.max_iters;
  mpc_socp__qoco_solver->settings->bisect_iters = mpc_socp__Canon_Settings.bisect_iters;
  mpc_socp__qoco_solver->settings->ruiz_iters = mpc_socp__Canon_Settings.ruiz_iters;
  mpc_socp__qoco_solver->settings->iter_ref_iters = mpc_socp__Canon_Settings.iter_ref_iters;
  mpc_socp__qoco_solver->settings->kkt_static_reg = mpc_socp__Canon_Settings.kkt_static_reg;
  mpc_socp__qoco_solver->settings->kkt_dynamic_reg = mpc_socp__Canon_Settings.kkt_dynamic_reg;
  mpc_socp__qoco_solver->settings->abstol = mpc_socp__Canon_Settings.abstol;
  mpc_socp__qoco_solver->settings->reltol = mpc_socp__Canon_Settings.reltol;
  mpc_socp__qoco_solver->settings->abstol_inacc = mpc_socp__Canon_Settings.abstol_inacc;
  mpc_socp__qoco_solver->settings->reltol_inacc = mpc_socp__Canon_Settings.reltol_inacc;
  mpc_socp__qoco_solver->settings->verbose = mpc_socp__Canon_Settings.verbose;
  // Solve with QOCO
  qoco_solve(mpc_socp__qoco_solver);
  // Retrieve results
  mpc_socp__cpg_retrieve_prim();
  mpc_socp__cpg_retrieve_dual();
  mpc_socp__cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  mpc_socp__Canon_Outdated.A = 0;
  mpc_socp__Canon_Outdated.b = 0;
  mpc_socp__Canon_Outdated.G = 0;
  mpc_socp__Canon_Outdated.h = 0;
}

// Update solver settings
void mpc_socp__cpg_set_solver_default_settings(){
  mpc_socp__Canon_Settings.max_iters = 200;
  mpc_socp__Canon_Settings.bisect_iters = 5;
  mpc_socp__Canon_Settings.ruiz_iters = 0;
  mpc_socp__Canon_Settings.iter_ref_iters = 1;
  mpc_socp__Canon_Settings.kkt_static_reg = 1e-8;
  mpc_socp__Canon_Settings.kkt_dynamic_reg = 1e-8;
  mpc_socp__Canon_Settings.abstol = 1e-7;
  mpc_socp__Canon_Settings.reltol = 1e-7;
  mpc_socp__Canon_Settings.abstol_inacc = 1e-5;
  mpc_socp__Canon_Settings.reltol_inacc = 1e-5;
  mpc_socp__Canon_Settings.verbose = 0;
}

void mpc_socp__cpg_set_solver_max_iters(cpg_int max_iters_new){
  mpc_socp__Canon_Settings.max_iters = max_iters_new;
}

void mpc_socp__cpg_set_solver_bisect_iters(cpg_int bisect_iters_new){
  mpc_socp__Canon_Settings.bisect_iters = bisect_iters_new;
}

void mpc_socp__cpg_set_solver_ruiz_iters(cpg_int ruiz_iters_new){
  mpc_socp__Canon_Settings.ruiz_iters = ruiz_iters_new;
}

void mpc_socp__cpg_set_solver_iter_ref_iters(cpg_int iter_ref_iters_new){
  mpc_socp__Canon_Settings.iter_ref_iters = iter_ref_iters_new;
}

void mpc_socp__cpg_set_solver_kkt_static_reg(cpg_float kkt_static_reg_new){
  mpc_socp__Canon_Settings.kkt_static_reg = kkt_static_reg_new;
}

void mpc_socp__cpg_set_solver_kkt_dynamic_reg(cpg_float kkt_dynamic_reg_new){
  mpc_socp__Canon_Settings.kkt_dynamic_reg = kkt_dynamic_reg_new;
}

void mpc_socp__cpg_set_solver_abstol(cpg_float abstol_new){
  mpc_socp__Canon_Settings.abstol = abstol_new;
}

void mpc_socp__cpg_set_solver_reltol(cpg_float reltol_new){
  mpc_socp__Canon_Settings.reltol = reltol_new;
}

void mpc_socp__cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  mpc_socp__Canon_Settings.abstol_inacc = abstol_inacc_new;
}

void mpc_socp__cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  mpc_socp__Canon_Settings.reltol_inacc = reltol_inacc_new;
}

void mpc_socp__cpg_set_solver_verbose(cpg_int verbose_new){
  mpc_socp__Canon_Settings.verbose = verbose_new;
}
