
/*
Auto-generated by CVXPYgen on June 03, 2025 at 00:33:02.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void mpc_socp__cpg_update_param3412(cpg_int idx, cpg_float val){
  mpc_socp__cpg_params_vec[idx+0] = val;
  mpc_socp__Canon_Outdated.A = 1;
}

void mpc_socp__cpg_update_param3405(cpg_int idx, cpg_float val){
  mpc_socp__cpg_params_vec[idx+406] = val;
  mpc_socp__Canon_Outdated.b = 1;
}

void mpc_socp__cpg_update_param3406(cpg_int idx, cpg_float val){
  mpc_socp__cpg_params_vec[idx+420] = val;
  mpc_socp__Canon_Outdated.b = 1;
}

void mpc_socp__cpg_update_param3409(cpg_int idx, cpg_float val){
  mpc_socp__cpg_params_vec[idx+840] = val;
  mpc_socp__Canon_Outdated.A = 1;
}

void mpc_socp__cpg_update_param3410(cpg_int idx, cpg_float val){
  mpc_socp__cpg_params_vec[idx+6524] = val;
  mpc_socp__Canon_Outdated.A = 1;
}

void mpc_socp__cpg_update_param3407(cpg_int idx, cpg_float val){
  mpc_socp__cpg_params_vec[idx+7742] = val;
  mpc_socp__Canon_Outdated.G = 1;
  mpc_socp__Canon_Outdated.h = 1;
}

void mpc_socp__cpg_update_param3408(cpg_int idx, cpg_float val){
  mpc_socp__cpg_params_vec[idx+7829] = val;
  mpc_socp__Canon_Outdated.h = 1;
}

// Map user-defined to canonical parameters
void mpc_socp__cpg_canonicalize_A(){
  for(i=0; i<8308; i++){
    mpc_socp__Canon_Params.A->x[i] = 0;
    for(j=mpc_socp__canon_A_map.p[i]; j<mpc_socp__canon_A_map.p[i+1]; j++){
      mpc_socp__Canon_Params.A->x[i] += mpc_socp__canon_A_map.x[j]*mpc_socp__cpg_params_vec[mpc_socp__canon_A_map.i[j]];
    }
  }
}

void mpc_socp__cpg_canonicalize_b(){
  for(i=0; i<913; i++){
    mpc_socp__Canon_Params.b[i] = 0;
    for(j=mpc_socp__canon_b_map.p[i]; j<mpc_socp__canon_b_map.p[i+1]; j++){
      mpc_socp__Canon_Params.b[i] += mpc_socp__canon_b_map.x[j]*mpc_socp__cpg_params_vec[mpc_socp__canon_b_map.i[j]];
    }
  }
}

void mpc_socp__cpg_canonicalize_G(){
  for(i=0; i<464; i++){
    mpc_socp__Canon_Params.G->x[i] = 0;
    for(j=mpc_socp__canon_G_map.p[i]; j<mpc_socp__canon_G_map.p[i+1]; j++){
      mpc_socp__Canon_Params.G->x[i] += mpc_socp__canon_G_map.x[j]*mpc_socp__cpg_params_vec[mpc_socp__canon_G_map.i[j]];
    }
  }
}

void mpc_socp__cpg_canonicalize_h(){
  for(i=0; i<435; i++){
    mpc_socp__Canon_Params.h[i] = 0;
    for(j=mpc_socp__canon_h_map.p[i]; j<mpc_socp__canon_h_map.p[i+1]; j++){
      mpc_socp__Canon_Params.h[i] += mpc_socp__canon_h_map.x[j]*mpc_socp__cpg_params_vec[mpc_socp__canon_h_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void mpc_socp__cpg_retrieve_prim(){
  mpc_socp__CPG_Prim.var3403[0] = mpc_socp__qoco_solver->sol->x[493];
  mpc_socp__CPG_Prim.var3403[1] = mpc_socp__qoco_solver->sol->x[494];
  mpc_socp__CPG_Prim.var3403[2] = mpc_socp__qoco_solver->sol->x[495];
  mpc_socp__CPG_Prim.var3403[3] = mpc_socp__qoco_solver->sol->x[496];
  mpc_socp__CPG_Prim.var3403[4] = mpc_socp__qoco_solver->sol->x[497];
  mpc_socp__CPG_Prim.var3403[5] = mpc_socp__qoco_solver->sol->x[498];
  mpc_socp__CPG_Prim.var3403[6] = mpc_socp__qoco_solver->sol->x[499];
  mpc_socp__CPG_Prim.var3403[7] = mpc_socp__qoco_solver->sol->x[500];
  mpc_socp__CPG_Prim.var3403[8] = mpc_socp__qoco_solver->sol->x[501];
  mpc_socp__CPG_Prim.var3403[9] = mpc_socp__qoco_solver->sol->x[502];
  mpc_socp__CPG_Prim.var3403[10] = mpc_socp__qoco_solver->sol->x[503];
  mpc_socp__CPG_Prim.var3403[11] = mpc_socp__qoco_solver->sol->x[504];
  mpc_socp__CPG_Prim.var3403[12] = mpc_socp__qoco_solver->sol->x[505];
  mpc_socp__CPG_Prim.var3403[13] = mpc_socp__qoco_solver->sol->x[506];
  mpc_socp__CPG_Prim.var3403[14] = mpc_socp__qoco_solver->sol->x[507];
  mpc_socp__CPG_Prim.var3403[15] = mpc_socp__qoco_solver->sol->x[508];
  mpc_socp__CPG_Prim.var3403[16] = mpc_socp__qoco_solver->sol->x[509];
  mpc_socp__CPG_Prim.var3403[17] = mpc_socp__qoco_solver->sol->x[510];
  mpc_socp__CPG_Prim.var3403[18] = mpc_socp__qoco_solver->sol->x[511];
  mpc_socp__CPG_Prim.var3403[19] = mpc_socp__qoco_solver->sol->x[512];
  mpc_socp__CPG_Prim.var3403[20] = mpc_socp__qoco_solver->sol->x[513];
  mpc_socp__CPG_Prim.var3403[21] = mpc_socp__qoco_solver->sol->x[514];
  mpc_socp__CPG_Prim.var3403[22] = mpc_socp__qoco_solver->sol->x[515];
  mpc_socp__CPG_Prim.var3403[23] = mpc_socp__qoco_solver->sol->x[516];
  mpc_socp__CPG_Prim.var3403[24] = mpc_socp__qoco_solver->sol->x[517];
  mpc_socp__CPG_Prim.var3403[25] = mpc_socp__qoco_solver->sol->x[518];
  mpc_socp__CPG_Prim.var3403[26] = mpc_socp__qoco_solver->sol->x[519];
  mpc_socp__CPG_Prim.var3403[27] = mpc_socp__qoco_solver->sol->x[520];
  mpc_socp__CPG_Prim.var3403[28] = mpc_socp__qoco_solver->sol->x[521];
  mpc_socp__CPG_Prim.var3403[29] = mpc_socp__qoco_solver->sol->x[522];
  mpc_socp__CPG_Prim.var3403[30] = mpc_socp__qoco_solver->sol->x[523];
  mpc_socp__CPG_Prim.var3403[31] = mpc_socp__qoco_solver->sol->x[524];
  mpc_socp__CPG_Prim.var3403[32] = mpc_socp__qoco_solver->sol->x[525];
  mpc_socp__CPG_Prim.var3403[33] = mpc_socp__qoco_solver->sol->x[526];
  mpc_socp__CPG_Prim.var3403[34] = mpc_socp__qoco_solver->sol->x[527];
  mpc_socp__CPG_Prim.var3403[35] = mpc_socp__qoco_solver->sol->x[528];
  mpc_socp__CPG_Prim.var3403[36] = mpc_socp__qoco_solver->sol->x[529];
  mpc_socp__CPG_Prim.var3403[37] = mpc_socp__qoco_solver->sol->x[530];
  mpc_socp__CPG_Prim.var3403[38] = mpc_socp__qoco_solver->sol->x[531];
  mpc_socp__CPG_Prim.var3403[39] = mpc_socp__qoco_solver->sol->x[532];
  mpc_socp__CPG_Prim.var3403[40] = mpc_socp__qoco_solver->sol->x[533];
  mpc_socp__CPG_Prim.var3403[41] = mpc_socp__qoco_solver->sol->x[534];
  mpc_socp__CPG_Prim.var3403[42] = mpc_socp__qoco_solver->sol->x[535];
  mpc_socp__CPG_Prim.var3403[43] = mpc_socp__qoco_solver->sol->x[536];
  mpc_socp__CPG_Prim.var3403[44] = mpc_socp__qoco_solver->sol->x[537];
  mpc_socp__CPG_Prim.var3403[45] = mpc_socp__qoco_solver->sol->x[538];
  mpc_socp__CPG_Prim.var3403[46] = mpc_socp__qoco_solver->sol->x[539];
  mpc_socp__CPG_Prim.var3403[47] = mpc_socp__qoco_solver->sol->x[540];
  mpc_socp__CPG_Prim.var3403[48] = mpc_socp__qoco_solver->sol->x[541];
  mpc_socp__CPG_Prim.var3403[49] = mpc_socp__qoco_solver->sol->x[542];
  mpc_socp__CPG_Prim.var3403[50] = mpc_socp__qoco_solver->sol->x[543];
  mpc_socp__CPG_Prim.var3403[51] = mpc_socp__qoco_solver->sol->x[544];
  mpc_socp__CPG_Prim.var3403[52] = mpc_socp__qoco_solver->sol->x[545];
  mpc_socp__CPG_Prim.var3403[53] = mpc_socp__qoco_solver->sol->x[546];
  mpc_socp__CPG_Prim.var3403[54] = mpc_socp__qoco_solver->sol->x[547];
  mpc_socp__CPG_Prim.var3403[55] = mpc_socp__qoco_solver->sol->x[548];
  mpc_socp__CPG_Prim.var3403[56] = mpc_socp__qoco_solver->sol->x[549];
  mpc_socp__CPG_Prim.var3403[57] = mpc_socp__qoco_solver->sol->x[550];
  mpc_socp__CPG_Prim.var3403[58] = mpc_socp__qoco_solver->sol->x[551];
  mpc_socp__CPG_Prim.var3403[59] = mpc_socp__qoco_solver->sol->x[552];
  mpc_socp__CPG_Prim.var3403[60] = mpc_socp__qoco_solver->sol->x[553];
  mpc_socp__CPG_Prim.var3403[61] = mpc_socp__qoco_solver->sol->x[554];
  mpc_socp__CPG_Prim.var3403[62] = mpc_socp__qoco_solver->sol->x[555];
  mpc_socp__CPG_Prim.var3403[63] = mpc_socp__qoco_solver->sol->x[556];
  mpc_socp__CPG_Prim.var3403[64] = mpc_socp__qoco_solver->sol->x[557];
  mpc_socp__CPG_Prim.var3403[65] = mpc_socp__qoco_solver->sol->x[558];
  mpc_socp__CPG_Prim.var3403[66] = mpc_socp__qoco_solver->sol->x[559];
  mpc_socp__CPG_Prim.var3403[67] = mpc_socp__qoco_solver->sol->x[560];
  mpc_socp__CPG_Prim.var3403[68] = mpc_socp__qoco_solver->sol->x[561];
  mpc_socp__CPG_Prim.var3403[69] = mpc_socp__qoco_solver->sol->x[562];
  mpc_socp__CPG_Prim.var3403[70] = mpc_socp__qoco_solver->sol->x[563];
  mpc_socp__CPG_Prim.var3403[71] = mpc_socp__qoco_solver->sol->x[564];
  mpc_socp__CPG_Prim.var3403[72] = mpc_socp__qoco_solver->sol->x[565];
  mpc_socp__CPG_Prim.var3403[73] = mpc_socp__qoco_solver->sol->x[566];
  mpc_socp__CPG_Prim.var3403[74] = mpc_socp__qoco_solver->sol->x[567];
  mpc_socp__CPG_Prim.var3403[75] = mpc_socp__qoco_solver->sol->x[568];
  mpc_socp__CPG_Prim.var3403[76] = mpc_socp__qoco_solver->sol->x[569];
  mpc_socp__CPG_Prim.var3403[77] = mpc_socp__qoco_solver->sol->x[570];
  mpc_socp__CPG_Prim.var3403[78] = mpc_socp__qoco_solver->sol->x[571];
  mpc_socp__CPG_Prim.var3403[79] = mpc_socp__qoco_solver->sol->x[572];
  mpc_socp__CPG_Prim.var3403[80] = mpc_socp__qoco_solver->sol->x[573];
  mpc_socp__CPG_Prim.var3403[81] = mpc_socp__qoco_solver->sol->x[574];
  mpc_socp__CPG_Prim.var3403[82] = mpc_socp__qoco_solver->sol->x[575];
  mpc_socp__CPG_Prim.var3403[83] = mpc_socp__qoco_solver->sol->x[576];
  mpc_socp__CPG_Prim.var3403[84] = mpc_socp__qoco_solver->sol->x[577];
  mpc_socp__CPG_Prim.var3403[85] = mpc_socp__qoco_solver->sol->x[578];
  mpc_socp__CPG_Prim.var3403[86] = mpc_socp__qoco_solver->sol->x[579];
  mpc_socp__CPG_Prim.var3403[87] = mpc_socp__qoco_solver->sol->x[580];
  mpc_socp__CPG_Prim.var3403[88] = mpc_socp__qoco_solver->sol->x[581];
  mpc_socp__CPG_Prim.var3403[89] = mpc_socp__qoco_solver->sol->x[582];
  mpc_socp__CPG_Prim.var3403[90] = mpc_socp__qoco_solver->sol->x[583];
  mpc_socp__CPG_Prim.var3403[91] = mpc_socp__qoco_solver->sol->x[584];
  mpc_socp__CPG_Prim.var3403[92] = mpc_socp__qoco_solver->sol->x[585];
  mpc_socp__CPG_Prim.var3403[93] = mpc_socp__qoco_solver->sol->x[586];
  mpc_socp__CPG_Prim.var3403[94] = mpc_socp__qoco_solver->sol->x[587];
  mpc_socp__CPG_Prim.var3403[95] = mpc_socp__qoco_solver->sol->x[588];
  mpc_socp__CPG_Prim.var3403[96] = mpc_socp__qoco_solver->sol->x[589];
  mpc_socp__CPG_Prim.var3403[97] = mpc_socp__qoco_solver->sol->x[590];
  mpc_socp__CPG_Prim.var3403[98] = mpc_socp__qoco_solver->sol->x[591];
  mpc_socp__CPG_Prim.var3403[99] = mpc_socp__qoco_solver->sol->x[592];
  mpc_socp__CPG_Prim.var3403[100] = mpc_socp__qoco_solver->sol->x[593];
  mpc_socp__CPG_Prim.var3403[101] = mpc_socp__qoco_solver->sol->x[594];
  mpc_socp__CPG_Prim.var3403[102] = mpc_socp__qoco_solver->sol->x[595];
  mpc_socp__CPG_Prim.var3403[103] = mpc_socp__qoco_solver->sol->x[596];
  mpc_socp__CPG_Prim.var3403[104] = mpc_socp__qoco_solver->sol->x[597];
  mpc_socp__CPG_Prim.var3403[105] = mpc_socp__qoco_solver->sol->x[598];
  mpc_socp__CPG_Prim.var3403[106] = mpc_socp__qoco_solver->sol->x[599];
  mpc_socp__CPG_Prim.var3403[107] = mpc_socp__qoco_solver->sol->x[600];
  mpc_socp__CPG_Prim.var3403[108] = mpc_socp__qoco_solver->sol->x[601];
  mpc_socp__CPG_Prim.var3403[109] = mpc_socp__qoco_solver->sol->x[602];
  mpc_socp__CPG_Prim.var3403[110] = mpc_socp__qoco_solver->sol->x[603];
  mpc_socp__CPG_Prim.var3403[111] = mpc_socp__qoco_solver->sol->x[604];
  mpc_socp__CPG_Prim.var3403[112] = mpc_socp__qoco_solver->sol->x[605];
  mpc_socp__CPG_Prim.var3403[113] = mpc_socp__qoco_solver->sol->x[606];
  mpc_socp__CPG_Prim.var3403[114] = mpc_socp__qoco_solver->sol->x[607];
  mpc_socp__CPG_Prim.var3403[115] = mpc_socp__qoco_solver->sol->x[608];
  mpc_socp__CPG_Prim.var3403[116] = mpc_socp__qoco_solver->sol->x[609];
  mpc_socp__CPG_Prim.var3403[117] = mpc_socp__qoco_solver->sol->x[610];
  mpc_socp__CPG_Prim.var3403[118] = mpc_socp__qoco_solver->sol->x[611];
  mpc_socp__CPG_Prim.var3403[119] = mpc_socp__qoco_solver->sol->x[612];
  mpc_socp__CPG_Prim.var3403[120] = mpc_socp__qoco_solver->sol->x[613];
  mpc_socp__CPG_Prim.var3403[121] = mpc_socp__qoco_solver->sol->x[614];
  mpc_socp__CPG_Prim.var3403[122] = mpc_socp__qoco_solver->sol->x[615];
  mpc_socp__CPG_Prim.var3403[123] = mpc_socp__qoco_solver->sol->x[616];
  mpc_socp__CPG_Prim.var3403[124] = mpc_socp__qoco_solver->sol->x[617];
  mpc_socp__CPG_Prim.var3403[125] = mpc_socp__qoco_solver->sol->x[618];
  mpc_socp__CPG_Prim.var3403[126] = mpc_socp__qoco_solver->sol->x[619];
  mpc_socp__CPG_Prim.var3403[127] = mpc_socp__qoco_solver->sol->x[620];
  mpc_socp__CPG_Prim.var3403[128] = mpc_socp__qoco_solver->sol->x[621];
  mpc_socp__CPG_Prim.var3403[129] = mpc_socp__qoco_solver->sol->x[622];
  mpc_socp__CPG_Prim.var3403[130] = mpc_socp__qoco_solver->sol->x[623];
  mpc_socp__CPG_Prim.var3403[131] = mpc_socp__qoco_solver->sol->x[624];
  mpc_socp__CPG_Prim.var3403[132] = mpc_socp__qoco_solver->sol->x[625];
  mpc_socp__CPG_Prim.var3403[133] = mpc_socp__qoco_solver->sol->x[626];
  mpc_socp__CPG_Prim.var3403[134] = mpc_socp__qoco_solver->sol->x[627];
  mpc_socp__CPG_Prim.var3403[135] = mpc_socp__qoco_solver->sol->x[628];
  mpc_socp__CPG_Prim.var3403[136] = mpc_socp__qoco_solver->sol->x[629];
  mpc_socp__CPG_Prim.var3403[137] = mpc_socp__qoco_solver->sol->x[630];
  mpc_socp__CPG_Prim.var3403[138] = mpc_socp__qoco_solver->sol->x[631];
  mpc_socp__CPG_Prim.var3403[139] = mpc_socp__qoco_solver->sol->x[632];
  mpc_socp__CPG_Prim.var3403[140] = mpc_socp__qoco_solver->sol->x[633];
  mpc_socp__CPG_Prim.var3403[141] = mpc_socp__qoco_solver->sol->x[634];
  mpc_socp__CPG_Prim.var3403[142] = mpc_socp__qoco_solver->sol->x[635];
  mpc_socp__CPG_Prim.var3403[143] = mpc_socp__qoco_solver->sol->x[636];
  mpc_socp__CPG_Prim.var3403[144] = mpc_socp__qoco_solver->sol->x[637];
  mpc_socp__CPG_Prim.var3403[145] = mpc_socp__qoco_solver->sol->x[638];
  mpc_socp__CPG_Prim.var3403[146] = mpc_socp__qoco_solver->sol->x[639];
  mpc_socp__CPG_Prim.var3403[147] = mpc_socp__qoco_solver->sol->x[640];
  mpc_socp__CPG_Prim.var3403[148] = mpc_socp__qoco_solver->sol->x[641];
  mpc_socp__CPG_Prim.var3403[149] = mpc_socp__qoco_solver->sol->x[642];
  mpc_socp__CPG_Prim.var3403[150] = mpc_socp__qoco_solver->sol->x[643];
  mpc_socp__CPG_Prim.var3403[151] = mpc_socp__qoco_solver->sol->x[644];
  mpc_socp__CPG_Prim.var3403[152] = mpc_socp__qoco_solver->sol->x[645];
  mpc_socp__CPG_Prim.var3403[153] = mpc_socp__qoco_solver->sol->x[646];
  mpc_socp__CPG_Prim.var3403[154] = mpc_socp__qoco_solver->sol->x[647];
  mpc_socp__CPG_Prim.var3403[155] = mpc_socp__qoco_solver->sol->x[648];
  mpc_socp__CPG_Prim.var3403[156] = mpc_socp__qoco_solver->sol->x[649];
  mpc_socp__CPG_Prim.var3403[157] = mpc_socp__qoco_solver->sol->x[650];
  mpc_socp__CPG_Prim.var3403[158] = mpc_socp__qoco_solver->sol->x[651];
  mpc_socp__CPG_Prim.var3403[159] = mpc_socp__qoco_solver->sol->x[652];
  mpc_socp__CPG_Prim.var3403[160] = mpc_socp__qoco_solver->sol->x[653];
  mpc_socp__CPG_Prim.var3403[161] = mpc_socp__qoco_solver->sol->x[654];
  mpc_socp__CPG_Prim.var3403[162] = mpc_socp__qoco_solver->sol->x[655];
  mpc_socp__CPG_Prim.var3403[163] = mpc_socp__qoco_solver->sol->x[656];
  mpc_socp__CPG_Prim.var3403[164] = mpc_socp__qoco_solver->sol->x[657];
  mpc_socp__CPG_Prim.var3403[165] = mpc_socp__qoco_solver->sol->x[658];
  mpc_socp__CPG_Prim.var3403[166] = mpc_socp__qoco_solver->sol->x[659];
  mpc_socp__CPG_Prim.var3403[167] = mpc_socp__qoco_solver->sol->x[660];
  mpc_socp__CPG_Prim.var3403[168] = mpc_socp__qoco_solver->sol->x[661];
  mpc_socp__CPG_Prim.var3403[169] = mpc_socp__qoco_solver->sol->x[662];
  mpc_socp__CPG_Prim.var3403[170] = mpc_socp__qoco_solver->sol->x[663];
  mpc_socp__CPG_Prim.var3403[171] = mpc_socp__qoco_solver->sol->x[664];
  mpc_socp__CPG_Prim.var3403[172] = mpc_socp__qoco_solver->sol->x[665];
  mpc_socp__CPG_Prim.var3403[173] = mpc_socp__qoco_solver->sol->x[666];
  mpc_socp__CPG_Prim.var3403[174] = mpc_socp__qoco_solver->sol->x[667];
  mpc_socp__CPG_Prim.var3403[175] = mpc_socp__qoco_solver->sol->x[668];
  mpc_socp__CPG_Prim.var3403[176] = mpc_socp__qoco_solver->sol->x[669];
  mpc_socp__CPG_Prim.var3403[177] = mpc_socp__qoco_solver->sol->x[670];
  mpc_socp__CPG_Prim.var3403[178] = mpc_socp__qoco_solver->sol->x[671];
  mpc_socp__CPG_Prim.var3403[179] = mpc_socp__qoco_solver->sol->x[672];
  mpc_socp__CPG_Prim.var3403[180] = mpc_socp__qoco_solver->sol->x[673];
  mpc_socp__CPG_Prim.var3403[181] = mpc_socp__qoco_solver->sol->x[674];
  mpc_socp__CPG_Prim.var3403[182] = mpc_socp__qoco_solver->sol->x[675];
  mpc_socp__CPG_Prim.var3403[183] = mpc_socp__qoco_solver->sol->x[676];
  mpc_socp__CPG_Prim.var3403[184] = mpc_socp__qoco_solver->sol->x[677];
  mpc_socp__CPG_Prim.var3403[185] = mpc_socp__qoco_solver->sol->x[678];
  mpc_socp__CPG_Prim.var3403[186] = mpc_socp__qoco_solver->sol->x[679];
  mpc_socp__CPG_Prim.var3403[187] = mpc_socp__qoco_solver->sol->x[680];
  mpc_socp__CPG_Prim.var3403[188] = mpc_socp__qoco_solver->sol->x[681];
  mpc_socp__CPG_Prim.var3403[189] = mpc_socp__qoco_solver->sol->x[682];
  mpc_socp__CPG_Prim.var3403[190] = mpc_socp__qoco_solver->sol->x[683];
  mpc_socp__CPG_Prim.var3403[191] = mpc_socp__qoco_solver->sol->x[684];
  mpc_socp__CPG_Prim.var3403[192] = mpc_socp__qoco_solver->sol->x[685];
  mpc_socp__CPG_Prim.var3403[193] = mpc_socp__qoco_solver->sol->x[686];
  mpc_socp__CPG_Prim.var3403[194] = mpc_socp__qoco_solver->sol->x[687];
  mpc_socp__CPG_Prim.var3403[195] = mpc_socp__qoco_solver->sol->x[688];
  mpc_socp__CPG_Prim.var3403[196] = mpc_socp__qoco_solver->sol->x[689];
  mpc_socp__CPG_Prim.var3403[197] = mpc_socp__qoco_solver->sol->x[690];
  mpc_socp__CPG_Prim.var3403[198] = mpc_socp__qoco_solver->sol->x[691];
  mpc_socp__CPG_Prim.var3403[199] = mpc_socp__qoco_solver->sol->x[692];
  mpc_socp__CPG_Prim.var3403[200] = mpc_socp__qoco_solver->sol->x[693];
  mpc_socp__CPG_Prim.var3403[201] = mpc_socp__qoco_solver->sol->x[694];
  mpc_socp__CPG_Prim.var3403[202] = mpc_socp__qoco_solver->sol->x[695];
  mpc_socp__CPG_Prim.var3403[203] = mpc_socp__qoco_solver->sol->x[696];
  mpc_socp__CPG_Prim.var3403[204] = mpc_socp__qoco_solver->sol->x[697];
  mpc_socp__CPG_Prim.var3403[205] = mpc_socp__qoco_solver->sol->x[698];
  mpc_socp__CPG_Prim.var3403[206] = mpc_socp__qoco_solver->sol->x[699];
  mpc_socp__CPG_Prim.var3403[207] = mpc_socp__qoco_solver->sol->x[700];
  mpc_socp__CPG_Prim.var3403[208] = mpc_socp__qoco_solver->sol->x[701];
  mpc_socp__CPG_Prim.var3403[209] = mpc_socp__qoco_solver->sol->x[702];
  mpc_socp__CPG_Prim.var3403[210] = mpc_socp__qoco_solver->sol->x[703];
  mpc_socp__CPG_Prim.var3403[211] = mpc_socp__qoco_solver->sol->x[704];
  mpc_socp__CPG_Prim.var3403[212] = mpc_socp__qoco_solver->sol->x[705];
  mpc_socp__CPG_Prim.var3403[213] = mpc_socp__qoco_solver->sol->x[706];
  mpc_socp__CPG_Prim.var3403[214] = mpc_socp__qoco_solver->sol->x[707];
  mpc_socp__CPG_Prim.var3403[215] = mpc_socp__qoco_solver->sol->x[708];
  mpc_socp__CPG_Prim.var3403[216] = mpc_socp__qoco_solver->sol->x[709];
  mpc_socp__CPG_Prim.var3403[217] = mpc_socp__qoco_solver->sol->x[710];
  mpc_socp__CPG_Prim.var3403[218] = mpc_socp__qoco_solver->sol->x[711];
  mpc_socp__CPG_Prim.var3403[219] = mpc_socp__qoco_solver->sol->x[712];
  mpc_socp__CPG_Prim.var3403[220] = mpc_socp__qoco_solver->sol->x[713];
  mpc_socp__CPG_Prim.var3403[221] = mpc_socp__qoco_solver->sol->x[714];
  mpc_socp__CPG_Prim.var3403[222] = mpc_socp__qoco_solver->sol->x[715];
  mpc_socp__CPG_Prim.var3403[223] = mpc_socp__qoco_solver->sol->x[716];
  mpc_socp__CPG_Prim.var3403[224] = mpc_socp__qoco_solver->sol->x[717];
  mpc_socp__CPG_Prim.var3403[225] = mpc_socp__qoco_solver->sol->x[718];
  mpc_socp__CPG_Prim.var3403[226] = mpc_socp__qoco_solver->sol->x[719];
  mpc_socp__CPG_Prim.var3403[227] = mpc_socp__qoco_solver->sol->x[720];
  mpc_socp__CPG_Prim.var3403[228] = mpc_socp__qoco_solver->sol->x[721];
  mpc_socp__CPG_Prim.var3403[229] = mpc_socp__qoco_solver->sol->x[722];
  mpc_socp__CPG_Prim.var3403[230] = mpc_socp__qoco_solver->sol->x[723];
  mpc_socp__CPG_Prim.var3403[231] = mpc_socp__qoco_solver->sol->x[724];
  mpc_socp__CPG_Prim.var3403[232] = mpc_socp__qoco_solver->sol->x[725];
  mpc_socp__CPG_Prim.var3403[233] = mpc_socp__qoco_solver->sol->x[726];
  mpc_socp__CPG_Prim.var3403[234] = mpc_socp__qoco_solver->sol->x[727];
  mpc_socp__CPG_Prim.var3403[235] = mpc_socp__qoco_solver->sol->x[728];
  mpc_socp__CPG_Prim.var3403[236] = mpc_socp__qoco_solver->sol->x[729];
  mpc_socp__CPG_Prim.var3403[237] = mpc_socp__qoco_solver->sol->x[730];
  mpc_socp__CPG_Prim.var3403[238] = mpc_socp__qoco_solver->sol->x[731];
  mpc_socp__CPG_Prim.var3403[239] = mpc_socp__qoco_solver->sol->x[732];
  mpc_socp__CPG_Prim.var3403[240] = mpc_socp__qoco_solver->sol->x[733];
  mpc_socp__CPG_Prim.var3403[241] = mpc_socp__qoco_solver->sol->x[734];
  mpc_socp__CPG_Prim.var3403[242] = mpc_socp__qoco_solver->sol->x[735];
  mpc_socp__CPG_Prim.var3403[243] = mpc_socp__qoco_solver->sol->x[736];
  mpc_socp__CPG_Prim.var3403[244] = mpc_socp__qoco_solver->sol->x[737];
  mpc_socp__CPG_Prim.var3403[245] = mpc_socp__qoco_solver->sol->x[738];
  mpc_socp__CPG_Prim.var3403[246] = mpc_socp__qoco_solver->sol->x[739];
  mpc_socp__CPG_Prim.var3403[247] = mpc_socp__qoco_solver->sol->x[740];
  mpc_socp__CPG_Prim.var3403[248] = mpc_socp__qoco_solver->sol->x[741];
  mpc_socp__CPG_Prim.var3403[249] = mpc_socp__qoco_solver->sol->x[742];
  mpc_socp__CPG_Prim.var3403[250] = mpc_socp__qoco_solver->sol->x[743];
  mpc_socp__CPG_Prim.var3403[251] = mpc_socp__qoco_solver->sol->x[744];
  mpc_socp__CPG_Prim.var3403[252] = mpc_socp__qoco_solver->sol->x[745];
  mpc_socp__CPG_Prim.var3403[253] = mpc_socp__qoco_solver->sol->x[746];
  mpc_socp__CPG_Prim.var3403[254] = mpc_socp__qoco_solver->sol->x[747];
  mpc_socp__CPG_Prim.var3403[255] = mpc_socp__qoco_solver->sol->x[748];
  mpc_socp__CPG_Prim.var3403[256] = mpc_socp__qoco_solver->sol->x[749];
  mpc_socp__CPG_Prim.var3403[257] = mpc_socp__qoco_solver->sol->x[750];
  mpc_socp__CPG_Prim.var3403[258] = mpc_socp__qoco_solver->sol->x[751];
  mpc_socp__CPG_Prim.var3403[259] = mpc_socp__qoco_solver->sol->x[752];
  mpc_socp__CPG_Prim.var3403[260] = mpc_socp__qoco_solver->sol->x[753];
  mpc_socp__CPG_Prim.var3403[261] = mpc_socp__qoco_solver->sol->x[754];
  mpc_socp__CPG_Prim.var3403[262] = mpc_socp__qoco_solver->sol->x[755];
  mpc_socp__CPG_Prim.var3403[263] = mpc_socp__qoco_solver->sol->x[756];
  mpc_socp__CPG_Prim.var3403[264] = mpc_socp__qoco_solver->sol->x[757];
  mpc_socp__CPG_Prim.var3403[265] = mpc_socp__qoco_solver->sol->x[758];
  mpc_socp__CPG_Prim.var3403[266] = mpc_socp__qoco_solver->sol->x[759];
  mpc_socp__CPG_Prim.var3403[267] = mpc_socp__qoco_solver->sol->x[760];
  mpc_socp__CPG_Prim.var3403[268] = mpc_socp__qoco_solver->sol->x[761];
  mpc_socp__CPG_Prim.var3403[269] = mpc_socp__qoco_solver->sol->x[762];
  mpc_socp__CPG_Prim.var3403[270] = mpc_socp__qoco_solver->sol->x[763];
  mpc_socp__CPG_Prim.var3403[271] = mpc_socp__qoco_solver->sol->x[764];
  mpc_socp__CPG_Prim.var3403[272] = mpc_socp__qoco_solver->sol->x[765];
  mpc_socp__CPG_Prim.var3403[273] = mpc_socp__qoco_solver->sol->x[766];
  mpc_socp__CPG_Prim.var3403[274] = mpc_socp__qoco_solver->sol->x[767];
  mpc_socp__CPG_Prim.var3403[275] = mpc_socp__qoco_solver->sol->x[768];
  mpc_socp__CPG_Prim.var3403[276] = mpc_socp__qoco_solver->sol->x[769];
  mpc_socp__CPG_Prim.var3403[277] = mpc_socp__qoco_solver->sol->x[770];
  mpc_socp__CPG_Prim.var3403[278] = mpc_socp__qoco_solver->sol->x[771];
  mpc_socp__CPG_Prim.var3403[279] = mpc_socp__qoco_solver->sol->x[772];
  mpc_socp__CPG_Prim.var3403[280] = mpc_socp__qoco_solver->sol->x[773];
  mpc_socp__CPG_Prim.var3403[281] = mpc_socp__qoco_solver->sol->x[774];
  mpc_socp__CPG_Prim.var3403[282] = mpc_socp__qoco_solver->sol->x[775];
  mpc_socp__CPG_Prim.var3403[283] = mpc_socp__qoco_solver->sol->x[776];
  mpc_socp__CPG_Prim.var3403[284] = mpc_socp__qoco_solver->sol->x[777];
  mpc_socp__CPG_Prim.var3403[285] = mpc_socp__qoco_solver->sol->x[778];
  mpc_socp__CPG_Prim.var3403[286] = mpc_socp__qoco_solver->sol->x[779];
  mpc_socp__CPG_Prim.var3403[287] = mpc_socp__qoco_solver->sol->x[780];
  mpc_socp__CPG_Prim.var3403[288] = mpc_socp__qoco_solver->sol->x[781];
  mpc_socp__CPG_Prim.var3403[289] = mpc_socp__qoco_solver->sol->x[782];
  mpc_socp__CPG_Prim.var3403[290] = mpc_socp__qoco_solver->sol->x[783];
  mpc_socp__CPG_Prim.var3403[291] = mpc_socp__qoco_solver->sol->x[784];
  mpc_socp__CPG_Prim.var3403[292] = mpc_socp__qoco_solver->sol->x[785];
  mpc_socp__CPG_Prim.var3403[293] = mpc_socp__qoco_solver->sol->x[786];
  mpc_socp__CPG_Prim.var3403[294] = mpc_socp__qoco_solver->sol->x[787];
  mpc_socp__CPG_Prim.var3403[295] = mpc_socp__qoco_solver->sol->x[788];
  mpc_socp__CPG_Prim.var3403[296] = mpc_socp__qoco_solver->sol->x[789];
  mpc_socp__CPG_Prim.var3403[297] = mpc_socp__qoco_solver->sol->x[790];
  mpc_socp__CPG_Prim.var3403[298] = mpc_socp__qoco_solver->sol->x[791];
  mpc_socp__CPG_Prim.var3403[299] = mpc_socp__qoco_solver->sol->x[792];
  mpc_socp__CPG_Prim.var3403[300] = mpc_socp__qoco_solver->sol->x[793];
  mpc_socp__CPG_Prim.var3403[301] = mpc_socp__qoco_solver->sol->x[794];
  mpc_socp__CPG_Prim.var3403[302] = mpc_socp__qoco_solver->sol->x[795];
  mpc_socp__CPG_Prim.var3403[303] = mpc_socp__qoco_solver->sol->x[796];
  mpc_socp__CPG_Prim.var3403[304] = mpc_socp__qoco_solver->sol->x[797];
  mpc_socp__CPG_Prim.var3403[305] = mpc_socp__qoco_solver->sol->x[798];
  mpc_socp__CPG_Prim.var3403[306] = mpc_socp__qoco_solver->sol->x[799];
  mpc_socp__CPG_Prim.var3403[307] = mpc_socp__qoco_solver->sol->x[800];
  mpc_socp__CPG_Prim.var3403[308] = mpc_socp__qoco_solver->sol->x[801];
  mpc_socp__CPG_Prim.var3403[309] = mpc_socp__qoco_solver->sol->x[802];
  mpc_socp__CPG_Prim.var3403[310] = mpc_socp__qoco_solver->sol->x[803];
  mpc_socp__CPG_Prim.var3403[311] = mpc_socp__qoco_solver->sol->x[804];
  mpc_socp__CPG_Prim.var3403[312] = mpc_socp__qoco_solver->sol->x[805];
  mpc_socp__CPG_Prim.var3403[313] = mpc_socp__qoco_solver->sol->x[806];
  mpc_socp__CPG_Prim.var3403[314] = mpc_socp__qoco_solver->sol->x[807];
  mpc_socp__CPG_Prim.var3403[315] = mpc_socp__qoco_solver->sol->x[808];
  mpc_socp__CPG_Prim.var3403[316] = mpc_socp__qoco_solver->sol->x[809];
  mpc_socp__CPG_Prim.var3403[317] = mpc_socp__qoco_solver->sol->x[810];
  mpc_socp__CPG_Prim.var3403[318] = mpc_socp__qoco_solver->sol->x[811];
  mpc_socp__CPG_Prim.var3403[319] = mpc_socp__qoco_solver->sol->x[812];
  mpc_socp__CPG_Prim.var3403[320] = mpc_socp__qoco_solver->sol->x[813];
  mpc_socp__CPG_Prim.var3403[321] = mpc_socp__qoco_solver->sol->x[814];
  mpc_socp__CPG_Prim.var3403[322] = mpc_socp__qoco_solver->sol->x[815];
  mpc_socp__CPG_Prim.var3403[323] = mpc_socp__qoco_solver->sol->x[816];
  mpc_socp__CPG_Prim.var3403[324] = mpc_socp__qoco_solver->sol->x[817];
  mpc_socp__CPG_Prim.var3403[325] = mpc_socp__qoco_solver->sol->x[818];
  mpc_socp__CPG_Prim.var3403[326] = mpc_socp__qoco_solver->sol->x[819];
  mpc_socp__CPG_Prim.var3403[327] = mpc_socp__qoco_solver->sol->x[820];
  mpc_socp__CPG_Prim.var3403[328] = mpc_socp__qoco_solver->sol->x[821];
  mpc_socp__CPG_Prim.var3403[329] = mpc_socp__qoco_solver->sol->x[822];
  mpc_socp__CPG_Prim.var3403[330] = mpc_socp__qoco_solver->sol->x[823];
  mpc_socp__CPG_Prim.var3403[331] = mpc_socp__qoco_solver->sol->x[824];
  mpc_socp__CPG_Prim.var3403[332] = mpc_socp__qoco_solver->sol->x[825];
  mpc_socp__CPG_Prim.var3403[333] = mpc_socp__qoco_solver->sol->x[826];
  mpc_socp__CPG_Prim.var3403[334] = mpc_socp__qoco_solver->sol->x[827];
  mpc_socp__CPG_Prim.var3403[335] = mpc_socp__qoco_solver->sol->x[828];
  mpc_socp__CPG_Prim.var3403[336] = mpc_socp__qoco_solver->sol->x[829];
  mpc_socp__CPG_Prim.var3403[337] = mpc_socp__qoco_solver->sol->x[830];
  mpc_socp__CPG_Prim.var3403[338] = mpc_socp__qoco_solver->sol->x[831];
  mpc_socp__CPG_Prim.var3403[339] = mpc_socp__qoco_solver->sol->x[832];
  mpc_socp__CPG_Prim.var3403[340] = mpc_socp__qoco_solver->sol->x[833];
  mpc_socp__CPG_Prim.var3403[341] = mpc_socp__qoco_solver->sol->x[834];
  mpc_socp__CPG_Prim.var3403[342] = mpc_socp__qoco_solver->sol->x[835];
  mpc_socp__CPG_Prim.var3403[343] = mpc_socp__qoco_solver->sol->x[836];
  mpc_socp__CPG_Prim.var3403[344] = mpc_socp__qoco_solver->sol->x[837];
  mpc_socp__CPG_Prim.var3403[345] = mpc_socp__qoco_solver->sol->x[838];
  mpc_socp__CPG_Prim.var3403[346] = mpc_socp__qoco_solver->sol->x[839];
  mpc_socp__CPG_Prim.var3403[347] = mpc_socp__qoco_solver->sol->x[840];
  mpc_socp__CPG_Prim.var3403[348] = mpc_socp__qoco_solver->sol->x[841];
  mpc_socp__CPG_Prim.var3403[349] = mpc_socp__qoco_solver->sol->x[842];
  mpc_socp__CPG_Prim.var3403[350] = mpc_socp__qoco_solver->sol->x[843];
  mpc_socp__CPG_Prim.var3403[351] = mpc_socp__qoco_solver->sol->x[844];
  mpc_socp__CPG_Prim.var3403[352] = mpc_socp__qoco_solver->sol->x[845];
  mpc_socp__CPG_Prim.var3403[353] = mpc_socp__qoco_solver->sol->x[846];
  mpc_socp__CPG_Prim.var3403[354] = mpc_socp__qoco_solver->sol->x[847];
  mpc_socp__CPG_Prim.var3403[355] = mpc_socp__qoco_solver->sol->x[848];
  mpc_socp__CPG_Prim.var3403[356] = mpc_socp__qoco_solver->sol->x[849];
  mpc_socp__CPG_Prim.var3403[357] = mpc_socp__qoco_solver->sol->x[850];
  mpc_socp__CPG_Prim.var3403[358] = mpc_socp__qoco_solver->sol->x[851];
  mpc_socp__CPG_Prim.var3403[359] = mpc_socp__qoco_solver->sol->x[852];
  mpc_socp__CPG_Prim.var3403[360] = mpc_socp__qoco_solver->sol->x[853];
  mpc_socp__CPG_Prim.var3403[361] = mpc_socp__qoco_solver->sol->x[854];
  mpc_socp__CPG_Prim.var3403[362] = mpc_socp__qoco_solver->sol->x[855];
  mpc_socp__CPG_Prim.var3403[363] = mpc_socp__qoco_solver->sol->x[856];
  mpc_socp__CPG_Prim.var3403[364] = mpc_socp__qoco_solver->sol->x[857];
  mpc_socp__CPG_Prim.var3403[365] = mpc_socp__qoco_solver->sol->x[858];
  mpc_socp__CPG_Prim.var3403[366] = mpc_socp__qoco_solver->sol->x[859];
  mpc_socp__CPG_Prim.var3403[367] = mpc_socp__qoco_solver->sol->x[860];
  mpc_socp__CPG_Prim.var3403[368] = mpc_socp__qoco_solver->sol->x[861];
  mpc_socp__CPG_Prim.var3403[369] = mpc_socp__qoco_solver->sol->x[862];
  mpc_socp__CPG_Prim.var3403[370] = mpc_socp__qoco_solver->sol->x[863];
  mpc_socp__CPG_Prim.var3403[371] = mpc_socp__qoco_solver->sol->x[864];
  mpc_socp__CPG_Prim.var3403[372] = mpc_socp__qoco_solver->sol->x[865];
  mpc_socp__CPG_Prim.var3403[373] = mpc_socp__qoco_solver->sol->x[866];
  mpc_socp__CPG_Prim.var3403[374] = mpc_socp__qoco_solver->sol->x[867];
  mpc_socp__CPG_Prim.var3403[375] = mpc_socp__qoco_solver->sol->x[868];
  mpc_socp__CPG_Prim.var3403[376] = mpc_socp__qoco_solver->sol->x[869];
  mpc_socp__CPG_Prim.var3403[377] = mpc_socp__qoco_solver->sol->x[870];
  mpc_socp__CPG_Prim.var3403[378] = mpc_socp__qoco_solver->sol->x[871];
  mpc_socp__CPG_Prim.var3403[379] = mpc_socp__qoco_solver->sol->x[872];
  mpc_socp__CPG_Prim.var3403[380] = mpc_socp__qoco_solver->sol->x[873];
  mpc_socp__CPG_Prim.var3403[381] = mpc_socp__qoco_solver->sol->x[874];
  mpc_socp__CPG_Prim.var3403[382] = mpc_socp__qoco_solver->sol->x[875];
  mpc_socp__CPG_Prim.var3403[383] = mpc_socp__qoco_solver->sol->x[876];
  mpc_socp__CPG_Prim.var3403[384] = mpc_socp__qoco_solver->sol->x[877];
  mpc_socp__CPG_Prim.var3403[385] = mpc_socp__qoco_solver->sol->x[878];
  mpc_socp__CPG_Prim.var3403[386] = mpc_socp__qoco_solver->sol->x[879];
  mpc_socp__CPG_Prim.var3403[387] = mpc_socp__qoco_solver->sol->x[880];
  mpc_socp__CPG_Prim.var3403[388] = mpc_socp__qoco_solver->sol->x[881];
  mpc_socp__CPG_Prim.var3403[389] = mpc_socp__qoco_solver->sol->x[882];
  mpc_socp__CPG_Prim.var3403[390] = mpc_socp__qoco_solver->sol->x[883];
  mpc_socp__CPG_Prim.var3403[391] = mpc_socp__qoco_solver->sol->x[884];
  mpc_socp__CPG_Prim.var3403[392] = mpc_socp__qoco_solver->sol->x[885];
  mpc_socp__CPG_Prim.var3403[393] = mpc_socp__qoco_solver->sol->x[886];
  mpc_socp__CPG_Prim.var3403[394] = mpc_socp__qoco_solver->sol->x[887];
  mpc_socp__CPG_Prim.var3403[395] = mpc_socp__qoco_solver->sol->x[888];
  mpc_socp__CPG_Prim.var3403[396] = mpc_socp__qoco_solver->sol->x[889];
  mpc_socp__CPG_Prim.var3403[397] = mpc_socp__qoco_solver->sol->x[890];
  mpc_socp__CPG_Prim.var3403[398] = mpc_socp__qoco_solver->sol->x[891];
  mpc_socp__CPG_Prim.var3403[399] = mpc_socp__qoco_solver->sol->x[892];
  mpc_socp__CPG_Prim.var3403[400] = mpc_socp__qoco_solver->sol->x[893];
  mpc_socp__CPG_Prim.var3403[401] = mpc_socp__qoco_solver->sol->x[894];
  mpc_socp__CPG_Prim.var3403[402] = mpc_socp__qoco_solver->sol->x[895];
  mpc_socp__CPG_Prim.var3403[403] = mpc_socp__qoco_solver->sol->x[896];
  mpc_socp__CPG_Prim.var3403[404] = mpc_socp__qoco_solver->sol->x[897];
  mpc_socp__CPG_Prim.var3403[405] = mpc_socp__qoco_solver->sol->x[898];
  mpc_socp__CPG_Prim.var3403[406] = mpc_socp__qoco_solver->sol->x[899];
  mpc_socp__CPG_Prim.var3403[407] = mpc_socp__qoco_solver->sol->x[900];
  mpc_socp__CPG_Prim.var3403[408] = mpc_socp__qoco_solver->sol->x[901];
  mpc_socp__CPG_Prim.var3403[409] = mpc_socp__qoco_solver->sol->x[902];
  mpc_socp__CPG_Prim.var3403[410] = mpc_socp__qoco_solver->sol->x[903];
  mpc_socp__CPG_Prim.var3403[411] = mpc_socp__qoco_solver->sol->x[904];
  mpc_socp__CPG_Prim.var3403[412] = mpc_socp__qoco_solver->sol->x[905];
  mpc_socp__CPG_Prim.var3403[413] = mpc_socp__qoco_solver->sol->x[906];
  mpc_socp__CPG_Prim.var3403[414] = mpc_socp__qoco_solver->sol->x[907];
  mpc_socp__CPG_Prim.var3403[415] = mpc_socp__qoco_solver->sol->x[908];
  mpc_socp__CPG_Prim.var3403[416] = mpc_socp__qoco_solver->sol->x[909];
  mpc_socp__CPG_Prim.var3403[417] = mpc_socp__qoco_solver->sol->x[910];
  mpc_socp__CPG_Prim.var3403[418] = mpc_socp__qoco_solver->sol->x[911];
  mpc_socp__CPG_Prim.var3403[419] = mpc_socp__qoco_solver->sol->x[912];
  mpc_socp__CPG_Prim.var3404[0] = mpc_socp__qoco_solver->sol->x[913];
  mpc_socp__CPG_Prim.var3404[1] = mpc_socp__qoco_solver->sol->x[914];
  mpc_socp__CPG_Prim.var3404[2] = mpc_socp__qoco_solver->sol->x[915];
  mpc_socp__CPG_Prim.var3404[3] = mpc_socp__qoco_solver->sol->x[916];
  mpc_socp__CPG_Prim.var3404[4] = mpc_socp__qoco_solver->sol->x[917];
  mpc_socp__CPG_Prim.var3404[5] = mpc_socp__qoco_solver->sol->x[918];
  mpc_socp__CPG_Prim.var3404[6] = mpc_socp__qoco_solver->sol->x[919];
  mpc_socp__CPG_Prim.var3404[7] = mpc_socp__qoco_solver->sol->x[920];
  mpc_socp__CPG_Prim.var3404[8] = mpc_socp__qoco_solver->sol->x[921];
  mpc_socp__CPG_Prim.var3404[9] = mpc_socp__qoco_solver->sol->x[922];
  mpc_socp__CPG_Prim.var3404[10] = mpc_socp__qoco_solver->sol->x[923];
  mpc_socp__CPG_Prim.var3404[11] = mpc_socp__qoco_solver->sol->x[924];
  mpc_socp__CPG_Prim.var3404[12] = mpc_socp__qoco_solver->sol->x[925];
  mpc_socp__CPG_Prim.var3404[13] = mpc_socp__qoco_solver->sol->x[926];
  mpc_socp__CPG_Prim.var3404[14] = mpc_socp__qoco_solver->sol->x[927];
  mpc_socp__CPG_Prim.var3404[15] = mpc_socp__qoco_solver->sol->x[928];
  mpc_socp__CPG_Prim.var3404[16] = mpc_socp__qoco_solver->sol->x[929];
  mpc_socp__CPG_Prim.var3404[17] = mpc_socp__qoco_solver->sol->x[930];
  mpc_socp__CPG_Prim.var3404[18] = mpc_socp__qoco_solver->sol->x[931];
  mpc_socp__CPG_Prim.var3404[19] = mpc_socp__qoco_solver->sol->x[932];
  mpc_socp__CPG_Prim.var3404[20] = mpc_socp__qoco_solver->sol->x[933];
  mpc_socp__CPG_Prim.var3404[21] = mpc_socp__qoco_solver->sol->x[934];
  mpc_socp__CPG_Prim.var3404[22] = mpc_socp__qoco_solver->sol->x[935];
  mpc_socp__CPG_Prim.var3404[23] = mpc_socp__qoco_solver->sol->x[936];
  mpc_socp__CPG_Prim.var3404[24] = mpc_socp__qoco_solver->sol->x[937];
  mpc_socp__CPG_Prim.var3404[25] = mpc_socp__qoco_solver->sol->x[938];
  mpc_socp__CPG_Prim.var3404[26] = mpc_socp__qoco_solver->sol->x[939];
  mpc_socp__CPG_Prim.var3404[27] = mpc_socp__qoco_solver->sol->x[940];
  mpc_socp__CPG_Prim.var3404[28] = mpc_socp__qoco_solver->sol->x[941];
  mpc_socp__CPG_Prim.var3404[29] = mpc_socp__qoco_solver->sol->x[942];
  mpc_socp__CPG_Prim.var3404[30] = mpc_socp__qoco_solver->sol->x[943];
  mpc_socp__CPG_Prim.var3404[31] = mpc_socp__qoco_solver->sol->x[944];
  mpc_socp__CPG_Prim.var3404[32] = mpc_socp__qoco_solver->sol->x[945];
  mpc_socp__CPG_Prim.var3404[33] = mpc_socp__qoco_solver->sol->x[946];
  mpc_socp__CPG_Prim.var3404[34] = mpc_socp__qoco_solver->sol->x[947];
  mpc_socp__CPG_Prim.var3404[35] = mpc_socp__qoco_solver->sol->x[948];
  mpc_socp__CPG_Prim.var3404[36] = mpc_socp__qoco_solver->sol->x[949];
  mpc_socp__CPG_Prim.var3404[37] = mpc_socp__qoco_solver->sol->x[950];
  mpc_socp__CPG_Prim.var3404[38] = mpc_socp__qoco_solver->sol->x[951];
  mpc_socp__CPG_Prim.var3404[39] = mpc_socp__qoco_solver->sol->x[952];
  mpc_socp__CPG_Prim.var3404[40] = mpc_socp__qoco_solver->sol->x[953];
  mpc_socp__CPG_Prim.var3404[41] = mpc_socp__qoco_solver->sol->x[954];
  mpc_socp__CPG_Prim.var3404[42] = mpc_socp__qoco_solver->sol->x[955];
  mpc_socp__CPG_Prim.var3404[43] = mpc_socp__qoco_solver->sol->x[956];
  mpc_socp__CPG_Prim.var3404[44] = mpc_socp__qoco_solver->sol->x[957];
  mpc_socp__CPG_Prim.var3404[45] = mpc_socp__qoco_solver->sol->x[958];
  mpc_socp__CPG_Prim.var3404[46] = mpc_socp__qoco_solver->sol->x[959];
  mpc_socp__CPG_Prim.var3404[47] = mpc_socp__qoco_solver->sol->x[960];
  mpc_socp__CPG_Prim.var3404[48] = mpc_socp__qoco_solver->sol->x[961];
  mpc_socp__CPG_Prim.var3404[49] = mpc_socp__qoco_solver->sol->x[962];
  mpc_socp__CPG_Prim.var3404[50] = mpc_socp__qoco_solver->sol->x[963];
  mpc_socp__CPG_Prim.var3404[51] = mpc_socp__qoco_solver->sol->x[964];
  mpc_socp__CPG_Prim.var3404[52] = mpc_socp__qoco_solver->sol->x[965];
  mpc_socp__CPG_Prim.var3404[53] = mpc_socp__qoco_solver->sol->x[966];
  mpc_socp__CPG_Prim.var3404[54] = mpc_socp__qoco_solver->sol->x[967];
  mpc_socp__CPG_Prim.var3404[55] = mpc_socp__qoco_solver->sol->x[968];
  mpc_socp__CPG_Prim.var3404[56] = mpc_socp__qoco_solver->sol->x[969];
  mpc_socp__CPG_Prim.var3404[57] = mpc_socp__qoco_solver->sol->x[970];
  mpc_socp__CPG_Prim.var3404[58] = mpc_socp__qoco_solver->sol->x[971];
  mpc_socp__CPG_Prim.var3404[59] = mpc_socp__qoco_solver->sol->x[972];
  mpc_socp__CPG_Prim.var3404[60] = mpc_socp__qoco_solver->sol->x[973];
  mpc_socp__CPG_Prim.var3404[61] = mpc_socp__qoco_solver->sol->x[974];
  mpc_socp__CPG_Prim.var3404[62] = mpc_socp__qoco_solver->sol->x[975];
  mpc_socp__CPG_Prim.var3404[63] = mpc_socp__qoco_solver->sol->x[976];
  mpc_socp__CPG_Prim.var3404[64] = mpc_socp__qoco_solver->sol->x[977];
  mpc_socp__CPG_Prim.var3404[65] = mpc_socp__qoco_solver->sol->x[978];
  mpc_socp__CPG_Prim.var3404[66] = mpc_socp__qoco_solver->sol->x[979];
  mpc_socp__CPG_Prim.var3404[67] = mpc_socp__qoco_solver->sol->x[980];
  mpc_socp__CPG_Prim.var3404[68] = mpc_socp__qoco_solver->sol->x[981];
  mpc_socp__CPG_Prim.var3404[69] = mpc_socp__qoco_solver->sol->x[982];
  mpc_socp__CPG_Prim.var3404[70] = mpc_socp__qoco_solver->sol->x[983];
  mpc_socp__CPG_Prim.var3404[71] = mpc_socp__qoco_solver->sol->x[984];
  mpc_socp__CPG_Prim.var3404[72] = mpc_socp__qoco_solver->sol->x[985];
  mpc_socp__CPG_Prim.var3404[73] = mpc_socp__qoco_solver->sol->x[986];
  mpc_socp__CPG_Prim.var3404[74] = mpc_socp__qoco_solver->sol->x[987];
  mpc_socp__CPG_Prim.var3404[75] = mpc_socp__qoco_solver->sol->x[988];
  mpc_socp__CPG_Prim.var3404[76] = mpc_socp__qoco_solver->sol->x[989];
  mpc_socp__CPG_Prim.var3404[77] = mpc_socp__qoco_solver->sol->x[990];
  mpc_socp__CPG_Prim.var3404[78] = mpc_socp__qoco_solver->sol->x[991];
  mpc_socp__CPG_Prim.var3404[79] = mpc_socp__qoco_solver->sol->x[992];
  mpc_socp__CPG_Prim.var3404[80] = mpc_socp__qoco_solver->sol->x[993];
  mpc_socp__CPG_Prim.var3404[81] = mpc_socp__qoco_solver->sol->x[994];
  mpc_socp__CPG_Prim.var3404[82] = mpc_socp__qoco_solver->sol->x[995];
  mpc_socp__CPG_Prim.var3404[83] = mpc_socp__qoco_solver->sol->x[996];
  mpc_socp__CPG_Prim.var3404[84] = mpc_socp__qoco_solver->sol->x[997];
  mpc_socp__CPG_Prim.var3404[85] = mpc_socp__qoco_solver->sol->x[998];
  mpc_socp__CPG_Prim.var3404[86] = mpc_socp__qoco_solver->sol->x[999];
}

// Retrieve dual solution in terms of user-defined constraints
void mpc_socp__cpg_retrieve_dual(){
  mpc_socp__CPG_Dual.d0[0] = mpc_socp__qoco_solver->sol->y[493];
  mpc_socp__CPG_Dual.d0[1] = mpc_socp__qoco_solver->sol->y[494];
  mpc_socp__CPG_Dual.d0[2] = mpc_socp__qoco_solver->sol->y[495];
  mpc_socp__CPG_Dual.d0[3] = mpc_socp__qoco_solver->sol->y[496];
  mpc_socp__CPG_Dual.d0[4] = mpc_socp__qoco_solver->sol->y[497];
  mpc_socp__CPG_Dual.d0[5] = mpc_socp__qoco_solver->sol->y[498];
  mpc_socp__CPG_Dual.d0[6] = mpc_socp__qoco_solver->sol->y[499];
  mpc_socp__CPG_Dual.d0[7] = mpc_socp__qoco_solver->sol->y[500];
  mpc_socp__CPG_Dual.d0[8] = mpc_socp__qoco_solver->sol->y[501];
  mpc_socp__CPG_Dual.d0[9] = mpc_socp__qoco_solver->sol->y[502];
  mpc_socp__CPG_Dual.d0[10] = mpc_socp__qoco_solver->sol->y[503];
  mpc_socp__CPG_Dual.d0[11] = mpc_socp__qoco_solver->sol->y[504];
  mpc_socp__CPG_Dual.d0[12] = mpc_socp__qoco_solver->sol->y[505];
  mpc_socp__CPG_Dual.d0[13] = mpc_socp__qoco_solver->sol->y[506];
  mpc_socp__CPG_Dual.d1[0] = mpc_socp__qoco_solver->sol->y[507];
  mpc_socp__CPG_Dual.d1[1] = mpc_socp__qoco_solver->sol->y[508];
  mpc_socp__CPG_Dual.d1[2] = mpc_socp__qoco_solver->sol->y[509];
  mpc_socp__CPG_Dual.d1[3] = mpc_socp__qoco_solver->sol->y[510];
  mpc_socp__CPG_Dual.d1[4] = mpc_socp__qoco_solver->sol->y[511];
  mpc_socp__CPG_Dual.d1[5] = mpc_socp__qoco_solver->sol->y[512];
  mpc_socp__CPG_Dual.d1[6] = mpc_socp__qoco_solver->sol->y[513];
  mpc_socp__CPG_Dual.d1[7] = mpc_socp__qoco_solver->sol->y[514];
  mpc_socp__CPG_Dual.d1[8] = mpc_socp__qoco_solver->sol->y[515];
  mpc_socp__CPG_Dual.d1[9] = mpc_socp__qoco_solver->sol->y[516];
  mpc_socp__CPG_Dual.d1[10] = mpc_socp__qoco_solver->sol->y[517];
  mpc_socp__CPG_Dual.d1[11] = mpc_socp__qoco_solver->sol->y[518];
  mpc_socp__CPG_Dual.d1[12] = mpc_socp__qoco_solver->sol->y[519];
  mpc_socp__CPG_Dual.d1[13] = mpc_socp__qoco_solver->sol->y[520];
  mpc_socp__CPG_Dual.d2 = mpc_socp__qoco_solver->sol->z[0];
  mpc_socp__CPG_Dual.d3 = mpc_socp__qoco_solver->sol->z[1];
  mpc_socp__CPG_Dual.d4 = mpc_socp__qoco_solver->sol->z[2];
  mpc_socp__CPG_Dual.d5[0] = mpc_socp__qoco_solver->sol->y[521];
  mpc_socp__CPG_Dual.d5[1] = mpc_socp__qoco_solver->sol->y[522];
  mpc_socp__CPG_Dual.d5[2] = mpc_socp__qoco_solver->sol->y[523];
  mpc_socp__CPG_Dual.d5[3] = mpc_socp__qoco_solver->sol->y[524];
  mpc_socp__CPG_Dual.d5[4] = mpc_socp__qoco_solver->sol->y[525];
  mpc_socp__CPG_Dual.d5[5] = mpc_socp__qoco_solver->sol->y[526];
  mpc_socp__CPG_Dual.d5[6] = mpc_socp__qoco_solver->sol->y[527];
  mpc_socp__CPG_Dual.d5[7] = mpc_socp__qoco_solver->sol->y[528];
  mpc_socp__CPG_Dual.d5[8] = mpc_socp__qoco_solver->sol->y[529];
  mpc_socp__CPG_Dual.d5[9] = mpc_socp__qoco_solver->sol->y[530];
  mpc_socp__CPG_Dual.d5[10] = mpc_socp__qoco_solver->sol->y[531];
  mpc_socp__CPG_Dual.d5[11] = mpc_socp__qoco_solver->sol->y[532];
  mpc_socp__CPG_Dual.d5[12] = mpc_socp__qoco_solver->sol->y[533];
  mpc_socp__CPG_Dual.d5[13] = mpc_socp__qoco_solver->sol->y[534];
  mpc_socp__CPG_Dual.d6 = mpc_socp__qoco_solver->sol->z[3];
  mpc_socp__CPG_Dual.d7 = mpc_socp__qoco_solver->sol->z[4];
  mpc_socp__CPG_Dual.d8 = mpc_socp__qoco_solver->sol->z[5];
  mpc_socp__CPG_Dual.d9[0] = mpc_socp__qoco_solver->sol->y[535];
  mpc_socp__CPG_Dual.d9[1] = mpc_socp__qoco_solver->sol->y[536];
  mpc_socp__CPG_Dual.d9[2] = mpc_socp__qoco_solver->sol->y[537];
  mpc_socp__CPG_Dual.d9[3] = mpc_socp__qoco_solver->sol->y[538];
  mpc_socp__CPG_Dual.d9[4] = mpc_socp__qoco_solver->sol->y[539];
  mpc_socp__CPG_Dual.d9[5] = mpc_socp__qoco_solver->sol->y[540];
  mpc_socp__CPG_Dual.d9[6] = mpc_socp__qoco_solver->sol->y[541];
  mpc_socp__CPG_Dual.d9[7] = mpc_socp__qoco_solver->sol->y[542];
  mpc_socp__CPG_Dual.d9[8] = mpc_socp__qoco_solver->sol->y[543];
  mpc_socp__CPG_Dual.d9[9] = mpc_socp__qoco_solver->sol->y[544];
  mpc_socp__CPG_Dual.d9[10] = mpc_socp__qoco_solver->sol->y[545];
  mpc_socp__CPG_Dual.d9[11] = mpc_socp__qoco_solver->sol->y[546];
  mpc_socp__CPG_Dual.d9[12] = mpc_socp__qoco_solver->sol->y[547];
  mpc_socp__CPG_Dual.d9[13] = mpc_socp__qoco_solver->sol->y[548];
  mpc_socp__CPG_Dual.d10 = mpc_socp__qoco_solver->sol->z[6];
  mpc_socp__CPG_Dual.d11 = mpc_socp__qoco_solver->sol->z[7];
  mpc_socp__CPG_Dual.d12 = mpc_socp__qoco_solver->sol->z[8];
  mpc_socp__CPG_Dual.d13[0] = mpc_socp__qoco_solver->sol->y[549];
  mpc_socp__CPG_Dual.d13[1] = mpc_socp__qoco_solver->sol->y[550];
  mpc_socp__CPG_Dual.d13[2] = mpc_socp__qoco_solver->sol->y[551];
  mpc_socp__CPG_Dual.d13[3] = mpc_socp__qoco_solver->sol->y[552];
  mpc_socp__CPG_Dual.d13[4] = mpc_socp__qoco_solver->sol->y[553];
  mpc_socp__CPG_Dual.d13[5] = mpc_socp__qoco_solver->sol->y[554];
  mpc_socp__CPG_Dual.d13[6] = mpc_socp__qoco_solver->sol->y[555];
  mpc_socp__CPG_Dual.d13[7] = mpc_socp__qoco_solver->sol->y[556];
  mpc_socp__CPG_Dual.d13[8] = mpc_socp__qoco_solver->sol->y[557];
  mpc_socp__CPG_Dual.d13[9] = mpc_socp__qoco_solver->sol->y[558];
  mpc_socp__CPG_Dual.d13[10] = mpc_socp__qoco_solver->sol->y[559];
  mpc_socp__CPG_Dual.d13[11] = mpc_socp__qoco_solver->sol->y[560];
  mpc_socp__CPG_Dual.d13[12] = mpc_socp__qoco_solver->sol->y[561];
  mpc_socp__CPG_Dual.d13[13] = mpc_socp__qoco_solver->sol->y[562];
  mpc_socp__CPG_Dual.d14 = mpc_socp__qoco_solver->sol->z[9];
  mpc_socp__CPG_Dual.d15 = mpc_socp__qoco_solver->sol->z[10];
  mpc_socp__CPG_Dual.d16 = mpc_socp__qoco_solver->sol->z[11];
  mpc_socp__CPG_Dual.d17[0] = mpc_socp__qoco_solver->sol->y[563];
  mpc_socp__CPG_Dual.d17[1] = mpc_socp__qoco_solver->sol->y[564];
  mpc_socp__CPG_Dual.d17[2] = mpc_socp__qoco_solver->sol->y[565];
  mpc_socp__CPG_Dual.d17[3] = mpc_socp__qoco_solver->sol->y[566];
  mpc_socp__CPG_Dual.d17[4] = mpc_socp__qoco_solver->sol->y[567];
  mpc_socp__CPG_Dual.d17[5] = mpc_socp__qoco_solver->sol->y[568];
  mpc_socp__CPG_Dual.d17[6] = mpc_socp__qoco_solver->sol->y[569];
  mpc_socp__CPG_Dual.d17[7] = mpc_socp__qoco_solver->sol->y[570];
  mpc_socp__CPG_Dual.d17[8] = mpc_socp__qoco_solver->sol->y[571];
  mpc_socp__CPG_Dual.d17[9] = mpc_socp__qoco_solver->sol->y[572];
  mpc_socp__CPG_Dual.d17[10] = mpc_socp__qoco_solver->sol->y[573];
  mpc_socp__CPG_Dual.d17[11] = mpc_socp__qoco_solver->sol->y[574];
  mpc_socp__CPG_Dual.d17[12] = mpc_socp__qoco_solver->sol->y[575];
  mpc_socp__CPG_Dual.d17[13] = mpc_socp__qoco_solver->sol->y[576];
  mpc_socp__CPG_Dual.d18 = mpc_socp__qoco_solver->sol->z[12];
  mpc_socp__CPG_Dual.d19 = mpc_socp__qoco_solver->sol->z[13];
  mpc_socp__CPG_Dual.d20 = mpc_socp__qoco_solver->sol->z[14];
  mpc_socp__CPG_Dual.d21[0] = mpc_socp__qoco_solver->sol->y[577];
  mpc_socp__CPG_Dual.d21[1] = mpc_socp__qoco_solver->sol->y[578];
  mpc_socp__CPG_Dual.d21[2] = mpc_socp__qoco_solver->sol->y[579];
  mpc_socp__CPG_Dual.d21[3] = mpc_socp__qoco_solver->sol->y[580];
  mpc_socp__CPG_Dual.d21[4] = mpc_socp__qoco_solver->sol->y[581];
  mpc_socp__CPG_Dual.d21[5] = mpc_socp__qoco_solver->sol->y[582];
  mpc_socp__CPG_Dual.d21[6] = mpc_socp__qoco_solver->sol->y[583];
  mpc_socp__CPG_Dual.d21[7] = mpc_socp__qoco_solver->sol->y[584];
  mpc_socp__CPG_Dual.d21[8] = mpc_socp__qoco_solver->sol->y[585];
  mpc_socp__CPG_Dual.d21[9] = mpc_socp__qoco_solver->sol->y[586];
  mpc_socp__CPG_Dual.d21[10] = mpc_socp__qoco_solver->sol->y[587];
  mpc_socp__CPG_Dual.d21[11] = mpc_socp__qoco_solver->sol->y[588];
  mpc_socp__CPG_Dual.d21[12] = mpc_socp__qoco_solver->sol->y[589];
  mpc_socp__CPG_Dual.d21[13] = mpc_socp__qoco_solver->sol->y[590];
  mpc_socp__CPG_Dual.d22 = mpc_socp__qoco_solver->sol->z[15];
  mpc_socp__CPG_Dual.d23 = mpc_socp__qoco_solver->sol->z[16];
  mpc_socp__CPG_Dual.d24 = mpc_socp__qoco_solver->sol->z[17];
  mpc_socp__CPG_Dual.d25[0] = mpc_socp__qoco_solver->sol->y[591];
  mpc_socp__CPG_Dual.d25[1] = mpc_socp__qoco_solver->sol->y[592];
  mpc_socp__CPG_Dual.d25[2] = mpc_socp__qoco_solver->sol->y[593];
  mpc_socp__CPG_Dual.d25[3] = mpc_socp__qoco_solver->sol->y[594];
  mpc_socp__CPG_Dual.d25[4] = mpc_socp__qoco_solver->sol->y[595];
  mpc_socp__CPG_Dual.d25[5] = mpc_socp__qoco_solver->sol->y[596];
  mpc_socp__CPG_Dual.d25[6] = mpc_socp__qoco_solver->sol->y[597];
  mpc_socp__CPG_Dual.d25[7] = mpc_socp__qoco_solver->sol->y[598];
  mpc_socp__CPG_Dual.d25[8] = mpc_socp__qoco_solver->sol->y[599];
  mpc_socp__CPG_Dual.d25[9] = mpc_socp__qoco_solver->sol->y[600];
  mpc_socp__CPG_Dual.d25[10] = mpc_socp__qoco_solver->sol->y[601];
  mpc_socp__CPG_Dual.d25[11] = mpc_socp__qoco_solver->sol->y[602];
  mpc_socp__CPG_Dual.d25[12] = mpc_socp__qoco_solver->sol->y[603];
  mpc_socp__CPG_Dual.d25[13] = mpc_socp__qoco_solver->sol->y[604];
  mpc_socp__CPG_Dual.d26 = mpc_socp__qoco_solver->sol->z[18];
  mpc_socp__CPG_Dual.d27 = mpc_socp__qoco_solver->sol->z[19];
  mpc_socp__CPG_Dual.d28 = mpc_socp__qoco_solver->sol->z[20];
  mpc_socp__CPG_Dual.d29[0] = mpc_socp__qoco_solver->sol->y[605];
  mpc_socp__CPG_Dual.d29[1] = mpc_socp__qoco_solver->sol->y[606];
  mpc_socp__CPG_Dual.d29[2] = mpc_socp__qoco_solver->sol->y[607];
  mpc_socp__CPG_Dual.d29[3] = mpc_socp__qoco_solver->sol->y[608];
  mpc_socp__CPG_Dual.d29[4] = mpc_socp__qoco_solver->sol->y[609];
  mpc_socp__CPG_Dual.d29[5] = mpc_socp__qoco_solver->sol->y[610];
  mpc_socp__CPG_Dual.d29[6] = mpc_socp__qoco_solver->sol->y[611];
  mpc_socp__CPG_Dual.d29[7] = mpc_socp__qoco_solver->sol->y[612];
  mpc_socp__CPG_Dual.d29[8] = mpc_socp__qoco_solver->sol->y[613];
  mpc_socp__CPG_Dual.d29[9] = mpc_socp__qoco_solver->sol->y[614];
  mpc_socp__CPG_Dual.d29[10] = mpc_socp__qoco_solver->sol->y[615];
  mpc_socp__CPG_Dual.d29[11] = mpc_socp__qoco_solver->sol->y[616];
  mpc_socp__CPG_Dual.d29[12] = mpc_socp__qoco_solver->sol->y[617];
  mpc_socp__CPG_Dual.d29[13] = mpc_socp__qoco_solver->sol->y[618];
  mpc_socp__CPG_Dual.d30 = mpc_socp__qoco_solver->sol->z[21];
  mpc_socp__CPG_Dual.d31 = mpc_socp__qoco_solver->sol->z[22];
  mpc_socp__CPG_Dual.d32 = mpc_socp__qoco_solver->sol->z[23];
  mpc_socp__CPG_Dual.d33[0] = mpc_socp__qoco_solver->sol->y[619];
  mpc_socp__CPG_Dual.d33[1] = mpc_socp__qoco_solver->sol->y[620];
  mpc_socp__CPG_Dual.d33[2] = mpc_socp__qoco_solver->sol->y[621];
  mpc_socp__CPG_Dual.d33[3] = mpc_socp__qoco_solver->sol->y[622];
  mpc_socp__CPG_Dual.d33[4] = mpc_socp__qoco_solver->sol->y[623];
  mpc_socp__CPG_Dual.d33[5] = mpc_socp__qoco_solver->sol->y[624];
  mpc_socp__CPG_Dual.d33[6] = mpc_socp__qoco_solver->sol->y[625];
  mpc_socp__CPG_Dual.d33[7] = mpc_socp__qoco_solver->sol->y[626];
  mpc_socp__CPG_Dual.d33[8] = mpc_socp__qoco_solver->sol->y[627];
  mpc_socp__CPG_Dual.d33[9] = mpc_socp__qoco_solver->sol->y[628];
  mpc_socp__CPG_Dual.d33[10] = mpc_socp__qoco_solver->sol->y[629];
  mpc_socp__CPG_Dual.d33[11] = mpc_socp__qoco_solver->sol->y[630];
  mpc_socp__CPG_Dual.d33[12] = mpc_socp__qoco_solver->sol->y[631];
  mpc_socp__CPG_Dual.d33[13] = mpc_socp__qoco_solver->sol->y[632];
  mpc_socp__CPG_Dual.d34 = mpc_socp__qoco_solver->sol->z[24];
  mpc_socp__CPG_Dual.d35 = mpc_socp__qoco_solver->sol->z[25];
  mpc_socp__CPG_Dual.d36 = mpc_socp__qoco_solver->sol->z[26];
  mpc_socp__CPG_Dual.d37[0] = mpc_socp__qoco_solver->sol->y[633];
  mpc_socp__CPG_Dual.d37[1] = mpc_socp__qoco_solver->sol->y[634];
  mpc_socp__CPG_Dual.d37[2] = mpc_socp__qoco_solver->sol->y[635];
  mpc_socp__CPG_Dual.d37[3] = mpc_socp__qoco_solver->sol->y[636];
  mpc_socp__CPG_Dual.d37[4] = mpc_socp__qoco_solver->sol->y[637];
  mpc_socp__CPG_Dual.d37[5] = mpc_socp__qoco_solver->sol->y[638];
  mpc_socp__CPG_Dual.d37[6] = mpc_socp__qoco_solver->sol->y[639];
  mpc_socp__CPG_Dual.d37[7] = mpc_socp__qoco_solver->sol->y[640];
  mpc_socp__CPG_Dual.d37[8] = mpc_socp__qoco_solver->sol->y[641];
  mpc_socp__CPG_Dual.d37[9] = mpc_socp__qoco_solver->sol->y[642];
  mpc_socp__CPG_Dual.d37[10] = mpc_socp__qoco_solver->sol->y[643];
  mpc_socp__CPG_Dual.d37[11] = mpc_socp__qoco_solver->sol->y[644];
  mpc_socp__CPG_Dual.d37[12] = mpc_socp__qoco_solver->sol->y[645];
  mpc_socp__CPG_Dual.d37[13] = mpc_socp__qoco_solver->sol->y[646];
  mpc_socp__CPG_Dual.d38 = mpc_socp__qoco_solver->sol->z[27];
  mpc_socp__CPG_Dual.d39 = mpc_socp__qoco_solver->sol->z[28];
  mpc_socp__CPG_Dual.d40 = mpc_socp__qoco_solver->sol->z[29];
  mpc_socp__CPG_Dual.d41[0] = mpc_socp__qoco_solver->sol->y[647];
  mpc_socp__CPG_Dual.d41[1] = mpc_socp__qoco_solver->sol->y[648];
  mpc_socp__CPG_Dual.d41[2] = mpc_socp__qoco_solver->sol->y[649];
  mpc_socp__CPG_Dual.d41[3] = mpc_socp__qoco_solver->sol->y[650];
  mpc_socp__CPG_Dual.d41[4] = mpc_socp__qoco_solver->sol->y[651];
  mpc_socp__CPG_Dual.d41[5] = mpc_socp__qoco_solver->sol->y[652];
  mpc_socp__CPG_Dual.d41[6] = mpc_socp__qoco_solver->sol->y[653];
  mpc_socp__CPG_Dual.d41[7] = mpc_socp__qoco_solver->sol->y[654];
  mpc_socp__CPG_Dual.d41[8] = mpc_socp__qoco_solver->sol->y[655];
  mpc_socp__CPG_Dual.d41[9] = mpc_socp__qoco_solver->sol->y[656];
  mpc_socp__CPG_Dual.d41[10] = mpc_socp__qoco_solver->sol->y[657];
  mpc_socp__CPG_Dual.d41[11] = mpc_socp__qoco_solver->sol->y[658];
  mpc_socp__CPG_Dual.d41[12] = mpc_socp__qoco_solver->sol->y[659];
  mpc_socp__CPG_Dual.d41[13] = mpc_socp__qoco_solver->sol->y[660];
  mpc_socp__CPG_Dual.d42 = mpc_socp__qoco_solver->sol->z[30];
  mpc_socp__CPG_Dual.d43 = mpc_socp__qoco_solver->sol->z[31];
  mpc_socp__CPG_Dual.d44 = mpc_socp__qoco_solver->sol->z[32];
  mpc_socp__CPG_Dual.d45[0] = mpc_socp__qoco_solver->sol->y[661];
  mpc_socp__CPG_Dual.d45[1] = mpc_socp__qoco_solver->sol->y[662];
  mpc_socp__CPG_Dual.d45[2] = mpc_socp__qoco_solver->sol->y[663];
  mpc_socp__CPG_Dual.d45[3] = mpc_socp__qoco_solver->sol->y[664];
  mpc_socp__CPG_Dual.d45[4] = mpc_socp__qoco_solver->sol->y[665];
  mpc_socp__CPG_Dual.d45[5] = mpc_socp__qoco_solver->sol->y[666];
  mpc_socp__CPG_Dual.d45[6] = mpc_socp__qoco_solver->sol->y[667];
  mpc_socp__CPG_Dual.d45[7] = mpc_socp__qoco_solver->sol->y[668];
  mpc_socp__CPG_Dual.d45[8] = mpc_socp__qoco_solver->sol->y[669];
  mpc_socp__CPG_Dual.d45[9] = mpc_socp__qoco_solver->sol->y[670];
  mpc_socp__CPG_Dual.d45[10] = mpc_socp__qoco_solver->sol->y[671];
  mpc_socp__CPG_Dual.d45[11] = mpc_socp__qoco_solver->sol->y[672];
  mpc_socp__CPG_Dual.d45[12] = mpc_socp__qoco_solver->sol->y[673];
  mpc_socp__CPG_Dual.d45[13] = mpc_socp__qoco_solver->sol->y[674];
  mpc_socp__CPG_Dual.d46 = mpc_socp__qoco_solver->sol->z[33];
  mpc_socp__CPG_Dual.d47 = mpc_socp__qoco_solver->sol->z[34];
  mpc_socp__CPG_Dual.d48 = mpc_socp__qoco_solver->sol->z[35];
  mpc_socp__CPG_Dual.d49[0] = mpc_socp__qoco_solver->sol->y[675];
  mpc_socp__CPG_Dual.d49[1] = mpc_socp__qoco_solver->sol->y[676];
  mpc_socp__CPG_Dual.d49[2] = mpc_socp__qoco_solver->sol->y[677];
  mpc_socp__CPG_Dual.d49[3] = mpc_socp__qoco_solver->sol->y[678];
  mpc_socp__CPG_Dual.d49[4] = mpc_socp__qoco_solver->sol->y[679];
  mpc_socp__CPG_Dual.d49[5] = mpc_socp__qoco_solver->sol->y[680];
  mpc_socp__CPG_Dual.d49[6] = mpc_socp__qoco_solver->sol->y[681];
  mpc_socp__CPG_Dual.d49[7] = mpc_socp__qoco_solver->sol->y[682];
  mpc_socp__CPG_Dual.d49[8] = mpc_socp__qoco_solver->sol->y[683];
  mpc_socp__CPG_Dual.d49[9] = mpc_socp__qoco_solver->sol->y[684];
  mpc_socp__CPG_Dual.d49[10] = mpc_socp__qoco_solver->sol->y[685];
  mpc_socp__CPG_Dual.d49[11] = mpc_socp__qoco_solver->sol->y[686];
  mpc_socp__CPG_Dual.d49[12] = mpc_socp__qoco_solver->sol->y[687];
  mpc_socp__CPG_Dual.d49[13] = mpc_socp__qoco_solver->sol->y[688];
  mpc_socp__CPG_Dual.d50 = mpc_socp__qoco_solver->sol->z[36];
  mpc_socp__CPG_Dual.d51 = mpc_socp__qoco_solver->sol->z[37];
  mpc_socp__CPG_Dual.d52 = mpc_socp__qoco_solver->sol->z[38];
  mpc_socp__CPG_Dual.d53[0] = mpc_socp__qoco_solver->sol->y[689];
  mpc_socp__CPG_Dual.d53[1] = mpc_socp__qoco_solver->sol->y[690];
  mpc_socp__CPG_Dual.d53[2] = mpc_socp__qoco_solver->sol->y[691];
  mpc_socp__CPG_Dual.d53[3] = mpc_socp__qoco_solver->sol->y[692];
  mpc_socp__CPG_Dual.d53[4] = mpc_socp__qoco_solver->sol->y[693];
  mpc_socp__CPG_Dual.d53[5] = mpc_socp__qoco_solver->sol->y[694];
  mpc_socp__CPG_Dual.d53[6] = mpc_socp__qoco_solver->sol->y[695];
  mpc_socp__CPG_Dual.d53[7] = mpc_socp__qoco_solver->sol->y[696];
  mpc_socp__CPG_Dual.d53[8] = mpc_socp__qoco_solver->sol->y[697];
  mpc_socp__CPG_Dual.d53[9] = mpc_socp__qoco_solver->sol->y[698];
  mpc_socp__CPG_Dual.d53[10] = mpc_socp__qoco_solver->sol->y[699];
  mpc_socp__CPG_Dual.d53[11] = mpc_socp__qoco_solver->sol->y[700];
  mpc_socp__CPG_Dual.d53[12] = mpc_socp__qoco_solver->sol->y[701];
  mpc_socp__CPG_Dual.d53[13] = mpc_socp__qoco_solver->sol->y[702];
  mpc_socp__CPG_Dual.d54 = mpc_socp__qoco_solver->sol->z[39];
  mpc_socp__CPG_Dual.d55 = mpc_socp__qoco_solver->sol->z[40];
  mpc_socp__CPG_Dual.d56 = mpc_socp__qoco_solver->sol->z[41];
  mpc_socp__CPG_Dual.d57[0] = mpc_socp__qoco_solver->sol->y[703];
  mpc_socp__CPG_Dual.d57[1] = mpc_socp__qoco_solver->sol->y[704];
  mpc_socp__CPG_Dual.d57[2] = mpc_socp__qoco_solver->sol->y[705];
  mpc_socp__CPG_Dual.d57[3] = mpc_socp__qoco_solver->sol->y[706];
  mpc_socp__CPG_Dual.d57[4] = mpc_socp__qoco_solver->sol->y[707];
  mpc_socp__CPG_Dual.d57[5] = mpc_socp__qoco_solver->sol->y[708];
  mpc_socp__CPG_Dual.d57[6] = mpc_socp__qoco_solver->sol->y[709];
  mpc_socp__CPG_Dual.d57[7] = mpc_socp__qoco_solver->sol->y[710];
  mpc_socp__CPG_Dual.d57[8] = mpc_socp__qoco_solver->sol->y[711];
  mpc_socp__CPG_Dual.d57[9] = mpc_socp__qoco_solver->sol->y[712];
  mpc_socp__CPG_Dual.d57[10] = mpc_socp__qoco_solver->sol->y[713];
  mpc_socp__CPG_Dual.d57[11] = mpc_socp__qoco_solver->sol->y[714];
  mpc_socp__CPG_Dual.d57[12] = mpc_socp__qoco_solver->sol->y[715];
  mpc_socp__CPG_Dual.d57[13] = mpc_socp__qoco_solver->sol->y[716];
  mpc_socp__CPG_Dual.d58 = mpc_socp__qoco_solver->sol->z[42];
  mpc_socp__CPG_Dual.d59 = mpc_socp__qoco_solver->sol->z[43];
  mpc_socp__CPG_Dual.d60 = mpc_socp__qoco_solver->sol->z[44];
  mpc_socp__CPG_Dual.d61[0] = mpc_socp__qoco_solver->sol->y[717];
  mpc_socp__CPG_Dual.d61[1] = mpc_socp__qoco_solver->sol->y[718];
  mpc_socp__CPG_Dual.d61[2] = mpc_socp__qoco_solver->sol->y[719];
  mpc_socp__CPG_Dual.d61[3] = mpc_socp__qoco_solver->sol->y[720];
  mpc_socp__CPG_Dual.d61[4] = mpc_socp__qoco_solver->sol->y[721];
  mpc_socp__CPG_Dual.d61[5] = mpc_socp__qoco_solver->sol->y[722];
  mpc_socp__CPG_Dual.d61[6] = mpc_socp__qoco_solver->sol->y[723];
  mpc_socp__CPG_Dual.d61[7] = mpc_socp__qoco_solver->sol->y[724];
  mpc_socp__CPG_Dual.d61[8] = mpc_socp__qoco_solver->sol->y[725];
  mpc_socp__CPG_Dual.d61[9] = mpc_socp__qoco_solver->sol->y[726];
  mpc_socp__CPG_Dual.d61[10] = mpc_socp__qoco_solver->sol->y[727];
  mpc_socp__CPG_Dual.d61[11] = mpc_socp__qoco_solver->sol->y[728];
  mpc_socp__CPG_Dual.d61[12] = mpc_socp__qoco_solver->sol->y[729];
  mpc_socp__CPG_Dual.d61[13] = mpc_socp__qoco_solver->sol->y[730];
  mpc_socp__CPG_Dual.d62 = mpc_socp__qoco_solver->sol->z[45];
  mpc_socp__CPG_Dual.d63 = mpc_socp__qoco_solver->sol->z[46];
  mpc_socp__CPG_Dual.d64 = mpc_socp__qoco_solver->sol->z[47];
  mpc_socp__CPG_Dual.d65[0] = mpc_socp__qoco_solver->sol->y[731];
  mpc_socp__CPG_Dual.d65[1] = mpc_socp__qoco_solver->sol->y[732];
  mpc_socp__CPG_Dual.d65[2] = mpc_socp__qoco_solver->sol->y[733];
  mpc_socp__CPG_Dual.d65[3] = mpc_socp__qoco_solver->sol->y[734];
  mpc_socp__CPG_Dual.d65[4] = mpc_socp__qoco_solver->sol->y[735];
  mpc_socp__CPG_Dual.d65[5] = mpc_socp__qoco_solver->sol->y[736];
  mpc_socp__CPG_Dual.d65[6] = mpc_socp__qoco_solver->sol->y[737];
  mpc_socp__CPG_Dual.d65[7] = mpc_socp__qoco_solver->sol->y[738];
  mpc_socp__CPG_Dual.d65[8] = mpc_socp__qoco_solver->sol->y[739];
  mpc_socp__CPG_Dual.d65[9] = mpc_socp__qoco_solver->sol->y[740];
  mpc_socp__CPG_Dual.d65[10] = mpc_socp__qoco_solver->sol->y[741];
  mpc_socp__CPG_Dual.d65[11] = mpc_socp__qoco_solver->sol->y[742];
  mpc_socp__CPG_Dual.d65[12] = mpc_socp__qoco_solver->sol->y[743];
  mpc_socp__CPG_Dual.d65[13] = mpc_socp__qoco_solver->sol->y[744];
  mpc_socp__CPG_Dual.d66 = mpc_socp__qoco_solver->sol->z[48];
  mpc_socp__CPG_Dual.d67 = mpc_socp__qoco_solver->sol->z[49];
  mpc_socp__CPG_Dual.d68 = mpc_socp__qoco_solver->sol->z[50];
  mpc_socp__CPG_Dual.d69[0] = mpc_socp__qoco_solver->sol->y[745];
  mpc_socp__CPG_Dual.d69[1] = mpc_socp__qoco_solver->sol->y[746];
  mpc_socp__CPG_Dual.d69[2] = mpc_socp__qoco_solver->sol->y[747];
  mpc_socp__CPG_Dual.d69[3] = mpc_socp__qoco_solver->sol->y[748];
  mpc_socp__CPG_Dual.d69[4] = mpc_socp__qoco_solver->sol->y[749];
  mpc_socp__CPG_Dual.d69[5] = mpc_socp__qoco_solver->sol->y[750];
  mpc_socp__CPG_Dual.d69[6] = mpc_socp__qoco_solver->sol->y[751];
  mpc_socp__CPG_Dual.d69[7] = mpc_socp__qoco_solver->sol->y[752];
  mpc_socp__CPG_Dual.d69[8] = mpc_socp__qoco_solver->sol->y[753];
  mpc_socp__CPG_Dual.d69[9] = mpc_socp__qoco_solver->sol->y[754];
  mpc_socp__CPG_Dual.d69[10] = mpc_socp__qoco_solver->sol->y[755];
  mpc_socp__CPG_Dual.d69[11] = mpc_socp__qoco_solver->sol->y[756];
  mpc_socp__CPG_Dual.d69[12] = mpc_socp__qoco_solver->sol->y[757];
  mpc_socp__CPG_Dual.d69[13] = mpc_socp__qoco_solver->sol->y[758];
  mpc_socp__CPG_Dual.d70 = mpc_socp__qoco_solver->sol->z[51];
  mpc_socp__CPG_Dual.d71 = mpc_socp__qoco_solver->sol->z[52];
  mpc_socp__CPG_Dual.d72 = mpc_socp__qoco_solver->sol->z[53];
  mpc_socp__CPG_Dual.d73[0] = mpc_socp__qoco_solver->sol->y[759];
  mpc_socp__CPG_Dual.d73[1] = mpc_socp__qoco_solver->sol->y[760];
  mpc_socp__CPG_Dual.d73[2] = mpc_socp__qoco_solver->sol->y[761];
  mpc_socp__CPG_Dual.d73[3] = mpc_socp__qoco_solver->sol->y[762];
  mpc_socp__CPG_Dual.d73[4] = mpc_socp__qoco_solver->sol->y[763];
  mpc_socp__CPG_Dual.d73[5] = mpc_socp__qoco_solver->sol->y[764];
  mpc_socp__CPG_Dual.d73[6] = mpc_socp__qoco_solver->sol->y[765];
  mpc_socp__CPG_Dual.d73[7] = mpc_socp__qoco_solver->sol->y[766];
  mpc_socp__CPG_Dual.d73[8] = mpc_socp__qoco_solver->sol->y[767];
  mpc_socp__CPG_Dual.d73[9] = mpc_socp__qoco_solver->sol->y[768];
  mpc_socp__CPG_Dual.d73[10] = mpc_socp__qoco_solver->sol->y[769];
  mpc_socp__CPG_Dual.d73[11] = mpc_socp__qoco_solver->sol->y[770];
  mpc_socp__CPG_Dual.d73[12] = mpc_socp__qoco_solver->sol->y[771];
  mpc_socp__CPG_Dual.d73[13] = mpc_socp__qoco_solver->sol->y[772];
  mpc_socp__CPG_Dual.d74 = mpc_socp__qoco_solver->sol->z[54];
  mpc_socp__CPG_Dual.d75 = mpc_socp__qoco_solver->sol->z[55];
  mpc_socp__CPG_Dual.d76 = mpc_socp__qoco_solver->sol->z[56];
  mpc_socp__CPG_Dual.d77[0] = mpc_socp__qoco_solver->sol->y[773];
  mpc_socp__CPG_Dual.d77[1] = mpc_socp__qoco_solver->sol->y[774];
  mpc_socp__CPG_Dual.d77[2] = mpc_socp__qoco_solver->sol->y[775];
  mpc_socp__CPG_Dual.d77[3] = mpc_socp__qoco_solver->sol->y[776];
  mpc_socp__CPG_Dual.d77[4] = mpc_socp__qoco_solver->sol->y[777];
  mpc_socp__CPG_Dual.d77[5] = mpc_socp__qoco_solver->sol->y[778];
  mpc_socp__CPG_Dual.d77[6] = mpc_socp__qoco_solver->sol->y[779];
  mpc_socp__CPG_Dual.d77[7] = mpc_socp__qoco_solver->sol->y[780];
  mpc_socp__CPG_Dual.d77[8] = mpc_socp__qoco_solver->sol->y[781];
  mpc_socp__CPG_Dual.d77[9] = mpc_socp__qoco_solver->sol->y[782];
  mpc_socp__CPG_Dual.d77[10] = mpc_socp__qoco_solver->sol->y[783];
  mpc_socp__CPG_Dual.d77[11] = mpc_socp__qoco_solver->sol->y[784];
  mpc_socp__CPG_Dual.d77[12] = mpc_socp__qoco_solver->sol->y[785];
  mpc_socp__CPG_Dual.d77[13] = mpc_socp__qoco_solver->sol->y[786];
  mpc_socp__CPG_Dual.d78 = mpc_socp__qoco_solver->sol->z[57];
  mpc_socp__CPG_Dual.d79 = mpc_socp__qoco_solver->sol->z[58];
  mpc_socp__CPG_Dual.d80 = mpc_socp__qoco_solver->sol->z[59];
  mpc_socp__CPG_Dual.d81[0] = mpc_socp__qoco_solver->sol->y[787];
  mpc_socp__CPG_Dual.d81[1] = mpc_socp__qoco_solver->sol->y[788];
  mpc_socp__CPG_Dual.d81[2] = mpc_socp__qoco_solver->sol->y[789];
  mpc_socp__CPG_Dual.d81[3] = mpc_socp__qoco_solver->sol->y[790];
  mpc_socp__CPG_Dual.d81[4] = mpc_socp__qoco_solver->sol->y[791];
  mpc_socp__CPG_Dual.d81[5] = mpc_socp__qoco_solver->sol->y[792];
  mpc_socp__CPG_Dual.d81[6] = mpc_socp__qoco_solver->sol->y[793];
  mpc_socp__CPG_Dual.d81[7] = mpc_socp__qoco_solver->sol->y[794];
  mpc_socp__CPG_Dual.d81[8] = mpc_socp__qoco_solver->sol->y[795];
  mpc_socp__CPG_Dual.d81[9] = mpc_socp__qoco_solver->sol->y[796];
  mpc_socp__CPG_Dual.d81[10] = mpc_socp__qoco_solver->sol->y[797];
  mpc_socp__CPG_Dual.d81[11] = mpc_socp__qoco_solver->sol->y[798];
  mpc_socp__CPG_Dual.d81[12] = mpc_socp__qoco_solver->sol->y[799];
  mpc_socp__CPG_Dual.d81[13] = mpc_socp__qoco_solver->sol->y[800];
  mpc_socp__CPG_Dual.d82 = mpc_socp__qoco_solver->sol->z[60];
  mpc_socp__CPG_Dual.d83 = mpc_socp__qoco_solver->sol->z[61];
  mpc_socp__CPG_Dual.d84 = mpc_socp__qoco_solver->sol->z[62];
  mpc_socp__CPG_Dual.d85[0] = mpc_socp__qoco_solver->sol->y[801];
  mpc_socp__CPG_Dual.d85[1] = mpc_socp__qoco_solver->sol->y[802];
  mpc_socp__CPG_Dual.d85[2] = mpc_socp__qoco_solver->sol->y[803];
  mpc_socp__CPG_Dual.d85[3] = mpc_socp__qoco_solver->sol->y[804];
  mpc_socp__CPG_Dual.d85[4] = mpc_socp__qoco_solver->sol->y[805];
  mpc_socp__CPG_Dual.d85[5] = mpc_socp__qoco_solver->sol->y[806];
  mpc_socp__CPG_Dual.d85[6] = mpc_socp__qoco_solver->sol->y[807];
  mpc_socp__CPG_Dual.d85[7] = mpc_socp__qoco_solver->sol->y[808];
  mpc_socp__CPG_Dual.d85[8] = mpc_socp__qoco_solver->sol->y[809];
  mpc_socp__CPG_Dual.d85[9] = mpc_socp__qoco_solver->sol->y[810];
  mpc_socp__CPG_Dual.d85[10] = mpc_socp__qoco_solver->sol->y[811];
  mpc_socp__CPG_Dual.d85[11] = mpc_socp__qoco_solver->sol->y[812];
  mpc_socp__CPG_Dual.d85[12] = mpc_socp__qoco_solver->sol->y[813];
  mpc_socp__CPG_Dual.d85[13] = mpc_socp__qoco_solver->sol->y[814];
  mpc_socp__CPG_Dual.d86 = mpc_socp__qoco_solver->sol->z[63];
  mpc_socp__CPG_Dual.d87 = mpc_socp__qoco_solver->sol->z[64];
  mpc_socp__CPG_Dual.d88 = mpc_socp__qoco_solver->sol->z[65];
  mpc_socp__CPG_Dual.d89[0] = mpc_socp__qoco_solver->sol->y[815];
  mpc_socp__CPG_Dual.d89[1] = mpc_socp__qoco_solver->sol->y[816];
  mpc_socp__CPG_Dual.d89[2] = mpc_socp__qoco_solver->sol->y[817];
  mpc_socp__CPG_Dual.d89[3] = mpc_socp__qoco_solver->sol->y[818];
  mpc_socp__CPG_Dual.d89[4] = mpc_socp__qoco_solver->sol->y[819];
  mpc_socp__CPG_Dual.d89[5] = mpc_socp__qoco_solver->sol->y[820];
  mpc_socp__CPG_Dual.d89[6] = mpc_socp__qoco_solver->sol->y[821];
  mpc_socp__CPG_Dual.d89[7] = mpc_socp__qoco_solver->sol->y[822];
  mpc_socp__CPG_Dual.d89[8] = mpc_socp__qoco_solver->sol->y[823];
  mpc_socp__CPG_Dual.d89[9] = mpc_socp__qoco_solver->sol->y[824];
  mpc_socp__CPG_Dual.d89[10] = mpc_socp__qoco_solver->sol->y[825];
  mpc_socp__CPG_Dual.d89[11] = mpc_socp__qoco_solver->sol->y[826];
  mpc_socp__CPG_Dual.d89[12] = mpc_socp__qoco_solver->sol->y[827];
  mpc_socp__CPG_Dual.d89[13] = mpc_socp__qoco_solver->sol->y[828];
  mpc_socp__CPG_Dual.d90 = mpc_socp__qoco_solver->sol->z[66];
  mpc_socp__CPG_Dual.d91 = mpc_socp__qoco_solver->sol->z[67];
  mpc_socp__CPG_Dual.d92 = mpc_socp__qoco_solver->sol->z[68];
  mpc_socp__CPG_Dual.d93[0] = mpc_socp__qoco_solver->sol->y[829];
  mpc_socp__CPG_Dual.d93[1] = mpc_socp__qoco_solver->sol->y[830];
  mpc_socp__CPG_Dual.d93[2] = mpc_socp__qoco_solver->sol->y[831];
  mpc_socp__CPG_Dual.d93[3] = mpc_socp__qoco_solver->sol->y[832];
  mpc_socp__CPG_Dual.d93[4] = mpc_socp__qoco_solver->sol->y[833];
  mpc_socp__CPG_Dual.d93[5] = mpc_socp__qoco_solver->sol->y[834];
  mpc_socp__CPG_Dual.d93[6] = mpc_socp__qoco_solver->sol->y[835];
  mpc_socp__CPG_Dual.d93[7] = mpc_socp__qoco_solver->sol->y[836];
  mpc_socp__CPG_Dual.d93[8] = mpc_socp__qoco_solver->sol->y[837];
  mpc_socp__CPG_Dual.d93[9] = mpc_socp__qoco_solver->sol->y[838];
  mpc_socp__CPG_Dual.d93[10] = mpc_socp__qoco_solver->sol->y[839];
  mpc_socp__CPG_Dual.d93[11] = mpc_socp__qoco_solver->sol->y[840];
  mpc_socp__CPG_Dual.d93[12] = mpc_socp__qoco_solver->sol->y[841];
  mpc_socp__CPG_Dual.d93[13] = mpc_socp__qoco_solver->sol->y[842];
  mpc_socp__CPG_Dual.d94 = mpc_socp__qoco_solver->sol->z[69];
  mpc_socp__CPG_Dual.d95 = mpc_socp__qoco_solver->sol->z[70];
  mpc_socp__CPG_Dual.d96 = mpc_socp__qoco_solver->sol->z[71];
  mpc_socp__CPG_Dual.d97[0] = mpc_socp__qoco_solver->sol->y[843];
  mpc_socp__CPG_Dual.d97[1] = mpc_socp__qoco_solver->sol->y[844];
  mpc_socp__CPG_Dual.d97[2] = mpc_socp__qoco_solver->sol->y[845];
  mpc_socp__CPG_Dual.d97[3] = mpc_socp__qoco_solver->sol->y[846];
  mpc_socp__CPG_Dual.d97[4] = mpc_socp__qoco_solver->sol->y[847];
  mpc_socp__CPG_Dual.d97[5] = mpc_socp__qoco_solver->sol->y[848];
  mpc_socp__CPG_Dual.d97[6] = mpc_socp__qoco_solver->sol->y[849];
  mpc_socp__CPG_Dual.d97[7] = mpc_socp__qoco_solver->sol->y[850];
  mpc_socp__CPG_Dual.d97[8] = mpc_socp__qoco_solver->sol->y[851];
  mpc_socp__CPG_Dual.d97[9] = mpc_socp__qoco_solver->sol->y[852];
  mpc_socp__CPG_Dual.d97[10] = mpc_socp__qoco_solver->sol->y[853];
  mpc_socp__CPG_Dual.d97[11] = mpc_socp__qoco_solver->sol->y[854];
  mpc_socp__CPG_Dual.d97[12] = mpc_socp__qoco_solver->sol->y[855];
  mpc_socp__CPG_Dual.d97[13] = mpc_socp__qoco_solver->sol->y[856];
  mpc_socp__CPG_Dual.d98 = mpc_socp__qoco_solver->sol->z[72];
  mpc_socp__CPG_Dual.d99 = mpc_socp__qoco_solver->sol->z[73];
  mpc_socp__CPG_Dual.d100 = mpc_socp__qoco_solver->sol->z[74];
  mpc_socp__CPG_Dual.d101[0] = mpc_socp__qoco_solver->sol->y[857];
  mpc_socp__CPG_Dual.d101[1] = mpc_socp__qoco_solver->sol->y[858];
  mpc_socp__CPG_Dual.d101[2] = mpc_socp__qoco_solver->sol->y[859];
  mpc_socp__CPG_Dual.d101[3] = mpc_socp__qoco_solver->sol->y[860];
  mpc_socp__CPG_Dual.d101[4] = mpc_socp__qoco_solver->sol->y[861];
  mpc_socp__CPG_Dual.d101[5] = mpc_socp__qoco_solver->sol->y[862];
  mpc_socp__CPG_Dual.d101[6] = mpc_socp__qoco_solver->sol->y[863];
  mpc_socp__CPG_Dual.d101[7] = mpc_socp__qoco_solver->sol->y[864];
  mpc_socp__CPG_Dual.d101[8] = mpc_socp__qoco_solver->sol->y[865];
  mpc_socp__CPG_Dual.d101[9] = mpc_socp__qoco_solver->sol->y[866];
  mpc_socp__CPG_Dual.d101[10] = mpc_socp__qoco_solver->sol->y[867];
  mpc_socp__CPG_Dual.d101[11] = mpc_socp__qoco_solver->sol->y[868];
  mpc_socp__CPG_Dual.d101[12] = mpc_socp__qoco_solver->sol->y[869];
  mpc_socp__CPG_Dual.d101[13] = mpc_socp__qoco_solver->sol->y[870];
  mpc_socp__CPG_Dual.d102 = mpc_socp__qoco_solver->sol->z[75];
  mpc_socp__CPG_Dual.d103 = mpc_socp__qoco_solver->sol->z[76];
  mpc_socp__CPG_Dual.d104 = mpc_socp__qoco_solver->sol->z[77];
  mpc_socp__CPG_Dual.d105[0] = mpc_socp__qoco_solver->sol->y[871];
  mpc_socp__CPG_Dual.d105[1] = mpc_socp__qoco_solver->sol->y[872];
  mpc_socp__CPG_Dual.d105[2] = mpc_socp__qoco_solver->sol->y[873];
  mpc_socp__CPG_Dual.d105[3] = mpc_socp__qoco_solver->sol->y[874];
  mpc_socp__CPG_Dual.d105[4] = mpc_socp__qoco_solver->sol->y[875];
  mpc_socp__CPG_Dual.d105[5] = mpc_socp__qoco_solver->sol->y[876];
  mpc_socp__CPG_Dual.d105[6] = mpc_socp__qoco_solver->sol->y[877];
  mpc_socp__CPG_Dual.d105[7] = mpc_socp__qoco_solver->sol->y[878];
  mpc_socp__CPG_Dual.d105[8] = mpc_socp__qoco_solver->sol->y[879];
  mpc_socp__CPG_Dual.d105[9] = mpc_socp__qoco_solver->sol->y[880];
  mpc_socp__CPG_Dual.d105[10] = mpc_socp__qoco_solver->sol->y[881];
  mpc_socp__CPG_Dual.d105[11] = mpc_socp__qoco_solver->sol->y[882];
  mpc_socp__CPG_Dual.d105[12] = mpc_socp__qoco_solver->sol->y[883];
  mpc_socp__CPG_Dual.d105[13] = mpc_socp__qoco_solver->sol->y[884];
  mpc_socp__CPG_Dual.d106 = mpc_socp__qoco_solver->sol->z[78];
  mpc_socp__CPG_Dual.d107 = mpc_socp__qoco_solver->sol->z[79];
  mpc_socp__CPG_Dual.d108 = mpc_socp__qoco_solver->sol->z[80];
  mpc_socp__CPG_Dual.d109[0] = mpc_socp__qoco_solver->sol->y[885];
  mpc_socp__CPG_Dual.d109[1] = mpc_socp__qoco_solver->sol->y[886];
  mpc_socp__CPG_Dual.d109[2] = mpc_socp__qoco_solver->sol->y[887];
  mpc_socp__CPG_Dual.d109[3] = mpc_socp__qoco_solver->sol->y[888];
  mpc_socp__CPG_Dual.d109[4] = mpc_socp__qoco_solver->sol->y[889];
  mpc_socp__CPG_Dual.d109[5] = mpc_socp__qoco_solver->sol->y[890];
  mpc_socp__CPG_Dual.d109[6] = mpc_socp__qoco_solver->sol->y[891];
  mpc_socp__CPG_Dual.d109[7] = mpc_socp__qoco_solver->sol->y[892];
  mpc_socp__CPG_Dual.d109[8] = mpc_socp__qoco_solver->sol->y[893];
  mpc_socp__CPG_Dual.d109[9] = mpc_socp__qoco_solver->sol->y[894];
  mpc_socp__CPG_Dual.d109[10] = mpc_socp__qoco_solver->sol->y[895];
  mpc_socp__CPG_Dual.d109[11] = mpc_socp__qoco_solver->sol->y[896];
  mpc_socp__CPG_Dual.d109[12] = mpc_socp__qoco_solver->sol->y[897];
  mpc_socp__CPG_Dual.d109[13] = mpc_socp__qoco_solver->sol->y[898];
  mpc_socp__CPG_Dual.d110 = mpc_socp__qoco_solver->sol->z[81];
  mpc_socp__CPG_Dual.d111 = mpc_socp__qoco_solver->sol->z[82];
  mpc_socp__CPG_Dual.d112 = mpc_socp__qoco_solver->sol->z[83];
  mpc_socp__CPG_Dual.d113[0] = mpc_socp__qoco_solver->sol->y[899];
  mpc_socp__CPG_Dual.d113[1] = mpc_socp__qoco_solver->sol->y[900];
  mpc_socp__CPG_Dual.d113[2] = mpc_socp__qoco_solver->sol->y[901];
  mpc_socp__CPG_Dual.d113[3] = mpc_socp__qoco_solver->sol->y[902];
  mpc_socp__CPG_Dual.d113[4] = mpc_socp__qoco_solver->sol->y[903];
  mpc_socp__CPG_Dual.d113[5] = mpc_socp__qoco_solver->sol->y[904];
  mpc_socp__CPG_Dual.d113[6] = mpc_socp__qoco_solver->sol->y[905];
  mpc_socp__CPG_Dual.d113[7] = mpc_socp__qoco_solver->sol->y[906];
  mpc_socp__CPG_Dual.d113[8] = mpc_socp__qoco_solver->sol->y[907];
  mpc_socp__CPG_Dual.d113[9] = mpc_socp__qoco_solver->sol->y[908];
  mpc_socp__CPG_Dual.d113[10] = mpc_socp__qoco_solver->sol->y[909];
  mpc_socp__CPG_Dual.d113[11] = mpc_socp__qoco_solver->sol->y[910];
  mpc_socp__CPG_Dual.d113[12] = mpc_socp__qoco_solver->sol->y[911];
  mpc_socp__CPG_Dual.d113[13] = mpc_socp__qoco_solver->sol->y[912];
  mpc_socp__CPG_Dual.d114 = mpc_socp__qoco_solver->sol->z[84];
  mpc_socp__CPG_Dual.d115 = mpc_socp__qoco_solver->sol->z[85];
  mpc_socp__CPG_Dual.d116 = mpc_socp__qoco_solver->sol->z[86];
}

// Retrieve solver info
void mpc_socp__cpg_retrieve_info(){
  mpc_socp__CPG_Info.obj_val = (mpc_socp__qoco_solver->sol->obj);
  mpc_socp__CPG_Info.iter = mpc_socp__qoco_solver->sol->iters;
  mpc_socp__CPG_Info.status = mpc_socp__qoco_solver->sol->status;
  mpc_socp__CPG_Info.pri_res = mpc_socp__qoco_solver->sol->pres;
  mpc_socp__CPG_Info.dua_res = mpc_socp__qoco_solver->sol->dres;
}

// Copy canonical parameters for preconditioning
void mpc_socp__cpg_copy_P(){
  for (i=0; i<493; i++){
    mpc_socp__Canon_Params_conditioning.P->x[i] = mpc_socp__Canon_Params.P->x[i];
  }
}

void mpc_socp__cpg_copy_c(){
  for (i=0; i<1087; i++){
    mpc_socp__Canon_Params_conditioning.c[i] = mpc_socp__Canon_Params.c[i];
  }
}

void mpc_socp__cpg_copy_A(){
  for (i=0; i<8308; i++){
    mpc_socp__Canon_Params_conditioning.A->x[i] = mpc_socp__Canon_Params.A->x[i];
  }
}

void mpc_socp__cpg_copy_b(){
  for (i=0; i<913; i++){
    mpc_socp__Canon_Params_conditioning.b[i] = mpc_socp__Canon_Params.b[i];
  }
}

void mpc_socp__cpg_copy_G(){
  for (i=0; i<464; i++){
    mpc_socp__Canon_Params_conditioning.G->x[i] = mpc_socp__Canon_Params.G->x[i];
  }
}

void mpc_socp__cpg_copy_h(){
  for (i=0; i<435; i++){
    mpc_socp__Canon_Params_conditioning.h[i] = mpc_socp__Canon_Params.h[i];
  }
}

void mpc_socp__cpg_copy_all(){
  mpc_socp__cpg_copy_P();
  mpc_socp__cpg_copy_c();
  mpc_socp__cpg_copy_A();
  mpc_socp__cpg_copy_b();
  mpc_socp__cpg_copy_G();
  mpc_socp__cpg_copy_h();
}

// Solve via canonicalization, canonical solve, retrieval
void mpc_socp__cpg_solve(){
  // Canonicalize if necessary
  if (mpc_socp__Canon_Outdated.A) {
    mpc_socp__cpg_canonicalize_A();
  }
  if (mpc_socp__Canon_Outdated.b) {
    mpc_socp__cpg_canonicalize_b();
  }
  if (mpc_socp__Canon_Outdated.G) {
    mpc_socp__cpg_canonicalize_G();
  }
  if (mpc_socp__Canon_Outdated.h) {
    mpc_socp__cpg_canonicalize_h();
  }
  if (!mpc_socp__qoco_solver ) {
    mpc_socp__cpg_copy_all();
   QOCOCscMatrix* P = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* A = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* G = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   qoco_set_csc(P, 1087, 1087, mpc_socp__Canon_Params.P->nnz, mpc_socp__Canon_Params.P->x, mpc_socp__Canon_Params.P->p, mpc_socp__Canon_Params.P->i);
   qoco_set_csc(A, 913, 1087, mpc_socp__Canon_Params.A->nnz, mpc_socp__Canon_Params.A->x, mpc_socp__Canon_Params.A->p, mpc_socp__Canon_Params.A->i);
   qoco_set_csc(G, 435, 1087, mpc_socp__Canon_Params.G->nnz, mpc_socp__Canon_Params.G->x, mpc_socp__Canon_Params.G->p, mpc_socp__Canon_Params.G->i);
   QOCOSettings* qoco_settings = (QOCOSettings*)malloc(sizeof(QOCOSettings));
   set_default_settings(qoco_settings);
   mpc_socp__qoco_solver = (QOCOSolver*)malloc(sizeof(QOCOSolver));
   qoco_setup(mpc_socp__qoco_solver, 1087, 435, 913, P, mpc_socp__Canon_Params.c, A, mpc_socp__Canon_Params.b, G, mpc_socp__Canon_Params.h, 87, 87, (int *) &mpc_socp__qoco_q, qoco_settings);
  }
  if (mpc_socp__Canon_Outdated.G) {
    update_matrix_data(mpc_socp__qoco_solver, NULL, NULL, mpc_socp__Canon_Params.G->x);
  }
  if (mpc_socp__Canon_Outdated.h) {
    update_vector_data(mpc_socp__qoco_solver, NULL, NULL, mpc_socp__Canon_Params.h);
  }
  if (mpc_socp__Canon_Outdated.A) {
    update_matrix_data(mpc_socp__qoco_solver, NULL, mpc_socp__Canon_Params.A->x, NULL);
  }
  if (mpc_socp__Canon_Outdated.b) {
    update_vector_data(mpc_socp__qoco_solver, NULL, mpc_socp__Canon_Params.b, NULL);
  }
  mpc_socp__qoco_solver->settings->max_iters = mpc_socp__Canon_Settings.max_iters;
  mpc_socp__qoco_solver->settings->bisect_iters = mpc_socp__Canon_Settings.bisect_iters;
  mpc_socp__qoco_solver->settings->ruiz_iters = mpc_socp__Canon_Settings.ruiz_iters;
  mpc_socp__qoco_solver->settings->iter_ref_iters = mpc_socp__Canon_Settings.iter_ref_iters;
  mpc_socp__qoco_solver->settings->kkt_static_reg = mpc_socp__Canon_Settings.kkt_static_reg;
  mpc_socp__qoco_solver->settings->kkt_dynamic_reg = mpc_socp__Canon_Settings.kkt_dynamic_reg;
  mpc_socp__qoco_solver->settings->abstol = mpc_socp__Canon_Settings.abstol;
  mpc_socp__qoco_solver->settings->reltol = mpc_socp__Canon_Settings.reltol;
  mpc_socp__qoco_solver->settings->abstol_inacc = mpc_socp__Canon_Settings.abstol_inacc;
  mpc_socp__qoco_solver->settings->reltol_inacc = mpc_socp__Canon_Settings.reltol_inacc;
  mpc_socp__qoco_solver->settings->verbose = mpc_socp__Canon_Settings.verbose;
  // Solve with QOCO
  qoco_solve(mpc_socp__qoco_solver);
  // Retrieve results
  mpc_socp__cpg_retrieve_prim();
  mpc_socp__cpg_retrieve_dual();
  mpc_socp__cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  mpc_socp__Canon_Outdated.A = 0;
  mpc_socp__Canon_Outdated.b = 0;
  mpc_socp__Canon_Outdated.G = 0;
  mpc_socp__Canon_Outdated.h = 0;
}

// Update solver settings
void mpc_socp__cpg_set_solver_default_settings(){
  mpc_socp__Canon_Settings.max_iters = 200;
  mpc_socp__Canon_Settings.bisect_iters = 5;
  mpc_socp__Canon_Settings.ruiz_iters = 0;
  mpc_socp__Canon_Settings.iter_ref_iters = 1;
  mpc_socp__Canon_Settings.kkt_static_reg = 1e-8;
  mpc_socp__Canon_Settings.kkt_dynamic_reg = 1e-8;
  mpc_socp__Canon_Settings.abstol = 1e-7;
  mpc_socp__Canon_Settings.reltol = 1e-7;
  mpc_socp__Canon_Settings.abstol_inacc = 1e-5;
  mpc_socp__Canon_Settings.reltol_inacc = 1e-5;
  mpc_socp__Canon_Settings.verbose = 0;
}

void mpc_socp__cpg_set_solver_max_iters(cpg_int max_iters_new){
  mpc_socp__Canon_Settings.max_iters = max_iters_new;
}

void mpc_socp__cpg_set_solver_bisect_iters(cpg_int bisect_iters_new){
  mpc_socp__Canon_Settings.bisect_iters = bisect_iters_new;
}

void mpc_socp__cpg_set_solver_ruiz_iters(cpg_int ruiz_iters_new){
  mpc_socp__Canon_Settings.ruiz_iters = ruiz_iters_new;
}

void mpc_socp__cpg_set_solver_iter_ref_iters(cpg_int iter_ref_iters_new){
  mpc_socp__Canon_Settings.iter_ref_iters = iter_ref_iters_new;
}

void mpc_socp__cpg_set_solver_kkt_static_reg(cpg_float kkt_static_reg_new){
  mpc_socp__Canon_Settings.kkt_static_reg = kkt_static_reg_new;
}

void mpc_socp__cpg_set_solver_kkt_dynamic_reg(cpg_float kkt_dynamic_reg_new){
  mpc_socp__Canon_Settings.kkt_dynamic_reg = kkt_dynamic_reg_new;
}

void mpc_socp__cpg_set_solver_abstol(cpg_float abstol_new){
  mpc_socp__Canon_Settings.abstol = abstol_new;
}

void mpc_socp__cpg_set_solver_reltol(cpg_float reltol_new){
  mpc_socp__Canon_Settings.reltol = reltol_new;
}

void mpc_socp__cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  mpc_socp__Canon_Settings.abstol_inacc = abstol_inacc_new;
}

void mpc_socp__cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  mpc_socp__Canon_Settings.reltol_inacc = reltol_inacc_new;
}

void mpc_socp__cpg_set_solver_verbose(cpg_int verbose_new){
  mpc_socp__Canon_Settings.verbose = verbose_new;
}
