
/*
Auto-generated by CVXPYgen on June 03, 2025 at 00:31:27.
Content: Python binding with pybind11.
*/

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <ctime>
#include "cpg_module.hpp"

extern "C" {
    #include "include/cpg_workspace.h"
    #include "include/cpg_solve.h"
}

namespace py = pybind11;

static int i;

scp_socp__CPG_Result_cpp_t scp_socp__solve_cpp(struct scp_socp__CPG_Updated_cpp_t& CPG_Updated_cpp, struct scp_socp__CPG_Params_cpp_t& CPG_Params_cpp){

    // Pass changed user-defined parameter values to the solver
    if (CPG_Updated_cpp.param15) {
        scp_socp__cpg_update_param15(CPG_Params_cpp.param15);
    }
    if (CPG_Updated_cpp.param16) {
        scp_socp__cpg_update_param16(CPG_Params_cpp.param16);
    }
    if (CPG_Updated_cpp.param17) {
        scp_socp__cpg_update_param17(CPG_Params_cpp.param17);
    }
    if (CPG_Updated_cpp.param7) {
        for(i=0; i<420; i++) {
            scp_socp__cpg_update_param7(i, CPG_Params_cpp.param7[i]);
        }
    }
    if (CPG_Updated_cpp.param18) {
        scp_socp__cpg_update_param18(CPG_Params_cpp.param18);
    }
    if (CPG_Updated_cpp.param20) {
        scp_socp__cpg_update_param20(CPG_Params_cpp.param20);
    }
    if (CPG_Updated_cpp.param8) {
        for(i=0; i<90; i++) {
            scp_socp__cpg_update_param8(i, CPG_Params_cpp.param8[i]);
        }
    }
    if (CPG_Updated_cpp.param19) {
        scp_socp__cpg_update_param19(CPG_Params_cpp.param19);
    }
    if (CPG_Updated_cpp.param21) {
        scp_socp__cpg_update_param21(CPG_Params_cpp.param21);
    }
    if (CPG_Updated_cpp.param9) {
        scp_socp__cpg_update_param9(CPG_Params_cpp.param9);
    }
    if (CPG_Updated_cpp.param10) {
        for(i=0; i<5684; i++) {
            scp_socp__cpg_update_param10(i, CPG_Params_cpp.param10[i]);
        }
    }
    if (CPG_Updated_cpp.param11) {
        for(i=0; i<1218; i++) {
            scp_socp__cpg_update_param11(i, CPG_Params_cpp.param11[i]);
        }
    }
    if (CPG_Updated_cpp.param12) {
        for(i=0; i<1218; i++) {
            scp_socp__cpg_update_param12(i, CPG_Params_cpp.param12[i]);
        }
    }
    if (CPG_Updated_cpp.param13) {
        for(i=0; i<406; i++) {
            scp_socp__cpg_update_param13(i, CPG_Params_cpp.param13[i]);
        }
    }
    if (CPG_Updated_cpp.param14) {
        for(i=0; i<406; i++) {
            scp_socp__cpg_update_param14(i, CPG_Params_cpp.param14[i]);
        }
    }

    // Solve
    std::clock_t ASA_start = std::clock();
    scp_socp__cpg_solve();
    std::clock_t ASA_end = std::clock();

    // Arrange and return results
    scp_socp__CPG_Prim_cpp_t CPG_Prim_cpp {};
    CPG_Prim_cpp.var3 = scp_socp__CPG_Prim.var3;
    for(i=0; i<406; i++) {
        CPG_Prim_cpp.var4[i] = scp_socp__CPG_Prim.var4[i];
    }
    for(i=0; i<30; i++) {
        CPG_Prim_cpp.var5[i] = scp_socp__CPG_Prim.var5[i];
    }
    CPG_Prim_cpp.var6 = scp_socp__CPG_Prim.var6;
    for(i=0; i<420; i++) {
        CPG_Prim_cpp.var1[i] = scp_socp__CPG_Prim.var1[i];
    }
    for(i=0; i<90; i++) {
        CPG_Prim_cpp.var2[i] = scp_socp__CPG_Prim.var2[i];
    }
    scp_socp__CPG_Dual_cpp_t CPG_Dual_cpp {};
    for(i=0; i<30; i++) {
        CPG_Dual_cpp.d0[i] = scp_socp__CPG_Dual.d0[i];
    }
    CPG_Dual_cpp.d1 = scp_socp__CPG_Dual.d1;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d2[i] = scp_socp__CPG_Dual.d2[i];
    }
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d3[i] = scp_socp__CPG_Dual.d3[i];
    }
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d4[i] = scp_socp__CPG_Dual.d4[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d5[i] = scp_socp__CPG_Dual.d5[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d6[i] = scp_socp__CPG_Dual.d6[i];
    }
    CPG_Dual_cpp.d7 = scp_socp__CPG_Dual.d7;
    CPG_Dual_cpp.d8 = scp_socp__CPG_Dual.d8;
    CPG_Dual_cpp.d9 = scp_socp__CPG_Dual.d9;
    CPG_Dual_cpp.d10 = scp_socp__CPG_Dual.d10;
    CPG_Dual_cpp.d11 = scp_socp__CPG_Dual.d11;
    CPG_Dual_cpp.d12 = scp_socp__CPG_Dual.d12;
    CPG_Dual_cpp.d13 = scp_socp__CPG_Dual.d13;
    CPG_Dual_cpp.d14 = scp_socp__CPG_Dual.d14;
    CPG_Dual_cpp.d15 = scp_socp__CPG_Dual.d15;
    CPG_Dual_cpp.d16 = scp_socp__CPG_Dual.d16;
    CPG_Dual_cpp.d17 = scp_socp__CPG_Dual.d17;
    CPG_Dual_cpp.d18 = scp_socp__CPG_Dual.d18;
    CPG_Dual_cpp.d19 = scp_socp__CPG_Dual.d19;
    CPG_Dual_cpp.d20 = scp_socp__CPG_Dual.d20;
    CPG_Dual_cpp.d21 = scp_socp__CPG_Dual.d21;
    CPG_Dual_cpp.d22 = scp_socp__CPG_Dual.d22;
    CPG_Dual_cpp.d23 = scp_socp__CPG_Dual.d23;
    CPG_Dual_cpp.d24 = scp_socp__CPG_Dual.d24;
    CPG_Dual_cpp.d25 = scp_socp__CPG_Dual.d25;
    CPG_Dual_cpp.d26 = scp_socp__CPG_Dual.d26;
    CPG_Dual_cpp.d27 = scp_socp__CPG_Dual.d27;
    CPG_Dual_cpp.d28 = scp_socp__CPG_Dual.d28;
    CPG_Dual_cpp.d29 = scp_socp__CPG_Dual.d29;
    CPG_Dual_cpp.d30 = scp_socp__CPG_Dual.d30;
    CPG_Dual_cpp.d31 = scp_socp__CPG_Dual.d31;
    CPG_Dual_cpp.d32 = scp_socp__CPG_Dual.d32;
    CPG_Dual_cpp.d33 = scp_socp__CPG_Dual.d33;
    CPG_Dual_cpp.d34 = scp_socp__CPG_Dual.d34;
    CPG_Dual_cpp.d35 = scp_socp__CPG_Dual.d35;
    CPG_Dual_cpp.d36 = scp_socp__CPG_Dual.d36;
    CPG_Dual_cpp.d37 = scp_socp__CPG_Dual.d37;
    CPG_Dual_cpp.d38 = scp_socp__CPG_Dual.d38;
    CPG_Dual_cpp.d39 = scp_socp__CPG_Dual.d39;
    CPG_Dual_cpp.d40 = scp_socp__CPG_Dual.d40;
    CPG_Dual_cpp.d41 = scp_socp__CPG_Dual.d41;
    CPG_Dual_cpp.d42 = scp_socp__CPG_Dual.d42;
    CPG_Dual_cpp.d43 = scp_socp__CPG_Dual.d43;
    CPG_Dual_cpp.d44 = scp_socp__CPG_Dual.d44;
    CPG_Dual_cpp.d45 = scp_socp__CPG_Dual.d45;
    CPG_Dual_cpp.d46 = scp_socp__CPG_Dual.d46;
    CPG_Dual_cpp.d47 = scp_socp__CPG_Dual.d47;
    CPG_Dual_cpp.d48 = scp_socp__CPG_Dual.d48;
    CPG_Dual_cpp.d49 = scp_socp__CPG_Dual.d49;
    CPG_Dual_cpp.d50 = scp_socp__CPG_Dual.d50;
    CPG_Dual_cpp.d51 = scp_socp__CPG_Dual.d51;
    CPG_Dual_cpp.d52 = scp_socp__CPG_Dual.d52;
    CPG_Dual_cpp.d53 = scp_socp__CPG_Dual.d53;
    CPG_Dual_cpp.d54 = scp_socp__CPG_Dual.d54;
    CPG_Dual_cpp.d55 = scp_socp__CPG_Dual.d55;
    CPG_Dual_cpp.d56 = scp_socp__CPG_Dual.d56;
    CPG_Dual_cpp.d57 = scp_socp__CPG_Dual.d57;
    CPG_Dual_cpp.d58 = scp_socp__CPG_Dual.d58;
    CPG_Dual_cpp.d59 = scp_socp__CPG_Dual.d59;
    CPG_Dual_cpp.d60 = scp_socp__CPG_Dual.d60;
    CPG_Dual_cpp.d61 = scp_socp__CPG_Dual.d61;
    CPG_Dual_cpp.d62 = scp_socp__CPG_Dual.d62;
    CPG_Dual_cpp.d63 = scp_socp__CPG_Dual.d63;
    CPG_Dual_cpp.d64 = scp_socp__CPG_Dual.d64;
    CPG_Dual_cpp.d65 = scp_socp__CPG_Dual.d65;
    CPG_Dual_cpp.d66 = scp_socp__CPG_Dual.d66;
    CPG_Dual_cpp.d67 = scp_socp__CPG_Dual.d67;
    CPG_Dual_cpp.d68 = scp_socp__CPG_Dual.d68;
    CPG_Dual_cpp.d69 = scp_socp__CPG_Dual.d69;
    CPG_Dual_cpp.d70 = scp_socp__CPG_Dual.d70;
    CPG_Dual_cpp.d71 = scp_socp__CPG_Dual.d71;
    CPG_Dual_cpp.d72 = scp_socp__CPG_Dual.d72;
    CPG_Dual_cpp.d73 = scp_socp__CPG_Dual.d73;
    CPG_Dual_cpp.d74 = scp_socp__CPG_Dual.d74;
    CPG_Dual_cpp.d75 = scp_socp__CPG_Dual.d75;
    CPG_Dual_cpp.d76 = scp_socp__CPG_Dual.d76;
    CPG_Dual_cpp.d77 = scp_socp__CPG_Dual.d77;
    CPG_Dual_cpp.d78 = scp_socp__CPG_Dual.d78;
    CPG_Dual_cpp.d79 = scp_socp__CPG_Dual.d79;
    CPG_Dual_cpp.d80 = scp_socp__CPG_Dual.d80;
    CPG_Dual_cpp.d81 = scp_socp__CPG_Dual.d81;
    CPG_Dual_cpp.d82 = scp_socp__CPG_Dual.d82;
    CPG_Dual_cpp.d83 = scp_socp__CPG_Dual.d83;
    CPG_Dual_cpp.d84 = scp_socp__CPG_Dual.d84;
    CPG_Dual_cpp.d85 = scp_socp__CPG_Dual.d85;
    CPG_Dual_cpp.d86 = scp_socp__CPG_Dual.d86;
    CPG_Dual_cpp.d87 = scp_socp__CPG_Dual.d87;
    CPG_Dual_cpp.d88 = scp_socp__CPG_Dual.d88;
    CPG_Dual_cpp.d89 = scp_socp__CPG_Dual.d89;
    CPG_Dual_cpp.d90 = scp_socp__CPG_Dual.d90;
    CPG_Dual_cpp.d91 = scp_socp__CPG_Dual.d91;
    CPG_Dual_cpp.d92 = scp_socp__CPG_Dual.d92;
    CPG_Dual_cpp.d93 = scp_socp__CPG_Dual.d93;
    CPG_Dual_cpp.d94 = scp_socp__CPG_Dual.d94;
    CPG_Dual_cpp.d95 = scp_socp__CPG_Dual.d95;
    CPG_Dual_cpp.d96 = scp_socp__CPG_Dual.d96;
    CPG_Dual_cpp.d97 = scp_socp__CPG_Dual.d97;
    CPG_Dual_cpp.d98 = scp_socp__CPG_Dual.d98;
    CPG_Dual_cpp.d99 = scp_socp__CPG_Dual.d99;
    CPG_Dual_cpp.d100 = scp_socp__CPG_Dual.d100;
    CPG_Dual_cpp.d101 = scp_socp__CPG_Dual.d101;
    CPG_Dual_cpp.d102 = scp_socp__CPG_Dual.d102;
    CPG_Dual_cpp.d103 = scp_socp__CPG_Dual.d103;
    CPG_Dual_cpp.d104 = scp_socp__CPG_Dual.d104;
    CPG_Dual_cpp.d105 = scp_socp__CPG_Dual.d105;
    CPG_Dual_cpp.d106 = scp_socp__CPG_Dual.d106;
    CPG_Dual_cpp.d107 = scp_socp__CPG_Dual.d107;
    CPG_Dual_cpp.d108 = scp_socp__CPG_Dual.d108;
    CPG_Dual_cpp.d109 = scp_socp__CPG_Dual.d109;
    CPG_Dual_cpp.d110 = scp_socp__CPG_Dual.d110;
    CPG_Dual_cpp.d111 = scp_socp__CPG_Dual.d111;
    CPG_Dual_cpp.d112 = scp_socp__CPG_Dual.d112;
    CPG_Dual_cpp.d113 = scp_socp__CPG_Dual.d113;
    CPG_Dual_cpp.d114 = scp_socp__CPG_Dual.d114;
    CPG_Dual_cpp.d115 = scp_socp__CPG_Dual.d115;
    CPG_Dual_cpp.d116 = scp_socp__CPG_Dual.d116;
    CPG_Dual_cpp.d117 = scp_socp__CPG_Dual.d117;
    CPG_Dual_cpp.d118 = scp_socp__CPG_Dual.d118;
    CPG_Dual_cpp.d119 = scp_socp__CPG_Dual.d119;
    CPG_Dual_cpp.d120 = scp_socp__CPG_Dual.d120;
    CPG_Dual_cpp.d121 = scp_socp__CPG_Dual.d121;
    CPG_Dual_cpp.d122 = scp_socp__CPG_Dual.d122;
    CPG_Dual_cpp.d123 = scp_socp__CPG_Dual.d123;
    CPG_Dual_cpp.d124 = scp_socp__CPG_Dual.d124;
    CPG_Dual_cpp.d125 = scp_socp__CPG_Dual.d125;
    CPG_Dual_cpp.d126 = scp_socp__CPG_Dual.d126;
    CPG_Dual_cpp.d127 = scp_socp__CPG_Dual.d127;
    CPG_Dual_cpp.d128 = scp_socp__CPG_Dual.d128;
    CPG_Dual_cpp.d129 = scp_socp__CPG_Dual.d129;
    CPG_Dual_cpp.d130 = scp_socp__CPG_Dual.d130;
    CPG_Dual_cpp.d131 = scp_socp__CPG_Dual.d131;
    CPG_Dual_cpp.d132 = scp_socp__CPG_Dual.d132;
    CPG_Dual_cpp.d133 = scp_socp__CPG_Dual.d133;
    CPG_Dual_cpp.d134 = scp_socp__CPG_Dual.d134;
    CPG_Dual_cpp.d135 = scp_socp__CPG_Dual.d135;
    CPG_Dual_cpp.d136 = scp_socp__CPG_Dual.d136;
    CPG_Dual_cpp.d137 = scp_socp__CPG_Dual.d137;
    CPG_Dual_cpp.d138 = scp_socp__CPG_Dual.d138;
    CPG_Dual_cpp.d139 = scp_socp__CPG_Dual.d139;
    CPG_Dual_cpp.d140 = scp_socp__CPG_Dual.d140;
    CPG_Dual_cpp.d141 = scp_socp__CPG_Dual.d141;
    CPG_Dual_cpp.d142 = scp_socp__CPG_Dual.d142;
    CPG_Dual_cpp.d143 = scp_socp__CPG_Dual.d143;
    CPG_Dual_cpp.d144 = scp_socp__CPG_Dual.d144;
    CPG_Dual_cpp.d145 = scp_socp__CPG_Dual.d145;
    CPG_Dual_cpp.d146 = scp_socp__CPG_Dual.d146;
    CPG_Dual_cpp.d147 = scp_socp__CPG_Dual.d147;
    CPG_Dual_cpp.d148 = scp_socp__CPG_Dual.d148;
    CPG_Dual_cpp.d149 = scp_socp__CPG_Dual.d149;
    CPG_Dual_cpp.d150 = scp_socp__CPG_Dual.d150;
    CPG_Dual_cpp.d151 = scp_socp__CPG_Dual.d151;
    CPG_Dual_cpp.d152 = scp_socp__CPG_Dual.d152;
    CPG_Dual_cpp.d153 = scp_socp__CPG_Dual.d153;
    CPG_Dual_cpp.d154 = scp_socp__CPG_Dual.d154;
    CPG_Dual_cpp.d155 = scp_socp__CPG_Dual.d155;
    CPG_Dual_cpp.d156 = scp_socp__CPG_Dual.d156;
    CPG_Dual_cpp.d157 = scp_socp__CPG_Dual.d157;
    CPG_Dual_cpp.d158 = scp_socp__CPG_Dual.d158;
    CPG_Dual_cpp.d159 = scp_socp__CPG_Dual.d159;
    CPG_Dual_cpp.d160 = scp_socp__CPG_Dual.d160;
    CPG_Dual_cpp.d161 = scp_socp__CPG_Dual.d161;
    CPG_Dual_cpp.d162 = scp_socp__CPG_Dual.d162;
    CPG_Dual_cpp.d163 = scp_socp__CPG_Dual.d163;
    CPG_Dual_cpp.d164 = scp_socp__CPG_Dual.d164;
    CPG_Dual_cpp.d165 = scp_socp__CPG_Dual.d165;
    CPG_Dual_cpp.d166 = scp_socp__CPG_Dual.d166;
    CPG_Dual_cpp.d167 = scp_socp__CPG_Dual.d167;
    CPG_Dual_cpp.d168 = scp_socp__CPG_Dual.d168;
    CPG_Dual_cpp.d169 = scp_socp__CPG_Dual.d169;
    CPG_Dual_cpp.d170 = scp_socp__CPG_Dual.d170;
    CPG_Dual_cpp.d171 = scp_socp__CPG_Dual.d171;
    CPG_Dual_cpp.d172 = scp_socp__CPG_Dual.d172;
    CPG_Dual_cpp.d173 = scp_socp__CPG_Dual.d173;
    CPG_Dual_cpp.d174 = scp_socp__CPG_Dual.d174;
    CPG_Dual_cpp.d175 = scp_socp__CPG_Dual.d175;
    CPG_Dual_cpp.d176 = scp_socp__CPG_Dual.d176;
    CPG_Dual_cpp.d177 = scp_socp__CPG_Dual.d177;
    CPG_Dual_cpp.d178 = scp_socp__CPG_Dual.d178;
    CPG_Dual_cpp.d179 = scp_socp__CPG_Dual.d179;
    CPG_Dual_cpp.d180 = scp_socp__CPG_Dual.d180;
    CPG_Dual_cpp.d181 = scp_socp__CPG_Dual.d181;
    CPG_Dual_cpp.d182 = scp_socp__CPG_Dual.d182;
    CPG_Dual_cpp.d183 = scp_socp__CPG_Dual.d183;
    CPG_Dual_cpp.d184 = scp_socp__CPG_Dual.d184;
    CPG_Dual_cpp.d185 = scp_socp__CPG_Dual.d185;
    CPG_Dual_cpp.d186 = scp_socp__CPG_Dual.d186;
    CPG_Dual_cpp.d187 = scp_socp__CPG_Dual.d187;
    CPG_Dual_cpp.d188 = scp_socp__CPG_Dual.d188;
    CPG_Dual_cpp.d189 = scp_socp__CPG_Dual.d189;
    CPG_Dual_cpp.d190 = scp_socp__CPG_Dual.d190;
    CPG_Dual_cpp.d191 = scp_socp__CPG_Dual.d191;
    CPG_Dual_cpp.d192 = scp_socp__CPG_Dual.d192;
    CPG_Dual_cpp.d193 = scp_socp__CPG_Dual.d193;
    CPG_Dual_cpp.d194 = scp_socp__CPG_Dual.d194;
    CPG_Dual_cpp.d195 = scp_socp__CPG_Dual.d195;
    CPG_Dual_cpp.d196 = scp_socp__CPG_Dual.d196;
    CPG_Dual_cpp.d197 = scp_socp__CPG_Dual.d197;
    CPG_Dual_cpp.d198 = scp_socp__CPG_Dual.d198;
    CPG_Dual_cpp.d199 = scp_socp__CPG_Dual.d199;
    CPG_Dual_cpp.d200 = scp_socp__CPG_Dual.d200;
    CPG_Dual_cpp.d201 = scp_socp__CPG_Dual.d201;
    CPG_Dual_cpp.d202 = scp_socp__CPG_Dual.d202;
    CPG_Dual_cpp.d203 = scp_socp__CPG_Dual.d203;
    CPG_Dual_cpp.d204 = scp_socp__CPG_Dual.d204;
    CPG_Dual_cpp.d205 = scp_socp__CPG_Dual.d205;
    CPG_Dual_cpp.d206 = scp_socp__CPG_Dual.d206;
    CPG_Dual_cpp.d207 = scp_socp__CPG_Dual.d207;
    CPG_Dual_cpp.d208 = scp_socp__CPG_Dual.d208;
    CPG_Dual_cpp.d209 = scp_socp__CPG_Dual.d209;
    CPG_Dual_cpp.d210 = scp_socp__CPG_Dual.d210;
    CPG_Dual_cpp.d211 = scp_socp__CPG_Dual.d211;
    CPG_Dual_cpp.d212 = scp_socp__CPG_Dual.d212;
    CPG_Dual_cpp.d213 = scp_socp__CPG_Dual.d213;
    CPG_Dual_cpp.d214 = scp_socp__CPG_Dual.d214;
    CPG_Dual_cpp.d215 = scp_socp__CPG_Dual.d215;
    CPG_Dual_cpp.d216 = scp_socp__CPG_Dual.d216;
    CPG_Dual_cpp.d217 = scp_socp__CPG_Dual.d217;
    CPG_Dual_cpp.d218 = scp_socp__CPG_Dual.d218;
    CPG_Dual_cpp.d219 = scp_socp__CPG_Dual.d219;
    CPG_Dual_cpp.d220 = scp_socp__CPG_Dual.d220;
    CPG_Dual_cpp.d221 = scp_socp__CPG_Dual.d221;
    CPG_Dual_cpp.d222 = scp_socp__CPG_Dual.d222;
    CPG_Dual_cpp.d223 = scp_socp__CPG_Dual.d223;
    CPG_Dual_cpp.d224 = scp_socp__CPG_Dual.d224;
    CPG_Dual_cpp.d225 = scp_socp__CPG_Dual.d225;
    CPG_Dual_cpp.d226 = scp_socp__CPG_Dual.d226;
    CPG_Dual_cpp.d227 = scp_socp__CPG_Dual.d227;
    CPG_Dual_cpp.d228 = scp_socp__CPG_Dual.d228;
    CPG_Dual_cpp.d229 = scp_socp__CPG_Dual.d229;
    CPG_Dual_cpp.d230 = scp_socp__CPG_Dual.d230;
    CPG_Dual_cpp.d231 = scp_socp__CPG_Dual.d231;
    CPG_Dual_cpp.d232 = scp_socp__CPG_Dual.d232;
    CPG_Dual_cpp.d233 = scp_socp__CPG_Dual.d233;
    CPG_Dual_cpp.d234 = scp_socp__CPG_Dual.d234;
    CPG_Dual_cpp.d235 = scp_socp__CPG_Dual.d235;
    CPG_Dual_cpp.d236 = scp_socp__CPG_Dual.d236;
    CPG_Dual_cpp.d237 = scp_socp__CPG_Dual.d237;
    CPG_Dual_cpp.d238 = scp_socp__CPG_Dual.d238;
    CPG_Dual_cpp.d239 = scp_socp__CPG_Dual.d239;
    CPG_Dual_cpp.d240 = scp_socp__CPG_Dual.d240;
    CPG_Dual_cpp.d241 = scp_socp__CPG_Dual.d241;
    CPG_Dual_cpp.d242 = scp_socp__CPG_Dual.d242;
    CPG_Dual_cpp.d243 = scp_socp__CPG_Dual.d243;
    CPG_Dual_cpp.d244 = scp_socp__CPG_Dual.d244;
    CPG_Dual_cpp.d245 = scp_socp__CPG_Dual.d245;
    CPG_Dual_cpp.d246 = scp_socp__CPG_Dual.d246;
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d247[i] = scp_socp__CPG_Dual.d247[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d248[i] = scp_socp__CPG_Dual.d248[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d249[i] = scp_socp__CPG_Dual.d249[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d250[i] = scp_socp__CPG_Dual.d250[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d251[i] = scp_socp__CPG_Dual.d251[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d252[i] = scp_socp__CPG_Dual.d252[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d253[i] = scp_socp__CPG_Dual.d253[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d254[i] = scp_socp__CPG_Dual.d254[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d255[i] = scp_socp__CPG_Dual.d255[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d256[i] = scp_socp__CPG_Dual.d256[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d257[i] = scp_socp__CPG_Dual.d257[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d258[i] = scp_socp__CPG_Dual.d258[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d259[i] = scp_socp__CPG_Dual.d259[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d260[i] = scp_socp__CPG_Dual.d260[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d261[i] = scp_socp__CPG_Dual.d261[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d262[i] = scp_socp__CPG_Dual.d262[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d263[i] = scp_socp__CPG_Dual.d263[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d264[i] = scp_socp__CPG_Dual.d264[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d265[i] = scp_socp__CPG_Dual.d265[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d266[i] = scp_socp__CPG_Dual.d266[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d267[i] = scp_socp__CPG_Dual.d267[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d268[i] = scp_socp__CPG_Dual.d268[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d269[i] = scp_socp__CPG_Dual.d269[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d270[i] = scp_socp__CPG_Dual.d270[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d271[i] = scp_socp__CPG_Dual.d271[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d272[i] = scp_socp__CPG_Dual.d272[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d273[i] = scp_socp__CPG_Dual.d273[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d274[i] = scp_socp__CPG_Dual.d274[i];
    }
    for(i=0; i<14; i++) {
        CPG_Dual_cpp.d275[i] = scp_socp__CPG_Dual.d275[i];
    }
    scp_socp__CPG_Info_cpp_t CPG_Info_cpp {};
    CPG_Info_cpp.obj_val = scp_socp__CPG_Info.obj_val;
    CPG_Info_cpp.iter = scp_socp__CPG_Info.iter;
    CPG_Info_cpp.status = scp_socp__CPG_Info.status;
    CPG_Info_cpp.pri_res = scp_socp__CPG_Info.pri_res;
    CPG_Info_cpp.dua_res = scp_socp__CPG_Info.dua_res;
    CPG_Info_cpp.time = 1.0 * (ASA_end - ASA_start) / CLOCKS_PER_SEC;
    scp_socp__CPG_Result_cpp_t CPG_Result_cpp {};
    CPG_Result_cpp.prim = CPG_Prim_cpp;
    CPG_Result_cpp.dual = CPG_Dual_cpp;
    CPG_Result_cpp.info = CPG_Info_cpp;
    return CPG_Result_cpp;

}

PYBIND11_MODULE(cpg_module, m) {

    py::class_<scp_socp__CPG_Params_cpp_t>(m, "scp_socp__cpg_params")
            .def(py::init<>())
            .def_readwrite("param15", &scp_socp__CPG_Params_cpp_t::param15)
            .def_readwrite("param16", &scp_socp__CPG_Params_cpp_t::param16)
            .def_readwrite("param17", &scp_socp__CPG_Params_cpp_t::param17)
            .def_readwrite("param7", &scp_socp__CPG_Params_cpp_t::param7)
            .def_readwrite("param18", &scp_socp__CPG_Params_cpp_t::param18)
            .def_readwrite("param20", &scp_socp__CPG_Params_cpp_t::param20)
            .def_readwrite("param8", &scp_socp__CPG_Params_cpp_t::param8)
            .def_readwrite("param19", &scp_socp__CPG_Params_cpp_t::param19)
            .def_readwrite("param21", &scp_socp__CPG_Params_cpp_t::param21)
            .def_readwrite("param9", &scp_socp__CPG_Params_cpp_t::param9)
            .def_readwrite("param10", &scp_socp__CPG_Params_cpp_t::param10)
            .def_readwrite("param11", &scp_socp__CPG_Params_cpp_t::param11)
            .def_readwrite("param12", &scp_socp__CPG_Params_cpp_t::param12)
            .def_readwrite("param13", &scp_socp__CPG_Params_cpp_t::param13)
            .def_readwrite("param14", &scp_socp__CPG_Params_cpp_t::param14)
            ;

    py::class_<scp_socp__CPG_Updated_cpp_t>(m, "scp_socp__cpg_updated")
            .def(py::init<>())
            .def_readwrite("param15", &scp_socp__CPG_Updated_cpp_t::param15)
            .def_readwrite("param16", &scp_socp__CPG_Updated_cpp_t::param16)
            .def_readwrite("param17", &scp_socp__CPG_Updated_cpp_t::param17)
            .def_readwrite("param7", &scp_socp__CPG_Updated_cpp_t::param7)
            .def_readwrite("param18", &scp_socp__CPG_Updated_cpp_t::param18)
            .def_readwrite("param20", &scp_socp__CPG_Updated_cpp_t::param20)
            .def_readwrite("param8", &scp_socp__CPG_Updated_cpp_t::param8)
            .def_readwrite("param19", &scp_socp__CPG_Updated_cpp_t::param19)
            .def_readwrite("param21", &scp_socp__CPG_Updated_cpp_t::param21)
            .def_readwrite("param9", &scp_socp__CPG_Updated_cpp_t::param9)
            .def_readwrite("param10", &scp_socp__CPG_Updated_cpp_t::param10)
            .def_readwrite("param11", &scp_socp__CPG_Updated_cpp_t::param11)
            .def_readwrite("param12", &scp_socp__CPG_Updated_cpp_t::param12)
            .def_readwrite("param13", &scp_socp__CPG_Updated_cpp_t::param13)
            .def_readwrite("param14", &scp_socp__CPG_Updated_cpp_t::param14)
            ;

    py::class_<scp_socp__CPG_Prim_cpp_t>(m, "scp_socp__cpg_prim")
            .def(py::init<>())
            .def_readwrite("var3", &scp_socp__CPG_Prim_cpp_t::var3)
            .def_readwrite("var4", &scp_socp__CPG_Prim_cpp_t::var4)
            .def_readwrite("var5", &scp_socp__CPG_Prim_cpp_t::var5)
            .def_readwrite("var6", &scp_socp__CPG_Prim_cpp_t::var6)
            .def_readwrite("var1", &scp_socp__CPG_Prim_cpp_t::var1)
            .def_readwrite("var2", &scp_socp__CPG_Prim_cpp_t::var2)
            ;

    py::class_<scp_socp__CPG_Dual_cpp_t>(m, "scp_socp__cpg_dual")
            .def(py::init<>())
            .def_readwrite("d0", &scp_socp__CPG_Dual_cpp_t::d0)
            .def_readwrite("d1", &scp_socp__CPG_Dual_cpp_t::d1)
            .def_readwrite("d2", &scp_socp__CPG_Dual_cpp_t::d2)
            .def_readwrite("d3", &scp_socp__CPG_Dual_cpp_t::d3)
            .def_readwrite("d4", &scp_socp__CPG_Dual_cpp_t::d4)
            .def_readwrite("d5", &scp_socp__CPG_Dual_cpp_t::d5)
            .def_readwrite("d6", &scp_socp__CPG_Dual_cpp_t::d6)
            .def_readwrite("d7", &scp_socp__CPG_Dual_cpp_t::d7)
            .def_readwrite("d8", &scp_socp__CPG_Dual_cpp_t::d8)
            .def_readwrite("d9", &scp_socp__CPG_Dual_cpp_t::d9)
            .def_readwrite("d10", &scp_socp__CPG_Dual_cpp_t::d10)
            .def_readwrite("d11", &scp_socp__CPG_Dual_cpp_t::d11)
            .def_readwrite("d12", &scp_socp__CPG_Dual_cpp_t::d12)
            .def_readwrite("d13", &scp_socp__CPG_Dual_cpp_t::d13)
            .def_readwrite("d14", &scp_socp__CPG_Dual_cpp_t::d14)
            .def_readwrite("d15", &scp_socp__CPG_Dual_cpp_t::d15)
            .def_readwrite("d16", &scp_socp__CPG_Dual_cpp_t::d16)
            .def_readwrite("d17", &scp_socp__CPG_Dual_cpp_t::d17)
            .def_readwrite("d18", &scp_socp__CPG_Dual_cpp_t::d18)
            .def_readwrite("d19", &scp_socp__CPG_Dual_cpp_t::d19)
            .def_readwrite("d20", &scp_socp__CPG_Dual_cpp_t::d20)
            .def_readwrite("d21", &scp_socp__CPG_Dual_cpp_t::d21)
            .def_readwrite("d22", &scp_socp__CPG_Dual_cpp_t::d22)
            .def_readwrite("d23", &scp_socp__CPG_Dual_cpp_t::d23)
            .def_readwrite("d24", &scp_socp__CPG_Dual_cpp_t::d24)
            .def_readwrite("d25", &scp_socp__CPG_Dual_cpp_t::d25)
            .def_readwrite("d26", &scp_socp__CPG_Dual_cpp_t::d26)
            .def_readwrite("d27", &scp_socp__CPG_Dual_cpp_t::d27)
            .def_readwrite("d28", &scp_socp__CPG_Dual_cpp_t::d28)
            .def_readwrite("d29", &scp_socp__CPG_Dual_cpp_t::d29)
            .def_readwrite("d30", &scp_socp__CPG_Dual_cpp_t::d30)
            .def_readwrite("d31", &scp_socp__CPG_Dual_cpp_t::d31)
            .def_readwrite("d32", &scp_socp__CPG_Dual_cpp_t::d32)
            .def_readwrite("d33", &scp_socp__CPG_Dual_cpp_t::d33)
            .def_readwrite("d34", &scp_socp__CPG_Dual_cpp_t::d34)
            .def_readwrite("d35", &scp_socp__CPG_Dual_cpp_t::d35)
            .def_readwrite("d36", &scp_socp__CPG_Dual_cpp_t::d36)
            .def_readwrite("d37", &scp_socp__CPG_Dual_cpp_t::d37)
            .def_readwrite("d38", &scp_socp__CPG_Dual_cpp_t::d38)
            .def_readwrite("d39", &scp_socp__CPG_Dual_cpp_t::d39)
            .def_readwrite("d40", &scp_socp__CPG_Dual_cpp_t::d40)
            .def_readwrite("d41", &scp_socp__CPG_Dual_cpp_t::d41)
            .def_readwrite("d42", &scp_socp__CPG_Dual_cpp_t::d42)
            .def_readwrite("d43", &scp_socp__CPG_Dual_cpp_t::d43)
            .def_readwrite("d44", &scp_socp__CPG_Dual_cpp_t::d44)
            .def_readwrite("d45", &scp_socp__CPG_Dual_cpp_t::d45)
            .def_readwrite("d46", &scp_socp__CPG_Dual_cpp_t::d46)
            .def_readwrite("d47", &scp_socp__CPG_Dual_cpp_t::d47)
            .def_readwrite("d48", &scp_socp__CPG_Dual_cpp_t::d48)
            .def_readwrite("d49", &scp_socp__CPG_Dual_cpp_t::d49)
            .def_readwrite("d50", &scp_socp__CPG_Dual_cpp_t::d50)
            .def_readwrite("d51", &scp_socp__CPG_Dual_cpp_t::d51)
            .def_readwrite("d52", &scp_socp__CPG_Dual_cpp_t::d52)
            .def_readwrite("d53", &scp_socp__CPG_Dual_cpp_t::d53)
            .def_readwrite("d54", &scp_socp__CPG_Dual_cpp_t::d54)
            .def_readwrite("d55", &scp_socp__CPG_Dual_cpp_t::d55)
            .def_readwrite("d56", &scp_socp__CPG_Dual_cpp_t::d56)
            .def_readwrite("d57", &scp_socp__CPG_Dual_cpp_t::d57)
            .def_readwrite("d58", &scp_socp__CPG_Dual_cpp_t::d58)
            .def_readwrite("d59", &scp_socp__CPG_Dual_cpp_t::d59)
            .def_readwrite("d60", &scp_socp__CPG_Dual_cpp_t::d60)
            .def_readwrite("d61", &scp_socp__CPG_Dual_cpp_t::d61)
            .def_readwrite("d62", &scp_socp__CPG_Dual_cpp_t::d62)
            .def_readwrite("d63", &scp_socp__CPG_Dual_cpp_t::d63)
            .def_readwrite("d64", &scp_socp__CPG_Dual_cpp_t::d64)
            .def_readwrite("d65", &scp_socp__CPG_Dual_cpp_t::d65)
            .def_readwrite("d66", &scp_socp__CPG_Dual_cpp_t::d66)
            .def_readwrite("d67", &scp_socp__CPG_Dual_cpp_t::d67)
            .def_readwrite("d68", &scp_socp__CPG_Dual_cpp_t::d68)
            .def_readwrite("d69", &scp_socp__CPG_Dual_cpp_t::d69)
            .def_readwrite("d70", &scp_socp__CPG_Dual_cpp_t::d70)
            .def_readwrite("d71", &scp_socp__CPG_Dual_cpp_t::d71)
            .def_readwrite("d72", &scp_socp__CPG_Dual_cpp_t::d72)
            .def_readwrite("d73", &scp_socp__CPG_Dual_cpp_t::d73)
            .def_readwrite("d74", &scp_socp__CPG_Dual_cpp_t::d74)
            .def_readwrite("d75", &scp_socp__CPG_Dual_cpp_t::d75)
            .def_readwrite("d76", &scp_socp__CPG_Dual_cpp_t::d76)
            .def_readwrite("d77", &scp_socp__CPG_Dual_cpp_t::d77)
            .def_readwrite("d78", &scp_socp__CPG_Dual_cpp_t::d78)
            .def_readwrite("d79", &scp_socp__CPG_Dual_cpp_t::d79)
            .def_readwrite("d80", &scp_socp__CPG_Dual_cpp_t::d80)
            .def_readwrite("d81", &scp_socp__CPG_Dual_cpp_t::d81)
            .def_readwrite("d82", &scp_socp__CPG_Dual_cpp_t::d82)
            .def_readwrite("d83", &scp_socp__CPG_Dual_cpp_t::d83)
            .def_readwrite("d84", &scp_socp__CPG_Dual_cpp_t::d84)
            .def_readwrite("d85", &scp_socp__CPG_Dual_cpp_t::d85)
            .def_readwrite("d86", &scp_socp__CPG_Dual_cpp_t::d86)
            .def_readwrite("d87", &scp_socp__CPG_Dual_cpp_t::d87)
            .def_readwrite("d88", &scp_socp__CPG_Dual_cpp_t::d88)
            .def_readwrite("d89", &scp_socp__CPG_Dual_cpp_t::d89)
            .def_readwrite("d90", &scp_socp__CPG_Dual_cpp_t::d90)
            .def_readwrite("d91", &scp_socp__CPG_Dual_cpp_t::d91)
            .def_readwrite("d92", &scp_socp__CPG_Dual_cpp_t::d92)
            .def_readwrite("d93", &scp_socp__CPG_Dual_cpp_t::d93)
            .def_readwrite("d94", &scp_socp__CPG_Dual_cpp_t::d94)
            .def_readwrite("d95", &scp_socp__CPG_Dual_cpp_t::d95)
            .def_readwrite("d96", &scp_socp__CPG_Dual_cpp_t::d96)
            .def_readwrite("d97", &scp_socp__CPG_Dual_cpp_t::d97)
            .def_readwrite("d98", &scp_socp__CPG_Dual_cpp_t::d98)
            .def_readwrite("d99", &scp_socp__CPG_Dual_cpp_t::d99)
            .def_readwrite("d100", &scp_socp__CPG_Dual_cpp_t::d100)
            .def_readwrite("d101", &scp_socp__CPG_Dual_cpp_t::d101)
            .def_readwrite("d102", &scp_socp__CPG_Dual_cpp_t::d102)
            .def_readwrite("d103", &scp_socp__CPG_Dual_cpp_t::d103)
            .def_readwrite("d104", &scp_socp__CPG_Dual_cpp_t::d104)
            .def_readwrite("d105", &scp_socp__CPG_Dual_cpp_t::d105)
            .def_readwrite("d106", &scp_socp__CPG_Dual_cpp_t::d106)
            .def_readwrite("d107", &scp_socp__CPG_Dual_cpp_t::d107)
            .def_readwrite("d108", &scp_socp__CPG_Dual_cpp_t::d108)
            .def_readwrite("d109", &scp_socp__CPG_Dual_cpp_t::d109)
            .def_readwrite("d110", &scp_socp__CPG_Dual_cpp_t::d110)
            .def_readwrite("d111", &scp_socp__CPG_Dual_cpp_t::d111)
            .def_readwrite("d112", &scp_socp__CPG_Dual_cpp_t::d112)
            .def_readwrite("d113", &scp_socp__CPG_Dual_cpp_t::d113)
            .def_readwrite("d114", &scp_socp__CPG_Dual_cpp_t::d114)
            .def_readwrite("d115", &scp_socp__CPG_Dual_cpp_t::d115)
            .def_readwrite("d116", &scp_socp__CPG_Dual_cpp_t::d116)
            .def_readwrite("d117", &scp_socp__CPG_Dual_cpp_t::d117)
            .def_readwrite("d118", &scp_socp__CPG_Dual_cpp_t::d118)
            .def_readwrite("d119", &scp_socp__CPG_Dual_cpp_t::d119)
            .def_readwrite("d120", &scp_socp__CPG_Dual_cpp_t::d120)
            .def_readwrite("d121", &scp_socp__CPG_Dual_cpp_t::d121)
            .def_readwrite("d122", &scp_socp__CPG_Dual_cpp_t::d122)
            .def_readwrite("d123", &scp_socp__CPG_Dual_cpp_t::d123)
            .def_readwrite("d124", &scp_socp__CPG_Dual_cpp_t::d124)
            .def_readwrite("d125", &scp_socp__CPG_Dual_cpp_t::d125)
            .def_readwrite("d126", &scp_socp__CPG_Dual_cpp_t::d126)
            .def_readwrite("d127", &scp_socp__CPG_Dual_cpp_t::d127)
            .def_readwrite("d128", &scp_socp__CPG_Dual_cpp_t::d128)
            .def_readwrite("d129", &scp_socp__CPG_Dual_cpp_t::d129)
            .def_readwrite("d130", &scp_socp__CPG_Dual_cpp_t::d130)
            .def_readwrite("d131", &scp_socp__CPG_Dual_cpp_t::d131)
            .def_readwrite("d132", &scp_socp__CPG_Dual_cpp_t::d132)
            .def_readwrite("d133", &scp_socp__CPG_Dual_cpp_t::d133)
            .def_readwrite("d134", &scp_socp__CPG_Dual_cpp_t::d134)
            .def_readwrite("d135", &scp_socp__CPG_Dual_cpp_t::d135)
            .def_readwrite("d136", &scp_socp__CPG_Dual_cpp_t::d136)
            .def_readwrite("d137", &scp_socp__CPG_Dual_cpp_t::d137)
            .def_readwrite("d138", &scp_socp__CPG_Dual_cpp_t::d138)
            .def_readwrite("d139", &scp_socp__CPG_Dual_cpp_t::d139)
            .def_readwrite("d140", &scp_socp__CPG_Dual_cpp_t::d140)
            .def_readwrite("d141", &scp_socp__CPG_Dual_cpp_t::d141)
            .def_readwrite("d142", &scp_socp__CPG_Dual_cpp_t::d142)
            .def_readwrite("d143", &scp_socp__CPG_Dual_cpp_t::d143)
            .def_readwrite("d144", &scp_socp__CPG_Dual_cpp_t::d144)
            .def_readwrite("d145", &scp_socp__CPG_Dual_cpp_t::d145)
            .def_readwrite("d146", &scp_socp__CPG_Dual_cpp_t::d146)
            .def_readwrite("d147", &scp_socp__CPG_Dual_cpp_t::d147)
            .def_readwrite("d148", &scp_socp__CPG_Dual_cpp_t::d148)
            .def_readwrite("d149", &scp_socp__CPG_Dual_cpp_t::d149)
            .def_readwrite("d150", &scp_socp__CPG_Dual_cpp_t::d150)
            .def_readwrite("d151", &scp_socp__CPG_Dual_cpp_t::d151)
            .def_readwrite("d152", &scp_socp__CPG_Dual_cpp_t::d152)
            .def_readwrite("d153", &scp_socp__CPG_Dual_cpp_t::d153)
            .def_readwrite("d154", &scp_socp__CPG_Dual_cpp_t::d154)
            .def_readwrite("d155", &scp_socp__CPG_Dual_cpp_t::d155)
            .def_readwrite("d156", &scp_socp__CPG_Dual_cpp_t::d156)
            .def_readwrite("d157", &scp_socp__CPG_Dual_cpp_t::d157)
            .def_readwrite("d158", &scp_socp__CPG_Dual_cpp_t::d158)
            .def_readwrite("d159", &scp_socp__CPG_Dual_cpp_t::d159)
            .def_readwrite("d160", &scp_socp__CPG_Dual_cpp_t::d160)
            .def_readwrite("d161", &scp_socp__CPG_Dual_cpp_t::d161)
            .def_readwrite("d162", &scp_socp__CPG_Dual_cpp_t::d162)
            .def_readwrite("d163", &scp_socp__CPG_Dual_cpp_t::d163)
            .def_readwrite("d164", &scp_socp__CPG_Dual_cpp_t::d164)
            .def_readwrite("d165", &scp_socp__CPG_Dual_cpp_t::d165)
            .def_readwrite("d166", &scp_socp__CPG_Dual_cpp_t::d166)
            .def_readwrite("d167", &scp_socp__CPG_Dual_cpp_t::d167)
            .def_readwrite("d168", &scp_socp__CPG_Dual_cpp_t::d168)
            .def_readwrite("d169", &scp_socp__CPG_Dual_cpp_t::d169)
            .def_readwrite("d170", &scp_socp__CPG_Dual_cpp_t::d170)
            .def_readwrite("d171", &scp_socp__CPG_Dual_cpp_t::d171)
            .def_readwrite("d172", &scp_socp__CPG_Dual_cpp_t::d172)
            .def_readwrite("d173", &scp_socp__CPG_Dual_cpp_t::d173)
            .def_readwrite("d174", &scp_socp__CPG_Dual_cpp_t::d174)
            .def_readwrite("d175", &scp_socp__CPG_Dual_cpp_t::d175)
            .def_readwrite("d176", &scp_socp__CPG_Dual_cpp_t::d176)
            .def_readwrite("d177", &scp_socp__CPG_Dual_cpp_t::d177)
            .def_readwrite("d178", &scp_socp__CPG_Dual_cpp_t::d178)
            .def_readwrite("d179", &scp_socp__CPG_Dual_cpp_t::d179)
            .def_readwrite("d180", &scp_socp__CPG_Dual_cpp_t::d180)
            .def_readwrite("d181", &scp_socp__CPG_Dual_cpp_t::d181)
            .def_readwrite("d182", &scp_socp__CPG_Dual_cpp_t::d182)
            .def_readwrite("d183", &scp_socp__CPG_Dual_cpp_t::d183)
            .def_readwrite("d184", &scp_socp__CPG_Dual_cpp_t::d184)
            .def_readwrite("d185", &scp_socp__CPG_Dual_cpp_t::d185)
            .def_readwrite("d186", &scp_socp__CPG_Dual_cpp_t::d186)
            .def_readwrite("d187", &scp_socp__CPG_Dual_cpp_t::d187)
            .def_readwrite("d188", &scp_socp__CPG_Dual_cpp_t::d188)
            .def_readwrite("d189", &scp_socp__CPG_Dual_cpp_t::d189)
            .def_readwrite("d190", &scp_socp__CPG_Dual_cpp_t::d190)
            .def_readwrite("d191", &scp_socp__CPG_Dual_cpp_t::d191)
            .def_readwrite("d192", &scp_socp__CPG_Dual_cpp_t::d192)
            .def_readwrite("d193", &scp_socp__CPG_Dual_cpp_t::d193)
            .def_readwrite("d194", &scp_socp__CPG_Dual_cpp_t::d194)
            .def_readwrite("d195", &scp_socp__CPG_Dual_cpp_t::d195)
            .def_readwrite("d196", &scp_socp__CPG_Dual_cpp_t::d196)
            .def_readwrite("d197", &scp_socp__CPG_Dual_cpp_t::d197)
            .def_readwrite("d198", &scp_socp__CPG_Dual_cpp_t::d198)
            .def_readwrite("d199", &scp_socp__CPG_Dual_cpp_t::d199)
            .def_readwrite("d200", &scp_socp__CPG_Dual_cpp_t::d200)
            .def_readwrite("d201", &scp_socp__CPG_Dual_cpp_t::d201)
            .def_readwrite("d202", &scp_socp__CPG_Dual_cpp_t::d202)
            .def_readwrite("d203", &scp_socp__CPG_Dual_cpp_t::d203)
            .def_readwrite("d204", &scp_socp__CPG_Dual_cpp_t::d204)
            .def_readwrite("d205", &scp_socp__CPG_Dual_cpp_t::d205)
            .def_readwrite("d206", &scp_socp__CPG_Dual_cpp_t::d206)
            .def_readwrite("d207", &scp_socp__CPG_Dual_cpp_t::d207)
            .def_readwrite("d208", &scp_socp__CPG_Dual_cpp_t::d208)
            .def_readwrite("d209", &scp_socp__CPG_Dual_cpp_t::d209)
            .def_readwrite("d210", &scp_socp__CPG_Dual_cpp_t::d210)
            .def_readwrite("d211", &scp_socp__CPG_Dual_cpp_t::d211)
            .def_readwrite("d212", &scp_socp__CPG_Dual_cpp_t::d212)
            .def_readwrite("d213", &scp_socp__CPG_Dual_cpp_t::d213)
            .def_readwrite("d214", &scp_socp__CPG_Dual_cpp_t::d214)
            .def_readwrite("d215", &scp_socp__CPG_Dual_cpp_t::d215)
            .def_readwrite("d216", &scp_socp__CPG_Dual_cpp_t::d216)
            .def_readwrite("d217", &scp_socp__CPG_Dual_cpp_t::d217)
            .def_readwrite("d218", &scp_socp__CPG_Dual_cpp_t::d218)
            .def_readwrite("d219", &scp_socp__CPG_Dual_cpp_t::d219)
            .def_readwrite("d220", &scp_socp__CPG_Dual_cpp_t::d220)
            .def_readwrite("d221", &scp_socp__CPG_Dual_cpp_t::d221)
            .def_readwrite("d222", &scp_socp__CPG_Dual_cpp_t::d222)
            .def_readwrite("d223", &scp_socp__CPG_Dual_cpp_t::d223)
            .def_readwrite("d224", &scp_socp__CPG_Dual_cpp_t::d224)
            .def_readwrite("d225", &scp_socp__CPG_Dual_cpp_t::d225)
            .def_readwrite("d226", &scp_socp__CPG_Dual_cpp_t::d226)
            .def_readwrite("d227", &scp_socp__CPG_Dual_cpp_t::d227)
            .def_readwrite("d228", &scp_socp__CPG_Dual_cpp_t::d228)
            .def_readwrite("d229", &scp_socp__CPG_Dual_cpp_t::d229)
            .def_readwrite("d230", &scp_socp__CPG_Dual_cpp_t::d230)
            .def_readwrite("d231", &scp_socp__CPG_Dual_cpp_t::d231)
            .def_readwrite("d232", &scp_socp__CPG_Dual_cpp_t::d232)
            .def_readwrite("d233", &scp_socp__CPG_Dual_cpp_t::d233)
            .def_readwrite("d234", &scp_socp__CPG_Dual_cpp_t::d234)
            .def_readwrite("d235", &scp_socp__CPG_Dual_cpp_t::d235)
            .def_readwrite("d236", &scp_socp__CPG_Dual_cpp_t::d236)
            .def_readwrite("d237", &scp_socp__CPG_Dual_cpp_t::d237)
            .def_readwrite("d238", &scp_socp__CPG_Dual_cpp_t::d238)
            .def_readwrite("d239", &scp_socp__CPG_Dual_cpp_t::d239)
            .def_readwrite("d240", &scp_socp__CPG_Dual_cpp_t::d240)
            .def_readwrite("d241", &scp_socp__CPG_Dual_cpp_t::d241)
            .def_readwrite("d242", &scp_socp__CPG_Dual_cpp_t::d242)
            .def_readwrite("d243", &scp_socp__CPG_Dual_cpp_t::d243)
            .def_readwrite("d244", &scp_socp__CPG_Dual_cpp_t::d244)
            .def_readwrite("d245", &scp_socp__CPG_Dual_cpp_t::d245)
            .def_readwrite("d246", &scp_socp__CPG_Dual_cpp_t::d246)
            .def_readwrite("d247", &scp_socp__CPG_Dual_cpp_t::d247)
            .def_readwrite("d248", &scp_socp__CPG_Dual_cpp_t::d248)
            .def_readwrite("d249", &scp_socp__CPG_Dual_cpp_t::d249)
            .def_readwrite("d250", &scp_socp__CPG_Dual_cpp_t::d250)
            .def_readwrite("d251", &scp_socp__CPG_Dual_cpp_t::d251)
            .def_readwrite("d252", &scp_socp__CPG_Dual_cpp_t::d252)
            .def_readwrite("d253", &scp_socp__CPG_Dual_cpp_t::d253)
            .def_readwrite("d254", &scp_socp__CPG_Dual_cpp_t::d254)
            .def_readwrite("d255", &scp_socp__CPG_Dual_cpp_t::d255)
            .def_readwrite("d256", &scp_socp__CPG_Dual_cpp_t::d256)
            .def_readwrite("d257", &scp_socp__CPG_Dual_cpp_t::d257)
            .def_readwrite("d258", &scp_socp__CPG_Dual_cpp_t::d258)
            .def_readwrite("d259", &scp_socp__CPG_Dual_cpp_t::d259)
            .def_readwrite("d260", &scp_socp__CPG_Dual_cpp_t::d260)
            .def_readwrite("d261", &scp_socp__CPG_Dual_cpp_t::d261)
            .def_readwrite("d262", &scp_socp__CPG_Dual_cpp_t::d262)
            .def_readwrite("d263", &scp_socp__CPG_Dual_cpp_t::d263)
            .def_readwrite("d264", &scp_socp__CPG_Dual_cpp_t::d264)
            .def_readwrite("d265", &scp_socp__CPG_Dual_cpp_t::d265)
            .def_readwrite("d266", &scp_socp__CPG_Dual_cpp_t::d266)
            .def_readwrite("d267", &scp_socp__CPG_Dual_cpp_t::d267)
            .def_readwrite("d268", &scp_socp__CPG_Dual_cpp_t::d268)
            .def_readwrite("d269", &scp_socp__CPG_Dual_cpp_t::d269)
            .def_readwrite("d270", &scp_socp__CPG_Dual_cpp_t::d270)
            .def_readwrite("d271", &scp_socp__CPG_Dual_cpp_t::d271)
            .def_readwrite("d272", &scp_socp__CPG_Dual_cpp_t::d272)
            .def_readwrite("d273", &scp_socp__CPG_Dual_cpp_t::d273)
            .def_readwrite("d274", &scp_socp__CPG_Dual_cpp_t::d274)
            .def_readwrite("d275", &scp_socp__CPG_Dual_cpp_t::d275)
            ;

    py::class_<scp_socp__CPG_Info_cpp_t>(m, "scp_socp__cpg_info")
            .def(py::init<>())
            .def_readwrite("obj_val", &scp_socp__CPG_Info_cpp_t::obj_val)
            .def_readwrite("iter", &scp_socp__CPG_Info_cpp_t::iter)
            .def_readwrite("status", &scp_socp__CPG_Info_cpp_t::status)
            .def_readwrite("pri_res", &scp_socp__CPG_Info_cpp_t::pri_res)
            .def_readwrite("dua_res", &scp_socp__CPG_Info_cpp_t::dua_res)
            .def_readwrite("time", &scp_socp__CPG_Info_cpp_t::time)
            ;

    py::class_<scp_socp__CPG_Result_cpp_t>(m, "scp_socp__cpg_result")
            .def(py::init<>())
            .def_readwrite("cpg_prim", &scp_socp__CPG_Result_cpp_t::prim)
            .def_readwrite("cpg_dual", &scp_socp__CPG_Result_cpp_t::dual)
            .def_readwrite("cpg_info", &scp_socp__CPG_Result_cpp_t::info)
            ;

    m.def("solve", &scp_socp__solve_cpp);

    m.def("set_solver_default_settings", &scp_socp__cpg_set_solver_default_settings);
    m.def("set_solver_max_iters", &scp_socp__cpg_set_solver_max_iters);
    m.def("set_solver_bisect_iters", &scp_socp__cpg_set_solver_bisect_iters);
    m.def("set_solver_ruiz_iters", &scp_socp__cpg_set_solver_ruiz_iters);
    m.def("set_solver_iter_ref_iters", &scp_socp__cpg_set_solver_iter_ref_iters);
    m.def("set_solver_kkt_static_reg", &scp_socp__cpg_set_solver_kkt_static_reg);
    m.def("set_solver_kkt_dynamic_reg", &scp_socp__cpg_set_solver_kkt_dynamic_reg);
    m.def("set_solver_abstol", &scp_socp__cpg_set_solver_abstol);
    m.def("set_solver_reltol", &scp_socp__cpg_set_solver_reltol);
    m.def("set_solver_abstol_inacc", &scp_socp__cpg_set_solver_abstol_inacc);
    m.def("set_solver_reltol_inacc", &scp_socp__cpg_set_solver_reltol_inacc);
    m.def("set_solver_verbose", &scp_socp__cpg_set_solver_verbose);

}
